### PR TITLE
Fix Ice/timeout by making sure controller is connected

### LINKED ISSUE #3194: cpp/Ice/timeout failure (Windows, debug)
From https://github.com/zeroc-ice/ice/actions/runs/12020089884/job/33507994262?pr=3185

```
*** [61/94] Running cpp/Ice/timeout tests ***
[ running client/server test - 11/25/24 23:12:51 ]
- Config: ssl,x64,Debug
(D:\a\ice\ice\cpp\test\Ice\timeout\msbuild\server\x64\Debug\server.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=D:\a\ice\ice\cpp\test\Ice\timeout\server-112524-2312.log env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
(D:\a\ice\ice\cpp\test\Ice\timeout\msbuild\client\x64\Debug\client.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.PrintStackTraces=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=D:\a\ice\ice\cpp\test\Ice\timeout\client-112524-2312.log env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
testing connect timeout... error: D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:2387 ::Ice::ConnectTimeoutException connection establishment timed out
stack trace:
  0 Ice::Exception::Exception at D:\a\ice\ice\cpp\src\Ice\Exception.cpp:436
  1 Ice::LocalException::LocalException at D:\a\ice\ice\cpp\include\Ice\LocalException.h:25
  2 Ice::TimeoutException::TimeoutException
  3 Ice::ConnectTimeoutException::ConnectTimeoutException at D:\a\ice\ice\cpp\include\Ice\LocalExceptions.h:312
  4 Ice::ConnectionI::connectTimedOut at D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:2387
  5 `anonymous namespace'::ConnectTimerTask::runTimerTask at D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:50
  6 IceInternal::ThreadObserverTimer::runTimerTask at D:\a\ice\ice\cpp\src\Ice\Instance.cpp:270
  7 IceInternal::Timer::run at D:\a\ice\ice\cpp\src\Ice\Timer.cpp:124
  8 std::invoke<void (__cdecl IceInternal::Timer::*)(void),IceInternal::Timer *> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\include\type_traits:1711
  9 std::thread::_Invoke<std::tuple<void (__cdecl IceInternal::Timer::*)(void),IceInternal::Timer *>,0,1> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\include\thread:61
 10 00007ffa8df62ef5
 11 00007ffaab384cb0
 12 00007ffaad29edcb
saved D:\a\ice\ice\cpp\test\Ice\timeout\client-112524-2312.log
!! 11/25/24 23:12:53669 error: communicator not destroyed during global destruction.
saved D:\a\ice\ice\cpp\test\Ice\timeout\server-112524-2312.log
```

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #3194.

### CODE REVIEW

**Review by externl — APPROVED** [review]

File: csharp/test/Ice/timeout/AllTests.cs [hunk 1]
```diff
@@ -27,9 +27,11 @@ private static Ice.Connection connect(ObjectPrx prx)
     public static async Task allTests(global::Test.TestHelper helper)
     {
         Test.ControllerPrx controller =
-            Test.ControllerPrxHelper.checkedCast(
+            Test.ControllerPrxHelper.uncheckedCast(
```
Comment (pepone) [inline csharp/test/Ice/timeout/AllTests.cs:30]: Why don't use `createProxy`?

**Review by pepone — APPROVED** [review]

**Review by InsertCreativityHere — APPROVED** [review]
A very minor inconsistency here is that the `connect` loop runs for a different number of iterations in different languages. In Ruby and Swift, it runs for 10 iterations, but in the other languages it will only run for 9 (because we use a pre-decrement).

This is so minor it's completely ignorable. But, if you want to make it slightly more consistent, consider switching the other languages to a post-decrement instead.
