### PR TITLE
Fix IceStorm crash when database dir doesn't exist

### LINKED ISSUE #3639: Provide diagnostics when IceStorm database directory does not exist
IceStorm currently crashes without any  message:

```shell
% icebox --Ice.Config=config.icebox                      
libc++abi: terminating
zsh: abort      icebox --Ice.Config=config.icebox
```

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #3639.

### CODE REVIEW

File: cpp/src/IceStorm/Instance.cpp [hunk 1]
```diff
@@ -129,7 +129,13 @@ Instance::Instance(
     }
 }
 
-Instance::~Instance() = default;
+Instance::~Instance()
+{
+    // Usually they are called before destruction, but in some cases they are not, for example when the constructor
+    // of PersistentInstance fails before the database directory does not exist.
```
Comment (externl) [inline cpp/src/IceStorm/Instance.cpp:135]:
```suggestion
    // of PersistentInstance fails in the case where the database directory does not exist.
```

**Review by externl — APPROVED** [review]

**Review by pepone — APPROVED** [review]
