### PR TITLE
Fix Generation of `serialVersionUID` Default Values

### LINKED ISSUE #3312: `slice2java` Does not Generate Stable Values for `serialVersionUID` Field
Every time you run `slice2java` over a Slice file, you will get a different value for this field.
This is particularly bad, since this field is supposed to represent a stable version ID for the class.
So, having it change every time you compile the file makes it completely useless, and as a result,
it is impossible to safely serialize/deserialize generated classes in Java at the moment.

This was caused by our switch to use `shared_ptr`, so it only affects main, and not any other branches.

### PR DESCRIPTION
**Pull request by InsertCreativityHere**
This PR fixes #3312 and #3316, both of which deal with how we generate the `serialVersionUID` field in java.
All of the 'real' changes are at the top of the first file.

But, I had to switch alot of functions defined on `JavaGenerator` from being `const` methods to `static` functions.
Since the function for computing `serialVersionUID` lives outside this `JavaGenerator` class, this change was necessary for it to be able to call `typeToString`. And changing `typeToString` to `static` had some viral effects.

### CODE REVIEW

File: cpp/src/slice2java/JavaUtil.cpp [hunk 1]
```diff
@@ -381,7 +376,7 @@ Slice::JavaGenerator::fixKwd(const string& name)
 }
```
Comment (InsertCreativityHere) [inline cpp/src/slice2java/JavaUtil.cpp:377]: Everything below this line is just me switching from `<function> const` to `static <function>`.
There is no reason for these not to be static, but it just happens that I _needed_ them to be static in this PR, so I could call them from outside the class they're defined in.

File: cpp/src/slice2java/JavaUtil.h [hunk 2]
```diff
@@ -83,78 +92,67 @@ namespace Slice
...
         //
         // Return the method call necessary to obtain the static type ID for an object type.
         //
-        [[nodiscard]] std::string getStaticId(const TypePtr&, const std::string&) const;
+        [[nodiscard]] static std::string getStaticId(const TypePtr&, const std::string&);
 
         //
         // Returns the optional type corresponding to the given Slice type.
         //
-        std::string getOptionalFormat(const TypePtr&);
```
Comment (InsertCreativityHere) [inline cpp/src/slice2java/JavaUtil.h:126]: I added a `[[nodiscard]]` here. This function has no side-effects and returns a string.
So, it should probably have `[[nodiscard]]` right?

File: cpp/src/slice2java/JavaUtil.h [hunk 3]
```diff
@@ -237,11 +233,10 @@ namespace Slice
         // The functions return true if a custom type was defined and false to indicate
         // the default mapping was used.
         //
-        bool
-        getDictionaryTypes(const DictionaryPtr&, const std::string&, const MetadataList&, std::string&, std::string&)
-            const;
-        bool
-        getSequenceTypes(const SequencePtr&, const std::string&, const MetadataList&, std::string&, std::string&) const;
+        static bool
```
Comment (externl) [inline cpp/src/slice2java/JavaUtil.h:236]: I'm fine making these static but they probably don't need to be one `JavaGenerator`.

File: cpp/src/slice2java/JavaUtil.cpp [hunk 4]
```diff
@@ -123,22 +123,18 @@ Slice::computeDefaultSerialVersionUID(const ContainedPtr& p)
...
     {
-        os << (*i)->name() << ":" << (*i)->type();
-        i++;
-        if (i != members.end())
-        {
-            os << ", ";
-        }
+        const MetadataList metadata = member->getMetadata();
+        const string typeString = JavaGenerator::typeToString(member->type(), TypeModeMember, "", metadata);
+        os << member->name() << ":" << typeString << ",";
```
Comment (externl) [inline cpp/src/slice2java/JavaUtil.cpp:136]: This will result in an "extra" comma, which is fine.

**Review by externl — APPROVED** [review]

**Review by bernardnormier — APPROVED** [review]

File: cpp/src/slice2java/JavaUtil.cpp (hunk 4 above)
Comment (InsertCreativityHere) [reply cpp/src/slice2java/JavaUtil.cpp:136]: Yes, I know it's a little lame, but it's just getting fed into a hash function.
So I didn't want to waste time and clock cycles checking if it's the last member.
*shrugs*

File: cpp/src/slice2java/JavaUtil.h (hunk 3 above)
Comment (InsertCreativityHere) [reply cpp/src/slice2java/JavaUtil.h:236]: I agree, but I didn't want to go too crazy in what was otherwise a very small and focused PR.
