### PR TITLE
Python 3.13 build fixes

### LINKED ISSUE #2906: Add support for Python 3.13
The build is currently failing on macOS:

```
Compiling [macosx-shared] modules/IcePy/ValueFactoryManager.cpp
modules/IcePy/Util.cpp:619:12: error: use of undeclared identifier 'PyEval_CallObject'
  619 |     return PyEval_CallObject(type, args.get());
      |            ^
modules/IcePy/Util.cpp:654:16: error: use of undeclared identifier 'PyEval_CallObject'
  654 |         return PyEval_CallObject(type, pArgs.get());
      |                ^
2 errors generated.
make: *** [modules/IcePy/build/macosx/obj/Util.o] Error 1
make: *** Waiting for unfinished jobs....
modules/IcePy/Types.cpp:306:23: error: use of undeclared identifier 'PyEval_CallObject'
  306 |     PyObjectHandle sd{PyEval_CallObject(_slicedDataType, args.get())};
      |                       ^
modules/IcePy/Types.cpp:332:30: error: use of undeclared identifier 'PyEval_CallObject'
  332 |         PyObjectHandle slice{PyEval_CallObject(_sliceInfoType, args.get())};
      |                              ^
modules/IcePy/Types.cpp:1480:21: error: use of undeclared identifier 'PyObject_AsReadBuffer'; did you mean 'PyObject_GetBuffer'?
 1480 |                 if (PyObject_AsReadBuffer(p, &buf, &sz) == 0)
      |                     ^~~~~~~~~~~~~~~~~~~~~
      |                     PyObject_GetBuffer
/Users/joe/.local/share/mise/installs/python/latest/include/python3.13/pybuffer.h:46:17: note: 'PyObject_GetBuffer' declared here
   46 | PyAPI_FUNC(int) PyObject_GetBuffer(PyObject *obj, Py_buffer *view,
      |                 ^
modules/IcePy/Types.cpp:1480:46: error: cannot initialize a parameter of type 'Py_buffer *' with an rvalue of type 'const void **'
 1480 |                 if (PyObject_AsReadBuffer(p, &buf, &sz) == 0)
      |                                              ^~~~
/Users/joe/.local/share/mise/installs/python/latest/include/python3.13/pybuffer.h:46:62: note: passing argument to parameter 'view' here
   46 | PyAPI_FUNC(int) PyObject_GetBuffer(PyObject *obj, Py_buffer *view,
      |                                                              ^
4 errors generated.
make: *** [modules/IcePy/build/macosx/obj/Types.o] Error 1
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #2906

### CODE REVIEW

**Review by bernardnormier — APPROVED** [review]

File: python/modules/IcePy/Types.cpp [hunk 1]
```diff
@@ -296,14 +296,7 @@ IcePy::StreamUtil::setSlicedDataMember(PyObject* obj, const Ice::SlicedDataPtr&
...
 
-    IcePy::PyObjectHandle args{PyTuple_New(0)};
-    if (!args.get())
-    {
-        assert(PyErr_Occurred());
-        throw AbortMarshaling();
-    }
-
-    PyObjectHandle sd{PyEval_CallObject(_slicedDataType, args.get())};
+    PyObjectHandle sd{PyObject_CallObject(_slicedDataType, nullptr)};
```
Comment (pepone) [inline python/modules/IcePy/Types.cpp:299]: No need to create empty tuples with `PyObject_CallObject`

File: python/modules/IcePy/Types.cpp [hunk 2]
```diff
@@ -1476,18 +1469,17 @@ IcePy::SequenceInfo::marshal(
...
+                Py_buffer pybuf;
+                if (pi && PyObject_GetBuffer(p, &pybuf, PyBUF_SIMPLE | PyBUF_FORMAT) == 0)
                 {
-                    if (pi->kind == PrimitiveInfo::KindString)
-                    {
-                        PyErr_Format(PyExc_ValueError, "expected sequence value");
-                        throw AbortMarshaling();
-                    }
+                    // Strings are handled as variable length types above.
+                    assert(pi->kind != PrimitiveInfo::KindString);
```
Comment (pepone) [inline python/modules/IcePy/Types.cpp:1476]: If we enter this branch we are dealing with fixed length element types, it cannot be a string.

File: python/modules/IcePy/Types.cpp [hunk 3]
```diff
@@ -1476,18 +1469,17 @@ IcePy::SequenceInfo::marshal(
...
+                    sz = pybuf.len;
+                    PyBuffer_Release(&pybuf);
```
Comment (pepone) [inline python/modules/IcePy/Types.cpp:1478]: each successful call to ` PyObject_GetBuffer` must be paired with a call to PyBuffer_Release to avoid leaks.
