### PR TITLE
Fix CollocatedRequestHandler to decrement the direct count on exception

### LINKED ISSUE #3112: DataStorm/api failure on Windows Debug/x64
https://github.com/zeroc-ice/ice/actions/runs/11746757701/job/32727218808

The test hangs. It is a client only test. There is an exception in the client log.

```
-- 11/08/24 18:06:01331 D:/a/ice/ice/cpp/test/DataStorm/api/msbuild/writer/x64/Debug/writer.exe: Data: e1:[k2:key]@3:topic: destroyed key writer
-- 11/08/24 18:06:01332 D:/a/ice/ice/cpp/test/DataStorm/api/msbuild/writer/x64/Debug/writer.exe: Topic: topic: destroyed topic writer
-- 11/08/24 18:06:01704 D:/a/ice/ice/cpp/test/DataStorm/api/msbuild/writer/x64/Debug/writer.exe: Session: s/1: destroyed session
   :the Ice communicator object is destroyed
     0 Ice::Exception::Exception at D:\a\ice\ice\cpp\src\Ice\Exception.cpp:514
     1 Ice::LocalException::LocalException at D:\a\ice\ice\cpp\include\Ice\LocalException.h:25
     2 Ice::CommunicatorDestroyedException::CommunicatorDestroyedException at D:\a\ice\ice\cpp\include\Ice\LocalExceptions.h:613
     3 IceInternal::Instance::serverThreadPool at D:\a\ice\ice\cpp\src\Ice\Instance.cpp:409
     4 Ice::ObjectAdapterI::getThreadPool at D:\a\ice\ice\cpp\src\Ice\ObjectAdapterI.cpp:781
     5 IceInternal::CollocatedRequestHandler::invokeAsyncRequest at D:\a\ice\ice\cpp\src\Ice\CollocatedRequestHandler.cpp:167
     6 IceInternal::OutgoingAsync::invokeCollocated at D:\a\ice\ice\cpp\src\Ice\OutgoingAsync.cpp:1038
     7 IceInternal::CollocatedRequestHandler::sendAsyncRequest at D:\a\ice\ice\cpp\src\Ice\CollocatedRequestHandler.cpp:52
     8 IceInternal::ProxyOutgoingAsyncBase::invokeImpl at D:\a\ice\ice\cpp\src\Ice\OutgoingAsync.cpp:448
     9 IceInternal::OutgoingAsync::invoke at D:\a\ice\ice\cpp\src\Ice\OutgoingAsync.cpp:1072
    10 IceInternal::OutgoingAsync::invoke at D:\a\ice\ice\cpp\src\Ice\OutgoingAsync.cpp:1096
    11 IceInternal::OutgoingAsyncT<void>::invoke at D:\a\ice\ice\cpp\include\Ice\OutgoingAsync.h:350
    12 DataStormContract::NodePrx::_iceI_createSession at D:\a\ice\ice\cpp\src\DataStorm\msbuild\datastorm\x64\Debug\Contract.cpp:489
    13 IceInternal::makeLambdaOutgoing<void,std::function<void __cdecl(void)>,std::function<void __cdecl(std::exception_ptr)>,std::function<void __cdecl(bool)>,DataStormContract::NodePrx const *,void (__cdecl DataStormContract::NodePrx::*)(std::shared_ptr<IceInternal::OutgoingAsyncT<void> > const &,std::optional<DataStormContract::NodePrx> const &,std::optional<DataStormContract::SubscriberSessionPrx> const &,bool,std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::less<void>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > > const &)const ,std::optional<DataStormContract::NodePrx> const &,std::optional<DataStormContract::SubscriberSessionPrx> const &,bool &,std::map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::less<void>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > > const &> at D:\a\ice\ice\cpp\include\Ice\OutgoingAsync.h:499
    14 DataStormContract::NodePrx::createSessionAsync at D:\a\ice\ice\cpp\src\DataStorm\msbuild\datastorm\x64\Debug\Contract.cpp:481
    15 `DataStormI::NodeI::createPublisherSession'::`3'::<lambda_1>::operator()<std::shared_ptr<Ice::Connection> > at D:\a\ice\ice\cpp\src\DataStorm\NodeI.cpp:330
    16 std::invoke<`DataStormI::NodeI::createPublisherSession'::`3'::<lambda_1> &,std::shared_ptr<Ice::Connection> > at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\type_traits:1714
    17 std::_Func_impl_no_alloc<`DataStormI::NodeI::createPublisherSession'::`3'::<lambda_1>,void,std::shared_ptr<Ice::Connection> >::_Do_call at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\functional:874
    18 std::_Func_class<void,std::shared_ptr<Ice::Connection> >::operator() at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\functional:920
    19 `IceInternal::ProxyGetConnectionLambda::ProxyGetConnectionLambda'::`2'::<lambda_1>::operator() at D:\a\ice\ice\cpp\src\Ice\ProxyAsync.cpp:78
    20 std::invoke<`IceInternal::ProxyGetConnectionLambda::ProxyGetConnectionLambda'::`2'::<lambda_1> &,bool> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\type_traits:1714
    21 std::_Func_impl_no_alloc<`IceInternal::ProxyGetConnectionLambda::ProxyGetConnectionLambda'::`2'::<lambda_1>,void,bool>::_Do_call at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\functional:874
    22 std::_Func_class<void,bool>::operator() at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\functional:920
    23 IceInternal::LambdaInvoke::handleInvokeResponse at D:\a\ice\ice\cpp\src\Ice\OutgoingAsync.cpp:1156
    24 IceInternal::OutgoingAsyncBase::invokeResponse at D:\a\ice\ice\cpp\src\Ice\OutgoingAsync.cpp:139
    25 `IceInternal::OutgoingAsyncBase::invokeResponseAsync'::`2'::<lambda_1>::operator() at D:\a\ice\ice\cpp\src\Ice\OutgoingAsync.cpp:91
    26 std::invoke<`IceInternal::OutgoingAsyncBase::invokeResponseAsync'::`2'::<lambda_1> &> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\type_traits:1704
    27 std::_Func_impl_no_alloc<`IceInternal::OutgoingAsyncBase::invokeResponseAsync'::`2'::<lambda_1>,void>::_Do_call at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\functional:874
    28 std::_Func_class<void>::operator() at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\functional:920
    29 IceInternal::ThreadPool::executeFromThisThread at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:450
    30 `IceInternal::ThreadPool::execute'::`2'::<lambda_1>::operator() at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:467
    31 std::invoke<`IceInternal::ThreadPool::execute'::`2'::<lambda_1> &,IceInternal::ThreadPoolCurrent &> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\type_traits:1714
    32 std::_Func_impl_no_alloc<`IceInternal::ThreadPool::execute'::`2'::<lambda_1>,void,IceInternal::ThreadPoolCurrent &>::_Do_call at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\functional:874
    33 std::_Func_class<void,IceInternal::ThreadPoolCurrent &>::operator() at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\functional:920
    34 IceInternal::ThreadPoolWorkQueue::message at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:114
    35 IceInternal::ThreadPool::run at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:723
    36 IceInternal::ThreadPool::EventHandlerThread::run at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:1080
    37 std::invoke<void (__cdecl IceInternal::ThreadPool::EventHandlerThread::*)(void),IceInternal::ThreadPool::EventHandlerThread *> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\type_traits:1720
    38 std::thread::_Invoke<std::tuple<void (__cdecl IceInternal::ThreadPool::EventHandlerThread::*)(void),IceInternal::ThreadPool::EventHandlerThread *>,0,1> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\thread:61
    39 00007ffa94413010
    40 00007ffabcb24cb0
    41 00007ffabe61ecdb
```

### PR DESCRIPTION
**Pull request by bernardnormier**
CollocatedRequestHandler::invokeAsyncRequest did not always decrement the "direct count" on exception, which could result in a hang at shudown.

Fixes #3112.

### CODE REVIEW

File: cpp/src/Ice/CollocatedRequestHandler.cpp [hunk 1]
```diff
@@ -100,102 +100,105 @@ CollocatedRequestHandler::invokeAsyncRequest(OutgoingAsyncBase* outAsync, int ba
     int requestId = 0;
     try
     {
-        lock_guard<mutex> lock(_mutex);
+        {
```
Comment (bernardnormier) [inline cpp/src/Ice/CollocatedRequestHandler.cpp:103]: The only change to this code was to enlarge the try-catch block.

**Review by pepone — APPROVED** [review]

**Review by externl — APPROVED** [review]
