### PR TITLE
Fix RSTRING_PTR usage in Ruby

### LINKED ISSUE #2342: Incorrect RSTRING_PTR usage in Ruby mapping
Is this usage of RSTRING_PTR correct? RSTRING_PTR returns a pointer to the Ruby-allocated memory for the string, and the previous usage is indeed suspicious because the documentation states that the returned string is not guaranteed to be null-terminated.

The correct usage would be:
```
string(RSTRING_PTR(path), RSTRING_LEN(path))
```

_Originally posted by @pepone in https://github.com/zeroc-ice/ice/pull/2340#discussion_r1652302932_

### PR DESCRIPTION
**Pull request by pepone**
Fix #2342

### CODE REVIEW

File: ruby/src/IceRuby/Config.h [hunk 1]
```diff
@@ -79,39 +79,4 @@ extern "C"
 
 #define CAST_METHOD(X) reinterpret_cast<ICE_RUBY_ENTRY_POINT>(X)
 
-//
```
Comment (pepone) [inline ruby/src/IceRuby/Config.h:82]: We can drop support for these ancient Ruby versions and remove the compatibility macros.

File: ruby/src/IceRuby/Util.cpp [hunk 2]
```diff
@@ -208,7 +208,7 @@ IceRuby::RubyException::operator<<(ostream& ostr) const
 {
     volatile VALUE cls = rb_class_path(CLASS_OF(ex));
     volatile VALUE msg = rb_obj_as_string(ex);
-    ostr << RSTRING_PTR(cls) << ": " << RSTRING_PTR(msg);
+    ostr << string(RSTRING_PTR(cls), RSTRING_LEN(cls)) << ": " << string(RSTRING_PTR(msg), RSTRING_LEN(msg));
```
Comment (bernardnormier) [inline ruby/src/IceRuby/Util.cpp:211]: It would be cleaner to use string_view here and `{}` for the ctor:
```
ostr << string_view{s, count} << ....
```

File: ruby/src/IceRuby/Operation.cpp [hunk 3]
```diff
@@ -574,7 +574,7 @@ IceRuby::OperationI::unmarshalException(const vector<byte>& bytes, const Ice::Co
             volatile VALUE cls = CLASS_OF(ex);
             volatile VALUE path = callRuby(rb_class_path, cls);
             assert(TYPE(path) == T_STRING);
-            throw Ice::UnknownUserException{__FILE__, __LINE__, RSTRING_PTR(path)};
+            throw Ice::UnknownUserException{__FILE__, __LINE__, string(RSTRING_PTR(path), RSTRING_LEN(path))};
```
Comment (bernardnormier) [inline ruby/src/IceRuby/Operation.cpp:577]: string is fine here. I would use `{}`.

**Review by bernardnormier — APPROVED** [review]
