### PR TITLE
VC++ warning fixes

### LINKED ISSUE #4676: VC++ warnings in generated C++ generated code
Building any generated code with Visual Studio 2026 got this warnings:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Warning	C4251	'IceInternal::OutgoingAsyncBase::_cancellationHandler': 'std::shared_ptr<IceInternal::CancellationHandler>' needs to have dll-interface to be used by clients of 'IceInternal::OutgoingAsyncBase'	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	131		
Warning	C4251	'std::enable_shared_from_this<IceInternal::OutgoingAsyncBase>::_Wptr': 'std::weak_ptr<_Ty>' needs to have dll-interface to be used by clients of 'std::enable_shared_from_this<IceInternal::OutgoingAsyncBase>'
        with
        [
            _Ty=IceInternal::OutgoingAsyncBase
        ]	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	69		
Warning	C4251	'IceInternal::ProxyOutgoingAsyncBase::_handler': 'std::shared_ptr<IceInternal::RequestHandler>' needs to have dll-interface to be used by clients of 'IceInternal::ProxyOutgoingAsyncBase'	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	174		
Warning	C4251	'IceInternal::OutgoingAsync::_userException': 'std::function<void (const Ice::UserException &)>' needs to have dll-interface to be used by clients of 'IceInternal::OutgoingAsync'	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	234		
Warning	C4251	'IceInternal::LambdaInvoke::_exception': 'std::function<void (std::exception_ptr)>' needs to have dll-interface to be used by clients of 'IceInternal::LambdaInvoke'	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	258		
Warning	C4251	'IceInternal::LambdaInvoke::_sent': 'std::function<void (bool)>' needs to have dll-interface to be used by clients of 'IceInternal::LambdaInvoke'	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	259		
Warning	C4251	'IceInternal::LambdaInvoke::_response': 'std::function<void (bool)>' needs to have dll-interface to be used by clients of 'IceInternal::LambdaInvoke'	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	260		
Warning	C4250	'IceInternal::LambdaOutgoing<void>': inherits 'IceInternal::LambdaInvoke::IceInternal::LambdaInvoke::handleSent' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	388		
Warning	C4250	'IceInternal::LambdaOutgoing<void>': inherits 'IceInternal::LambdaInvoke::IceInternal::LambdaInvoke::handleException' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	388		
Warning	C4250	'IceInternal::LambdaOutgoing<void>': inherits 'IceInternal::LambdaInvoke::IceInternal::LambdaInvoke::handleResponse' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	388		
Warning	C4250	'IceInternal::LambdaOutgoing<void>': inherits 'IceInternal::LambdaInvoke::IceInternal::LambdaInvoke::handleInvokeSent' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	388		
Warning	C4250	'IceInternal::LambdaOutgoing<void>': inherits 'IceInternal::LambdaInvoke::IceInternal::LambdaInvoke::handleInvokeException' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	388		
Warning	C4250	'IceInternal::LambdaOutgoing<void>': inherits 'IceInternal::LambdaInvoke::IceInternal::LambdaInvoke::handleInvokeResponse' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	388		
Warning	C4250	'IceInternal::PromiseOutgoing<void>': inherits 'IceInternal::PromiseInvoke<void>::IceInternal::PromiseInvoke<void>::handleException' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	447		
Warning	C4250	'IceInternal::PromiseOutgoing<void>': inherits 'IceInternal::PromiseInvoke<void>::IceInternal::PromiseInvoke<void>::handleResponse' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	447		
Warning	C4250	'IceInternal::PromiseOutgoing<void>': inherits 'IceInternal::PromiseInvoke<void>::IceInternal::PromiseInvoke<void>::handleInvokeSent' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	447		
Warning	C4250	'IceInternal::PromiseOutgoing<void>': inherits 'IceInternal::PromiseInvoke<void>::IceInternal::PromiseInvoke<void>::handleInvokeException' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	447		
Warning	C4250	'IceInternal::PromiseOutgoing<void>': inherits 'IceInternal::PromiseInvoke<void>::IceInternal::PromiseInvoke<void>::handleInvokeResponse' via dominance	Project1	C:\Users\jose\source\repos\Project1\packages\ZeroC.Ice.Cpp.3.8.0-nightly.20251203.1\build\native\include\Ice\OutgoingAsync.h	447		
```

We disable this warnings in the generated headers by including `PushDisableWarnings.h` and `PopDisableWarnings.h` but this doesn't work for the few headers that we include directly in the generated cpp files.

For example:

```
// <auto-generated>Generated from Slice file 'Foo.ice'.</auto-generated>

#define ICE_BUILDING_GENERATED_CODE

#include "Foo.h"
#include <Ice/AsyncResponseHandler.h>
#include <Ice/DefaultSliceLoader.h>
#include <Ice/OutgoingAsync.h>
#include <algorithm>
#include <array>
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #4676

### CODE REVIEW

File: cpp/include/Ice/OutgoingAsync.h [hunk 1]
```diff
@@ -305,7 +309,7 @@ namespace IceInternal
         {
             _read = [](Ice::InputStream* stream)
             {
-                T v;
+                T v{};
```
Comment (pepone) [inline cpp/include/Ice/OutgoingAsync.h:312]: VC++ linter flags this as uninitialized

File: cpp/include/Ice/DefaultSliceLoader.h [hunk 2]
```diff
@@ -11,6 +11,12 @@
 #include <string>
 #include <type_traits>
 
+#if defined(_MSC_VER)
+#    pragma warning(push)
+#    pragma warning(disable : 4250) // ... : inherits ... via dominance
```
Comment (bernardnormier) [inline cpp/include/Ice/DefaultSliceLoader.h]: What is the dominance in this file?

File: cpp/include/Ice/ObserverHelper.h [hunk 3]
```diff
@@ -8,6 +8,12 @@
 
 #include <string_view>
 
+#if defined(_MSC_VER)
+#    pragma warning(push)
+#    pragma warning(disable : 4250) // ... : inherits ... via dominance
```
Comment (bernardnormier) [inline cpp/include/Ice/ObserverHelper.h]: Is this necessary?

**Review by bernardnormier — APPROVED** [review]

File: cpp/include/Ice/DefaultSliceLoader.h (hunk 2 above)
Comment (pepone) [reply cpp/include/Ice/DefaultSliceLoader.h]: not required here.

File: cpp/include/Ice/ObserverHelper.h (hunk 3 above)
Comment (pepone) [reply cpp/include/Ice/ObserverHelper.h]: not required.
