### PR TITLE
Use a standard c++ attribute for visibility with clang and gcc

### LINKED ISSUE #3788: Debian 12/ RedHat 9 build failure
```
x86_64-linux-gnu-g++ -g -O2 -ffile-prefix-map=/workspace/build=. -fstack-protector-strong -Wformat -Werror=format-security -MT src/IceGridLib/build/x86_64-linux-gnu/obj/pic/Admin.o -MMD -MP -MF  src/IceGridLib/build/x86_64-linux-gnu/obj/pic/Admin.Td -fvisibility=hidden -Wall -Wextra -Wredundant-decls -Wshadow -Wdeprecated -Werror -pthread -DNDEBUG -std=c++17 -Isrc/IceGridLib/generated -Iinclude -Iinclude/generated -DICEGRID_API_EXPORTS -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -c src/IceGridLib/generated/Admin.cpp -o src/IceGridLib/build/x86_64-linux-gnu/obj/pic/Admin.o
In file included from include/generated/IceGrid/Admin.h:12,
                 from src/IceGridLib/generated/Admin.cpp:11:
include/generated/IceGrid/Descriptor.h:1165:23: error: expected identifier before ‘[’ token
 1165 |     class ICEGRID_API [[deprecated]] BoxedDistributionDescriptor : public Ice::Value
      |                       ^
include/generated/IceGrid/Descriptor.h:1165:66: error: expected initializer before ‘:’ token
 1165 |     class ICEGRID_API [[deprecated]] BoxedDistributionDescriptor : public Ice::Value
      |  
```

See the attached build logs from the Nightly workflow

[debian12-build.txt](https://github.com/user-attachments/files/19485250/debian12-build.txt)
[rhel9-build.txt](https://github.com/user-attachments/files/19485296/rhel9-build.txt)

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #3788.

### CODE REVIEW

File: cpp/include/Ice/Communicator.h [hunk 1]
```diff
@@ -323,12 +323,12 @@ namespace Ice
         [[nodiscard]] IceInternal::ReferencePtr _propertyToProxy(std::string_view property) const;
 
         /// @cond INTERNAL
-        friend ICE_API CommunicatorPtr initialize(int&, const char*[], InitializationData);
-        friend ICE_API CommunicatorPtr initialize(InitializationData);
+        friend ICE_API_FRIEND CommunicatorPtr initialize(int&, const char*[], InitializationData);
```
Comment (bernardnormier) [inline cpp/include/Ice/Communicator.h:326]: Required on Windows, but doesn't work with the standard attribute placement (as the end).

File: cpp/include/Ice/StringConverter.h [hunk 2]
```diff
@@ -48,12 +48,10 @@ namespace Ice
     };
 
 #if defined(__clang__)
-    //
     // Explicit template instantiation so that dynamic_cast of derived exported
     // classes works well with clang, see ICE-7473.
-    //
-    template class ICE_API BasicStringConverter<char>;
-    template class ICE_API BasicStringConverter<wchar_t>;
+    template class __attribute__((visibility("default"))) BasicStringConverter<char>;
```
Comment (bernardnormier) [inline cpp/include/Ice/StringConverter.h:53]: I could not find a way to use the standard c++ attribute here.

File: cpp/include/Ice/FactoryTable.h [hunk 3]
```diff
@@ -51,7 +51,7 @@ namespace IceInternal
         TypeIdTable _typeIdTable;
     };
 
-    extern ICE_API FactoryTable* factoryTable;
+    ICE_API extern FactoryTable* factoryTable;
```
Comment (bernardnormier) [inline cpp/include/Ice/FactoryTable.h:54]: Fortunately this works on Windows too.

**Review by pepone — APPROVED** [review]

**Review by externl — APPROVED** [review]

**Comment by pepone** [comment]
I tested rhel9 C++/Ruby builds. It is working fine.
