### PR TITLE
Fixes for ice2slice generated links

### LINKED ISSUE #3993: ice2slice for Locator.ice
Running ice2slice on Locator.ice and comparing it with IceRPC's Locator.slice shows a number of issues in ice2slice:

- it should map Ice::Identity to Ice::IdentityPath
- `::IceRpc::ServiceAddress` should be `IceRpc::ServiceAddress`
- all the generated `@link` are broken
- `{}` should be spelled on a single line

### PR DESCRIPTION
**Pull request by pepone**
Fix #3993

### CODE REVIEW

File: cpp/src/ice2slice/Gen.cpp [hunk 1]
```diff
@@ -219,20 +228,18 @@ namespace
     {
         // The only difference with '@link' between the 'Ice' and 'Slice' syntaxes
         // is that the 'Ice' syntax uses '#' whereas the 'Slice' syntax uses '::'.
-        string formattedLink;
-        auto separatorPos = rawLink.find('#');
+        string formattedLink = rawLink;
+        auto separatorPos = formattedLink.find('#');
```
Comment (pepone) [inline cpp/src/ice2slice/Gen.cpp:232]: We were generating `{@link }` when `separatorPos == string::npos`

File: cpp/src/ice2slice/Gen.cpp [hunk 2]
```diff
@@ -305,7 +312,11 @@ namespace
         {
             string memberComponent = "";
             string::size_type hashPos = ident.find('#');
-            if (hashPos != string::npos)
+            if (hashPos == 0)
+            {
+                ident = ident.substr(1);
```
Comment (pepone) [inline cpp/src/ice2slice/Gen.cpp:317]: We were generating `@see ::foo` instead of `@see foo`

File: cpp/src/ice2slice/Gen.cpp [hunk 3]
```diff
@@ -724,6 +735,13 @@ Gen::TypesVisitor::getOutput(const ContainedPtr& contained)
     {
         string outputName = getOutputName(_fileBase, _modules.size() > 1 ? scope : "");
         unique_ptr<Output> out = make_unique<Output>(outputName.c_str());
+        if (!(*out))
+        {
+            ostringstream os;
+            os << "cannot open '" << outputName << "': " << IceInternal::errorToString(errno);
+            throw FileException(os.str());
```
Comment (pepone) [inline cpp/src/ice2slice/Gen.cpp:742]: The compiler didn't report any failures if it failed to create the files.

**Review by InsertCreativityHere — APPROVED** [review]
Looks good to me!
(Except for the build error for including `StringUtil` of course)

**Review by bernardnormier — APPROVED** [review]
