### PR TITLE
Delete copy and move operations on ScopedCertificate wrappers

### LINKED ISSUE #5099: SSL: Code quality cleanups (typos, unused includes, minor fixes)
## Summary

Security review of `cpp/src/Ice/SSL/` identified several low-severity code quality issues. These are safe, low-risk cleanups.

### `AltNAmeIP` should be `AltNameIP`
**File:** `SSLUtil.h:37`

```cpp
const int AltNAmeIP = 7;
```

Inconsistent with `AltNameDNS`, `AltNameEmail`, `AltNameDirectory`, `AltNameURL`. Also referenced in `SSLUtil.cpp:348` and `SchannelEngine.cpp:671`.

### `"unknow"` should be `"unknown"`
**File:** `SchannelEngine.cpp:972`

```cpp
os << "SSL transport: error unknow key algorithm: '" << keyInfo->Algorithm.pszObjId << "'";
```

### OpenSSL: Unused `#include <iostream>`
**File:** `OpenSSLTransceiverI.cpp:23`

### Schannel: Unused `#include <iostream>`
**File:** `SchannelEngine.cpp:17`

### SecureTransport: Missing `[[fallthrough]]` in `escapeX509Name`
**File:** `SecureTransportUtil.cpp:70-95`

Switch cases for special characters intentionally fall through to `default`. Without `[[fallthrough]]`, a future maintainer could "fix" the apparent bug by adding a `break`, which would break DN escaping used by TrustManager.

### Shared: `ScopedCertificate` classes lack deleted copy constructors
**File:** `SSLUtil.h:56-99`

All three backend-specific `ScopedCertificate` RAII wrappers allow copying, which would result in double-free of the underlying certificate resource.

**Fix:** Add `= delete` for copy constructor and copy assignment operator.

### Shared: `const_cast` to set const members in `SSLEngine::initialize()`
**File:** `SSLEngine.cpp:62-64`

```cpp
const_cast<bool&>(_revocationCheckCacheOnly) = ...;
const_cast<int&>(_revocationCheck) = ...;
```

Technically undefined behavior. Either remove `const` from these members or initialize them in the constructor.

### Shared: `parseBytes()` silently drops trailing nibble on odd-length hex
**File:** `SSLUtil.cpp:46-77`

An odd-length hex string silently loses its last character. Used for certificate fingerprint parsing.

**Fix:** Return `false` if the cleaned hex string has an odd length.

### SecureTransport: Naive `.pem` extension check
**File:** `SecureTransportUtil.cpp:576`

```cpp
if (file.find(".pem") != string::npos)
```

Matches `file.pem.bak`, `my.pemthing`, etc. Should check that the filename ends with `.pem`.

### Schannel: `CryptReleaseContext` never called for acquired `cryptProv`
**File:** `SchannelEngine.cpp:1015-1034`

After acquiring the cryptographic context and importing the key, the `cryptProv` handle is never released. Resource leak.

### Schannel: `ISC_RET_EXTENDED_ERROR` used in request flags
**File:** `SchannelTransceiverI.cpp:119`

`ISC_RET_EXTENDED_ERROR` (a return flag) is used where `ISC_REQ_EXTENDED_ERROR` (a request flag) is expected. Same numeric value, but semantically incorrect.

### PR DESCRIPTION
**Pull request by pepone**
## Summary
- Delete copy constructor, copy assignment, move constructor, and move assignment on all three `ScopedCertificate` RAII wrappers to prevent potential double-free

Fixes #5099

## Test plan
- [ ] Build on all platforms
- [ ] Run SSL tests to verify no behavioral changes

### CODE REVIEW

File: cpp/src/Ice/SSL/SSLEngine.cpp [hunk 1]
```diff
@@ -59,9 +59,8 @@ Ice::SSL::SSLEngine::initialize()
     _securityTraceLevel = properties->getIcePropertyAsInt("IceSSL.Trace.Security");
     _securityTraceCategory = "Security";
 
-    const_cast<bool&>(_revocationCheckCacheOnly) =
```
Comment (externl) [inline cpp/src/Ice/SSL/SSLEngine.cpp:62]: This is a pattern that we use all over the place. I get that it's not a great practice, but the const data member is what we want.

Comment (pepone) [reply cpp/src/Ice/SSL/SSLEngine.cpp:62]: Reverted this part.
