### PR TITLE
Fix Instabilities and Unnecessary Sorting in the Generated Code

### LINKED ISSUE #3313: User-Defined Operations are Not Generated in a Stable Ordering with `slice2cs`
`slice2cs` normally generates user-defined functions in the order that you pass them, but sometimes the order of these operations will change. Interestingly, the order of certain operations remains unchanged, but the order of groups of operations will swap around.
See this for an example:
https://github.com/InsertCreativityHere/compiler-comparison/commit/367c05c1b8f1e4a22a1e46fdf5c7b18fa56b8cc9#diff-7c8e3101e439f1f9a8ef3843193f28c141dcea274095e762b972b856a5151928

... actually, as I'm writing this out, I'm pretty sure I figured it out. I think what's happening is when you have interface inheritance,
and we iterate through the parent interfaces, the order we do that in isn't stable... that seems like a sensible explanation at least.

### PR DESCRIPTION
**Pull request by InsertCreativityHere**
This PR fixes #3313 and #3205.

All of the instabilities were caused by places where we were calling `sort` on `list`s of `shared_ptr`s, which meant we were sorting things by unstable memory addresses.
Thankfully, all of the sorting we were trying to do in those places was unnecessary and removed.

The two types of sorting which is removed by this PR:
- We used to sort the exception specifications of operation, so it'd be safe to call `unique` to remove duplicates.
  But this is useless. The Slice compiler already disallows the same exception to appear twice in an exception specification.
- We used to sort out operations by name, so it'd be safe to call `unique` to remove duplicates.
  But again, the Slice compiler issues errors if there's any conflicts, even from inherited names (including diamonds).

One exception:
We still sort our operations by name in C++ because we use a binary search over operation names to perform dispatch.
So we require the names to be alphabetized. We re-use the same list for generating the actual operations and the dispatch, and I just left it alone. It's fine.

### CODE REVIEW

File: cpp/src/Slice/Parser.cpp [hunk 1]
```diff
@@ -3053,7 +3053,6 @@ Slice::InterfaceDef::allBases() const
 {
     InterfaceList result = _bases;
     result.sort(containedCompare);
-    result.unique(containedEqual);
```
Comment (InsertCreativityHere) [inline cpp/src/Slice/Parser.cpp:3056]: It is illegal to list the same interface multiple times in an inheritance list, so there's no point to calling `unique` on `_bases` here.

File: cpp/src/Slice/Parser.cpp [hunk 2]
```diff
@@ -3584,7 +3583,6 @@ Slice::Exception::createDataMember(
     checkIdentifier(name); // Don't return here -- we create the data member anyway.
 
     // Check whether any bases have defined a member with the same name already.
-    ExceptionList bl = allBases();
```
Comment (InsertCreativityHere) [inline cpp/src/Slice/Parser.cpp:3587]: Dead variable.

File: cpp/src/ice2slice/Gen.cpp [hunk 3]
```diff
@@ -561,8 +561,6 @@ Gen::TypesVisitor::visitInterfaceDefStart(const InterfaceDefPtr& p)
         }
 
         ExceptionList throws = op->throws();
-        throws.sort();
-        throws.unique();
```
Comment (InsertCreativityHere) [inline cpp/src/ice2slice/Gen.cpp:565]: We no longer sort our exception specifications, because there's no point to calling `unique`.
The Slice compiler already ensures this for us.

File: cpp/src/slice2cpp/Gen.cpp [hunk 4]
```diff
@@ -216,15 +216,10 @@ namespace
...
-            throws.sort();
-            throws.unique();
-
-            //
             // Arrange exceptions into most-derived to least-derived order. If we don't
             // do this, a base exception handler can appear before a derived exception
             // handler, causing compiler warnings and resulting in the base exception
             // being marshaled instead of the derived exception.
-            //
             throws.sort(Slice::DerivedToBaseCompare());
```
Comment (InsertCreativityHere) [inline cpp/src/slice2cpp/Gen.cpp:223]: Note that in the languages, we _do_ still sort them by derived-to-base.
This sorting is stable (it won't re-arrange elements that are 'equal'). And this is necessary to prevent dead catch blocks.

We do this in all compilers except 'ice2slice' (where it's correct not to) and 'slice2php', 'slice2py', and 'slice2rb'.
It is suspicious that we aren't sorting exceptions in those languages.

File: cpp/src/slice2cs/Gen.cpp [hunk 5]
```diff
@@ -317,25 +317,20 @@ Slice::CsVisitor::writeUnmarshalDataMember(
...
-        allOps.sort();
-        allOps.unique();
-        for (OperationList::const_iterator i = allOps.begin(); i != allOps.end(); ++i)
-        {
-            string retS;
-            vector<string> params, args;
-            string ns = getNamespace(p);
-            string name = getDispatchParams(*i, retS, params, args, ns);
-            _out << sp << nl << "public abstract " << retS << " " << name << spar << params << epar << ';';
-        }
```
Comment (InsertCreativityHere) [inline cpp/src/slice2cs/Gen.cpp:338]: Simplified this whole block.
But the main change was removing the sorting of `OperationPtr` that it used to be doing.

File: cpp/src/slice2cs/Gen.cpp [hunk 6]
```diff
@@ -2698,18 +2693,6 @@ Slice::Gen::HelperVisitor::visitInterfaceDefStart(const InterfaceDefPtr& p)
...
-        throws.unique();
-
-        //
-        // Arrange exceptions into most-derived to least-derived order. If we don't
-        // do this, a base exception handler can appear before a derived exception
-        // handler, causing compiler warnings and resulting in the base exception
-        // being marshaled instead of the derived exception.
-        //
-        throws.sort(Slice::DerivedToBaseCompare());
-
```
Comment (InsertCreativityHere) [inline cpp/src/slice2cs/Gen.cpp:2712]: Dead code.

File: cpp/src/slice2java/Gen.cpp [hunk 7]
```diff
@@ -3956,8 +3954,6 @@ Slice::Gen::ProxyVisitor::ProxyVisitor(const string& dir) : JavaVisitor(dir) {}
 bool
 Slice::Gen::ProxyVisitor::visitInterfaceDefStart(const InterfaceDefPtr& p)
 {
-    const OperationList ops = p->allOperations();
```
Comment (InsertCreativityHere) [inline cpp/src/slice2java/Gen.cpp:3959]: Another dead variable...

File: cpp/src/slice2js/Gen.cpp [hunk 8]
```diff
@@ -2035,7 +2036,6 @@ Slice::Gen::TypeScriptImportVisitor::visitInterfaceDefStart(const InterfaceDefPt
     }
 
     // Add imports required for operation parameters and return types.
-    const OperationList operationList = p->allOperations();
```
Comment (InsertCreativityHere) [inline cpp/src/slice2js/Gen.cpp:2038]: Dead.

File: cpp/src/slice2matlab/Main.cpp [hunk 9]
```diff
@@ -1713,7 +1713,6 @@ CodeVisitor::visitInterfaceDefStart(const InterfaceDefPtr& p)
     const string scoped = p->scoped();
     const string abs = getAbsolute(p);
     InterfaceList bases = p->bases();
-    const OperationList allOps = p->allOperations();
```
Comment (InsertCreativityHere) [inline cpp/src/slice2matlab/Main.cpp:1716]: Dead.

File: cpp/src/slice2cs/Gen.cpp [hunk 10]
```diff
@@ -317,26 +317,31 @@ Slice::CsVisitor::writeUnmarshalDataMember(
 void
 Slice::CsVisitor::writeInheritedOperations(const InterfaceDefPtr& p)
 {
```
Comment (bernardnormier) [inline cpp/src/slice2cs/Gen.cpp:319]: I think it would be cleaner to eliminate this helper function (called once) and just call allOperations on the interface in the calling function.

**Review by bernardnormier — APPROVED** [review]
I woud also remove:
> allOpNames.unique();

from line 2564 in slice2cpp/Gen.cpp.

**Comment by InsertCreativityHere** [comment]
Originally I left that `unique` in because I was planning to check out the code around it, because I smelled a bug.
But I went ahead and removed this `unique` in this PR and just opened an issue for my suspicion:
#3318

File: cpp/src/slice2cs/Gen.cpp (hunk 10 above)
Comment (InsertCreativityHere) [reply cpp/src/slice2cs/Gen.cpp]: I didn't want to make it too hard to review the changes, but you're right.
I 'inlined' this code, and actually managed to simplify a good chunk of the code around where we called this too.

File: cpp/src/slice2cpp/Gen.cpp [hunk 11]
```diff
@@ -2657,7 +2651,6 @@ Slice::Gen::InterfaceVisitor::visitInterfaceDefEnd(const InterfaceDefPtr& p)
         allOpNames.push_back("ice_isA");
         allOpNames.push_back("ice_ping");
         allOpNames.sort();
-        allOpNames.unique();
```
Comment (InsertCreativityHere) [inline cpp/src/slice2cpp/Gen.cpp:2660]: The Slice compiler ensures that there are no duplicate operation names, even among inherited operations.

File: cpp/src/slice2cs/Gen.cpp (hunk 5 above)
Comment (InsertCreativityHere) [reply cpp/src/slice2cs/Gen.cpp:338]: After a review comment from Bernard, I just inlined the simplified version of this function.

File: cpp/src/slice2cs/Gen.cpp [hunk 12]
```diff
@@ -3224,16 +3178,30 @@ Slice::Gen::DispatcherVisitor::visitInterfaceDefStart(const InterfaceDefPtr& p)
...
+            if (find_if(
+                    allOps.begin(),
+                    allOps.end(),
+                    [name = baseOp->name()](const auto& other) { return other->name() == name; }) == allOps.end())
+            {
+                allOps.push_back(baseOp);
+            }
+        }
+    }
+    for (const auto& op : allOps)
```
Comment (InsertCreativityHere) [inline cpp/src/slice2cs/Gen.cpp:3197]: Where `writeInheritedOperations` was inlined to.

File: cpp/src/slice2cs/Gen.cpp [hunk 13]
```diff
@@ -3223,17 +3177,14 @@ Slice::Gen::DispatcherVisitor::visitInterfaceDefStart(const InterfaceDefPtr& p)
     _out << fixId(name);
 
     _out << sb;
-
-    for (const auto& op : p->operations())
+    for (const auto& op : p->allOperations())
```
Comment (InsertCreativityHere) [inline cpp/src/slice2cs/Gen.cpp:3180]: Now we just call `allOperations` instead of `operations` followed by `writeInheritedOperations`.

A side effect of this is that now, the order that we generate operations in is reversed. It used to be Derived -> Base, but now it's Derived -> Base.

**Review by pepone — APPROVED** [review]
