### PR TITLE
Disable locale testing on iOS

### LINKED ISSUE #4011: C++ iOS simulator collate_byname failure
```
testing proxy to string is not affected by locale settings... unexpected exception while running `Ice/proxy client':
collate_byname<char>::collate_byname failed to construct for en_US.UTF-8
Traceback (most recent call last):
  File "/Users/jose/Documents/3.8/ice/cpp/../scripts/Util.py", line 1324, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jose/Documents/3.8/ice/cpp/../scripts/Util.py", line 2444, in waitSuccess
    raise RuntimeError(
    ...<2 lines>...
    )
RuntimeError: unexpected exit status: expected: 0, got 1
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #4011

### CODE REVIEW

**Review by externl — APPROVED** [review]
Why does this test only fail sometimes?

File: cpp/test/Ice/proxy/AllTests.cpp [hunk 1]
```diff
@@ -1186,6 +1186,7 @@ allTests(TestHelper* helper)
 
     cout << "ok" << endl;
 
+#if (!defined(__APPLE__) || TARGET_OS_IPHONE == 0)
```
Comment (bernardnormier) [inline cpp/test/Ice/proxy/AllTests.cpp:1191]: Need to add a comment explaining why it's disabled for iOS, something like:
```cp
// TODO: with iOS, we get: 
// collate_byname<char>::collate_byname failed to construct for en_US.UTF-8
```

Otherwise, I wonder if on iOS proxyToString is affected by the current locale.
