### PR TITLE
Fix spurious wakeup handling in iOS CFStream selector

### LINKED ISSUE #4962: objc iOS test suite connection refused
```
*** [1/30] Running objective-c/Ice/acm tests ***
[ running client/server test - 01/27/26 11:16:08 ]
- Config: arc-xcodesdk,iphoneos
(executing `Ice/acm/server' on `iOS Device' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.Default.Protocol=tcp', '--Ice.IPv6=0', '--Ice.ThreadPool.Server.Size=1', '--Ice.ThreadPool.Server.SizeMax=3', '--Ice.ThreadPool.Server.SizeWarn=0'])
(executing `Ice/acm/client' on `iOS Device' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.Default.Protocol=tcp', '--Ice.IPv6=0'])
StreamTransceiver.cpp:242: ::Ice::ConnectionRefusedException:
connection refused: Connection refused
Traceback (most recent call last):
  File "/Users/joe/Developer/zeroc-ice/ice/objective-c/./../scripts/Util.py", line 1236, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joe/Developer/zeroc-ice/ice/objective-c/./../scripts/Util.py", line 2194, in waitSuccess
    raise RuntimeError("unexpected exit status: expected: %d, got %d\n" % (exitstatus, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #4962

### CODE REVIEW

File: cpp/src/Ice/Selector.cpp [hunk 1]
```diff
@@ -1458,9 +1458,10 @@ Selector::select(int timeout)
             {
                 if(!timedWait(IceUtil::Time::seconds(timeout)))
                 {
-                    break;
+                    throw SelectorTimeoutException(); // Actual timeout
                 }
-                throw SelectorTimeoutException();
+                // Signaled but no ready handlers - spurious wakeup, continue waiting
+                continue;
```
Comment (externl) [inline cpp/src/Ice/Selector.cpp]: Is this true, the wake up could be because of ready handlers or spurious wake, no?

Comment (pepone) [reply cpp/src/Ice/Selector.cpp]: Yes, you are right we better re-check the ready handlers in this case.

**Review by externl — APPROVED** [review]
Looks good!
