### PR TITLE
Fix C# multicast bug on Windows 

### LINKED ISSUE #3882: C# Ice.PluginInitializationException for IceDiscovery when IP address is not specified
### Version

- Ice 3.8 Nightly
- Windows 11

### Describe the bug

When attempting to initialize a communicator for a server in C# using IceDiscovery to listen for clients on Windows 11, you will get an Ice.PluginInitializationException unless you specify an IP. In my case, specifying the IP was done through a command argument `dotnet run --IceDiscovery.Interface=127.0.0.1`.

### Expected behavior

Instead of throwing an exception, the server is expected to finish initializing and begin listening for clients.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR fixes #3882.

The root issue was that getLocalAddresses was returning sometimes on Windows 11 169.x addresses (C# only).

This PR also simplifies the corresponding C++ code.

### CODE REVIEW

File: cpp/src/Ice/Network.cpp [hunk 1]
```diff
@@ -113,7 +113,8 @@ namespace
         return fd;
     }
 
-    vector<Address> getLocalAddresses(ProtocolSupport protocol, bool includeLoopback, bool singleAddressPerInterface)
```
Comment (bernardnormier) [inline cpp/src/Ice/Network.cpp:116]: We only call this function once with includeLoopback=true and singleAddressPerInterface=true

File: cpp/src/Ice/Network.cpp [hunk 2]
```diff
@@ -191,15 +184,15 @@ namespace
...
-            if (curr->ifa_addr && (includeLoopback || !(curr->ifa_flags & IFF_LOOPBACK)))
+            if (curr->ifa_addr)
             {
                 if (curr->ifa_addr->sa_family == AF_INET && protocol != EnableIPv6)
                 {
                     Address addr;
                     memcpy(&addr.saStorage, curr->ifa_addr, sizeof(sockaddr_in));
                     if (addr.saIn.sin_addr.s_addr != 0)
                     {
-                        if (!singleAddressPerInterface || interfaces.find(curr->ifa_name) == interfaces.end())
```
Comment (bernardnormier) [inline cpp/src/Ice/Network.cpp:202]: becomes `!true || ...`

File: cpp/src/Ice/Network.cpp [hunk 3]
```diff
@@ -291,10 +284,9 @@ namespace
                     {
                         Address addr;
                         memcpy(&addr.saStorage, &ifr[j].ifr_addr, sizeof(sockaddr_in));
-                        if (addr.saIn.sin_addr.s_addr != 0 &&
```
Comment (bernardnormier) [inline cpp/src/Ice/Network.cpp:294]: All this code is apparently for Solaris and AIX. I think we should remove it.

File: csharp/src/Ice/Internal/Network.cs [hunk 4]
```diff
@@ -578,7 +579,9 @@ internal static IPAddress[] getLocalAddresses(int protocol, bool singleAddressPe
         try
         {
             addresses = new List<IPAddress>();
-            NetworkInterface[] nics = NetworkInterface.GetAllNetworkInterfaces();
+            IEnumerable<NetworkInterface> nics = NetworkInterface.GetAllNetworkInterfaces().Where(
+                nic => nic.SupportsMulticast && nic.OperationalStatus == OperationalStatus.Up);
```
Comment (bernardnormier) [inline csharp/src/Ice/Internal/Network.cs:583]: The actual fix.

File: cpp/src/Ice/Network.cpp (hunk 3 above)
Comment (InsertCreativityHere) [reply cpp/src/Ice/Network.cpp:294]: I agree we should just remove all this.
Definitely seems like it's just leftover from Solaris support...

File: cpp/src/Ice/Network.cpp (hunk 1 above)
Comment (InsertCreativityHere) [reply cpp/src/Ice/Network.cpp:116]: Very nice simplification.
Crazy we still had these 2 bools sitting around...

**Review by InsertCreativityHere — APPROVED** [review]
Looks good to me!

File: cpp/src/Ice/Network.cpp (hunk 3 above)
Comment (externl) [reply cpp/src/Ice/Network.cpp:294]: We should definitely remove this.

**Review by externl — APPROVED** [review]
