### PR TITLE
Fix segmentation fault in Communicator __aexit__

### LINKED ISSUE #3824: Ice/asyncio test failure
See https://github.com/zeroc-ice/ice/actions/runs/14266952064/job/39991012366?pr=3802

```
[ running client/server test - 04/04/25 14:18:03 ]
- Config: ws,compress,ipv6,serialize,mx
("/opt/hostedtoolcache/Python/3.13.2/arm64/bin/python3"  /home/runner/work/ice/ice/python/test/TestHelper.py Server --Ice.Default.Host=::1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'LD_LIBRARY_PATH': '/home/runner/work/ice/ice/cpp/lib/aarch64-linux-gnu', 'PYTHONPATH': '/home/runner/work/ice/ice/python/python:/home/runner/work/ice/ice/python/test/Ice/asyncio'})
("/opt/hostedtoolcache/Python/3.13.2/arm64/bin/python3"  /home/runner/work/ice/ice/python/test/TestHelper.py Client --Ice.Default.Host=::1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none env={'LD_LIBRARY_PATH': '/home/runner/work/ice/ice/cpp/lib/aarch64-linux-gnu', 'PYTHONPATH': '/home/runner/work/ice/ice/python/python:/home/runner/work/ice/ice/python/test/Ice/asyncio'})
testing invocation... ok
testing builtin in operations... ok
testing exceptions... ok
testing cancellation... ok
testing communicator shutdownCompleted... ok
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)
Python runtime state: finalizing (tstate=0x0000ff152d1412d8)

Thread 0x0000ff152d322020 (most recent call first):
  <no Python frame>

Extension modules: IcePy (total: 1)

test in Ice/asyncio failed:
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #3824

### CODE REVIEW

File: python/modules/IcePy/Communicator.cpp [hunk 1]
```diff
@@ -245,6 +245,7 @@ communicatorDealloc(CommunicatorObject* self)
     delete self->communicator;
     delete self->shutdownException;
     delete self->shutdownFuture;
+    delete self->executor;
```
Comment (pepone) [inline python/modules/IcePy/Communicator.cpp:248]: unrelated fix, we were leaking this.

File: python/modules/IcePy/Communicator.cpp [hunk 2]
```diff
@@ -328,17 +321,39 @@ communicatorDestroyAsync(CommunicatorObject* self, PyObject* /*args*/)
...
+                if (!Py_IsFinalizing())
                 {
-                    PyObjectHandle discard{callMethod(futureGuard.get(), "set_result", Py_None)};
+                    Py_DECREF(setResult);
+                    Py_DECREF(setResultArgs);
                 }
+#endif
             });
-    return IcePy::wrapFuture(*self->communicator, future.get());
+    return Py_None;
```
[the remark this answers is not in the document]
Comment (pepone) [reply python/modules/IcePy/Communicator.cpp:356]: Doesn't apply to new Python versions, Py_None is an immortal object.

File: python/modules/IcePy/Communicator.cpp [hunk 3]
```diff
@@ -283,40 +284,31 @@ communicatorDestroy(CommunicatorObject* self, PyObject* /*args*/)
...
+    if (!PyCallable_Check(setResult))
+    {
+        PyErr_SetString(PyExc_TypeError, "setResult must be callable");
+        return nullptr;
+    }
 
     (*self->communicator)
         ->destroyAsync(
-            [self, vfm, futureObject]()
+            [self, setResult = Py_NewRef(setResult), vfm]()
```
Comment (bernardnormier) [inline python/modules/IcePy/Communicator.cpp:307]: I don't understand why we need to make a new "ref" for `completed`.

This communicatorDestroyAsync is an internal function and I expect all callers (in our Python code) will ensure the completed callback remains alive until `completed` is called.

File: python/modules/IcePy/Communicator.cpp [hunk 4]
```diff
@@ -328,17 +320,39 @@ communicatorDestroyAsync(CommunicatorObject* self, PyObject* /*args*/)
                 Py_XDECREF(self->wrapper);
                 self->wrapper = nullptr;
 
-                PyObject* err = PyErr_Occurred();
-                if (err)
+                PyObject* setResultArgs = PyTuple_Pack(1, Py_None);
```
Comment (bernardnormier) [inline python/modules/IcePy/Communicator.cpp:323]: I would call it `emptyTuple`. You're sure that's the simplest way to create an empty tuple?

Comment (pepone) [reply python/modules/IcePy/Communicator.cpp:323]: It is not empty it has 1 argument None.

File: python/modules/IcePy/Communicator.cpp [hunk 5]
```diff
@@ -328,17 +320,39 @@ communicatorDestroyAsync(CommunicatorObject* self, PyObject* /*args*/)
...
+
+                // Calling setResult completes the future that Communicator.__aexit__ is awaiting. Note that the
+                // future's callbacks can start running before PyObject_Call returns. In a typical Ice application, the
+                // main script exits once this future is completed, which can trigger Python interpreter finalization.
+                //
+                // If the interpreter is already finalizing by the time PyObject_Call returns, we must avoid releasing
+                // the references to setResult and setResultArgs, as invoking Python API functions (like Py_DECREF)
+                // during finalization is not safe. In that case, we intentionally leak these objects to prevent
+                // potential crashes.
+                PyObject* result = PyObject_Call(setResult, setResultArgs, nullptr);
```
[the remark this answers is not in the document]
Comment (pepone) [reply python/modules/IcePy/Communicator.cpp:338]: We can pass a lambda that calls `set_result(None)`. We still have to pass a tuple to `PyObject_Call` event if it is the empty tuple.

File: python/modules/IcePy/Communicator.cpp (hunk 4 above)
Comment (bernardnormier) [reply python/modules/IcePy/Communicator.cpp:323]: We should remove the arg to the callback. Then we can use an empty tuple - an immortal one with 3.13:
https://docs.python.org/3.13/c-api/object.html#c.Py_CONSTANT_EMPTY_TUPLE

File: python/modules/IcePy/Communicator.cpp (hunk 3 above)
Comment (bernardnormier) [reply python/modules/IcePy/Communicator.cpp:307]: Yes, you're right. Please add a comment.

File: python/modules/IcePy/Communicator.cpp (hunk 4 above)
Comment (pepone) [reply python/modules/IcePy/Communicator.cpp:323]: I would rather keep the arg, this is the same API as asyncio.Future

https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.set_result

We can pass a lambda callback as @externl suggest

File: python/modules/IcePy/Communicator.cpp [hunk 6]
```diff
@@ -328,17 +320,39 @@ communicatorDestroyAsync(CommunicatorObject* self, PyObject* /*args*/)
...
+                assert(result == nullptr || result == Py_None);
+                if (result == nullptr)
                 {
-                    PyObjectHandle discard{callMethod(futureGuard.get(), "set_exception", err)};
+                    PyErr_PrintEx(0);
                 }
-                else
+
+#if PY_VERSION_HEX >= 0x030D0000
```
[the remark this answers is not in the document]
Comment (pepone) [reply python/modules/IcePy/Communicator.cpp:345]: Yes we require 3.12

File: python/modules/IcePy/Communicator.cpp [hunk 7]
```diff
@@ -328,17 +324,45 @@ communicatorDestroyAsync(CommunicatorObject* self, PyObject* /*args*/)
...
+                // With Python 3.13 and later, we use Py_IsFinalizing to conditionally release the references to
+                // completed and emptyArgs when the interpreter is not finalizing.
+                if (!Py_IsFinalizing())
+                {
+                    Py_DECREF(completed);
+                    Py_DECREF(emptyArgs);
+                }
+#endif
+                // Check whether we still own the GIL. If interpreter finalization has begun, we may no longer hold the
+                // GIL and must avoid calling PyGILState_Release unless we do
```
Comment (bernardnormier) [inline python/modules/IcePy/Communicator.cpp:359]: Missing period at the end of the comment.

File: python/modules/IcePy/Communicator.cpp [hunk 8]
```diff
@@ -328,17 +324,45 @@ communicatorDestroyAsync(CommunicatorObject* self, PyObject* /*args*/)
                 Py_XDECREF(self->wrapper);
                 self->wrapper = nullptr;
 
-                PyObject* err = PyErr_Occurred();
-                if (err)
+                PyObject* emptyArgs = PyTuple_New(0);
```
Comment (bernardnormier) [inline python/modules/IcePy/Communicator.cpp:327]: Maybe at a reminder to upgrade to the empty tuple constant with 3.13?

**Review by bernardnormier — APPROVED** [review]
Looks good.

**Review by externl — APPROVED** [review]

File: python/modules/IcePy/Communicator.cpp (hunk 8 above)
Comment (pepone) [reply python/modules/IcePy/Communicator.cpp:327]: Not sure we have empty tuples all over the place, at some point when we increase the minimum supported version we would need to go over the new features.
