### PR TITLE
Fix Ice/background test failures

### LINKED ISSUE #1893: C++ Ice/background test failures with CI
Saw this with the CI windows build.

```
2024-03-01T20:52:37.5885298Z D:\a\ice\ice\cpp\test\Ice\background\AllTests.cpp:150: assertion `f1.wait_for(chrono::milliseconds(0)) != future_status::ready' failed
2024-03-01T20:52:37.5886905Z !! 03/01/24 20:48:19308 error: communicator not destroyed during global destruction.
2024-03-01T20:52:37.5887788Z 
2024-03-01T20:52:37.5887978Z test in Ice/background failed:
2024-03-01T20:52:37.5888480Z Traceback (most recent call last):
2024-03-01T20:52:37.5889347Z   File "D:\a\ice\ice\scripts\Util.py", line 2050, in run
2024-03-01T20:52:37.5890027Z     self.runWithDriver(current)
2024-03-01T20:52:37.5890770Z   File "D:\a\ice\ice\scripts\Util.py", line 2081, in runWithDriver
2024-03-01T20:52:37.5892462Z     current.driver.runClientServerTestCase(current)
2024-03-01T20:52:37.5893566Z   File "D:\a\ice\ice\scripts\LocalDriver.py", line 680, in runClientServerTestCase
2024-03-01T20:52:37.5894580Z     self.runner.runClientSide(client, current, host)
2024-03-01T20:52:37.5895538Z   File "D:\a\ice\ice\scripts\LocalDriver.py", line 207, in runClientSide
2024-03-01T20:52:37.5897647Z     testcase._runClientSide(current, host)
2024-03-01T20:52:37.5898992Z   File "D:\a\ice\ice\scripts\Util.py", line 2027, in _runClientSide
2024-03-01T20:52:37.5899869Z     self.runClientSide(current)
2024-03-01T20:52:37.5900687Z   File "D:\a\ice\ice\scripts\Util.py", line 1913, in runClientSide
2024-03-01T20:52:37.5901523Z     self._runClient(current, client)
2024-03-01T20:52:37.5902342Z   File "D:\a\ice\ice\scripts\Util.py", line 2039, in _runClient
2024-03-01T20:52:37.5903135Z     client.run(current)
2024-03-01T20:52:37.5903950Z   File "D:\a\ice\ice\scripts\Util.py", line 1441, in run
2024-03-01T20:52:37.5904868Z     process.waitSuccess(exitstatus=exitstatus, timeout=30)
2024-03-01T20:52:37.5905820Z   File "D:\a\ice\ice\scripts\Expect.py", line 691, in waitSuccess
2024-03-01T20:52:37.5906610Z     self.testExitStatus(exitstatus)
2024-03-01T20:52:37.5907355Z   File "D:\a\ice\ice\scripts\Expect.py", line 735, in testExitStatus
2024-03-01T20:52:37.5908075Z     test(self.exitstatus, exitstatus)
2024-03-01T20:52:37.5908785Z   File "D:\a\ice\ice\scripts\Expect.py", line 717, in test
2024-03-01T20:52:37.5909448Z     raise RuntimeError(
2024-03-01T20:52:37.5910083Z RuntimeError: unexpected exit status: expected: 0, got 3221226505
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #1893

Question for reviewers, should we use large timeouts "10ms" in `wait_for(chrono::milliseconds(0)) != future_status::ready)` calls?

### CODE REVIEW

File: cpp/test/Ice/background/AllTests.cpp [hunk 1]
```diff
@@ -132,8 +132,7 @@ allTests(TestHelper* helper)
         backgroundController->resumeCall("findAdapterById");
 
         locator = LocatorPrx(communicator, "locator:" + endp);
-        obj = obj->ice_locator(locator);
-        obj->ice_ping();
+        locator->ice_ping();
```
Comment (bernardnormier) [inline cpp/test/Ice/background/AllTests.cpp:135]: It's a different test.

Before: we were pinging an indirect proxy (I assume), resolved via locator
After: we ping the locator itself

Is this undoing an accidental change from a previous PR?

**Comment by bernardnormier** [comment]
> Question for reviewers, should we use large timeouts "10ms" in wait_for(chrono::milliseconds(0)) != future_status::ready) calls?

Yes, I think it would be clearer to wait for 10ms than wait for 0ms. With 0, it's not clear we wait at all.

File: cpp/test/Ice/background/AllTests.cpp (hunk 1 above)
Comment (pepone) [reply cpp/test/Ice/background/AllTests.cpp:135]: > Is this undoing an accidental change from a previous PR?

Yes, see comments in #1893. In the original version before the proxy usage refactoring in the test we ping the locator not the indirect the proxy.

**Review by bernardnormier — APPROVED** [review]

**Review by bentoi — APPROVED** [review]
