### PR TITLE
Fix DataStorm code to not schedule tasks with a destroyed timer.

### LINKED ISSUE #2938: DataStorm/config assertion failure (macos)
from https://github.com/zeroc-ice/ice/actions/runs/11418709851/job/31772470210?pr=2937

```
*** [232/340] Running cpp/DataStorm/config tests ***
[ running Writer/Reader test - 10/19/24 15:50:45 ]
(/Users/runner/work/ice/ice/cpp/test/DataStorm/config/build/macosx/shared/reader --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --DataStorm.Node.Multicast.Enabled=0 --DataStorm.Node.Server.Endpoints="tcp -p 14010" --DataStorm.Trace.Topic=1 --DataStorm.Trace.Session=3 --DataStorm.Trace.Data=2 --Ice.LogFile=/Users/runner/work/ice/ice/cpp/test/DataStorm/config/server-101924-1550.log)
(/Users/runner/work/ice/ice/cpp/test/DataStorm/config/build/macosx/shared/writer --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.PrintStackTraces=1 --DataStorm.Node.Multicast.Enabled=0 --DataStorm.Node.Server.Enabled=0 --DataStorm.Node.ConnectTo="tcp -p 14010" --DataStorm.Trace.Topic=1 --DataStorm.Trace.Session=3 --DataStorm.Trace.Data=2 --Ice.LogFile=/Users/runner/work/ice/ice/cpp/test/DataStorm/config/client-101924-1550.log)
testing writer/reader name... ok
testing writer sampleCount... ok
testing reader sampleCount... ok
testing writer sampleLifetime... ok
testing reader sampleLifetime... ok
testing writer clearHistory... ok
testing reader clearHistory... ok
testing priority discard policy... ok
testing send time discard policy... timer destroyed
Assertion failed: (false), function remove, file ConnectionManager.cpp, line 81.
saved /Users/runner/work/ice/ice/cpp/test/DataStorm/config/client-101924-1550.log
saved /Users/runner/work/ice/ice/cpp/test/DataStorm/config/server-101924-1550.log
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #2938

I added a few helper functions in DataStorm instance to avoid using a destroyed timer. The helpers methods ignore schedule calls if the timer is already destroyed, which is what we did with the original DataStorm timer.

### CODE REVIEW

File: cpp/src/DataStorm/Instance.h [hunk 1]
```diff
@@ -105,6 +99,37 @@ namespace DataStormI
 
         void destroy(bool);
 
+        // Helper methods to schedule and cancel timer tasks with the instance timers, schedule and cancel calls
+        // done after the instance is destroyed are ignored.
+
+        template<class Rep, class Period>
+        void scheduleTimerTask(std::function<void()> function, const std::chrono::duration<Rep, Period>& delay)
+        {
+            std::unique_lock<std::mutex> lock(_mutex);
```
Comment (externl) [inline cpp/src/DataStorm/Instance.h:108]: Should we throw an exception if the timer is null. Otherwise you get the illusion that it worked.

Comment (pepone) [reply cpp/src/DataStorm/Instance.h:108]: These timers are used for reconnect sessions, or retry connection failures, there is a chance this happens during destroy and it is fine to ignore, the timer is only ever null if we are destroying the node.

we already throw invalid_argument from Ice::Timer in this case, another option would be to ignore it, but I think it is clear this way that we are only ignoring scheduled calls once we are destroyed.

**Review by externl — APPROVED** [review]

**Review by bernardnormier — APPROVED** [review]
