### PR TITLE
Fix operation mode check in C++, C# and Java

### LINKED ISSUE #3679: Update operation mode check during dispatch
The operation mode check performed during dispatch should always succeed when the received operation mode is Normal.

The bad situation we want to detect and report is when the client believes an operation is idempotent but the local implementation believes it's not.

See also:
https://github.com/icerpc/icerpc-csharp/blob/f109b98c1cb69755ccca7ddf3cc247982e7afb8c/src/IceRpc.Slice/IncomingRequestExtensions.cs#L13

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #3679.

We should be checking this operation mode for mismatch in all languages with server-side support, but currently only check it in C++, C#, Java and Python.

We have a TODO in slice2swift:
https://github.com/zeroc-ice/ice/blob/db9df33024761cc5fb281fbb8f390b415cc041b4/cpp/src/slice2swift/SwiftUtil.cpp#L1615

I can't find where we check it in JS (if we check it).

### CODE REVIEW

File: cpp/src/slice2java/Gen.cpp [hunk 1]
```diff
@@ -21,7 +21,7 @@ namespace
         switch (opMode)
         {
             case Operation::Normal:
-                mode = "null"; // shorthand for most common case
```
Comment (bernardnormier) [inline cpp/src/slice2java/Gen.cpp:24]: We should not do that anywhere.

**Review by externl — APPROVED** [review]

**Review by pepone — APPROVED** [review]

**Comment by pepone** [comment]
> I can't find where we check it in JS (if we check it).

I will review JS code.
