### PR TITLE
Fix close implementation

### LINKED ISSUE #2698: Check if close requested when canceling an invocation
The C++, C# and Java code currently do not check if "close was requested" when canceling a two-way invocation - but they should.

JS is already correct.

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR fixes to close implementation in C++, C# and Java to take into account request cancellation.

It also updates the JS implementation to be more like the C++/C#/Java implementations.

Fixes #2698

### CODE REVIEW

File: js/src/Ice/ConnectionI.js [hunk 1]
```diff
@@ -220,34 +220,18 @@ export class ConnectionI {
...
-        // requests have completed and we can transition to StateClosing. We also
-        // complete outstanding promises.
-        //
-        if (this._asyncRequests.size === 0 && this._closed !== undefined) {
-            //
-            // The caller doesn't expect the state of the connection to change when this is called so we queue the
-            // check in the event loop an return control to the caller. This is consistent with other implementations
-            // as well.
-            //
-            Timer.setImmediate(() => {
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:244]: I removed this Timer.setImmediate logic. It does not make sense to me for "application close". Am I missing something?

File: js/src/Ice/ConnectionI.js [hunk 2]
```diff
@@ -760,7 +750,6 @@ export class ConnectionI {
             value.completedEx(this._exception);
         }
         this._asyncRequests.clear();
-        this.checkClose();
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:763]: This checkClose was not correct. We're in finish and already closed here.

**Review by pepone — APPROVED** [review]

**Review by externl — APPROVED** [review]

File: js/src/Ice/ConnectionI.js (hunk 1 above)
Comment (pepone) [reply js/src/Ice/ConnectionI.js:244]: I agree
