### PR TITLE
Fix null reference skipping optional class

### LINKED ISSUE #1295: TypeError Skipping and optional class in JavaScript
```
Ice.js:10296 Uncaught (in promise) TypeError: patcher is not a function
    at Ice.js:10296
    at __init__.readInstance (Ice.js:8706)
    at __init__.readObject (Ice.js:8311)
    at __init__.readObject (Ice.js:10289)
    at __init__.skipOpt (Ice.js:10423)
    at __init__.skipOpts (Ice.js:10452)
    at __init__.endSlice (Ice.js:8448)
    at __init__.endReadSlice (Ice.js:9787)
    at __readImpl (Ice.js:2656)
    at Object.__read (Ice.js:2514)
```

The problem is that the patcher captured in this closure is null https://github.com/zeroc-ice/ice/blob/3.6/js/src/Ice/BasicStream.js#L2580

### PR DESCRIPTION
**Pull request by pepone**
This PR fixes #1295

### CODE REVIEW

File: js/src/Ice/BasicStream.js [hunk 1]
```diff
@@ -2572,7 +2572,7 @@ var BasicStream = Class({
         //
         this._readEncapsStack.decoder.readObject.call(
             this._readEncapsStack.decoder,
-            function(obj){
+            patcher == null ? null : function(obj){
```
Comment (bentoi) [inline js/src/Ice/BasicStream.js:2575]: I would use `=== null` to be consistent.

**Review by bentoi — APPROVED** [review]
