### PR TITLE
Fix DataStorm filter element ID handling and correctness bugs

### LINKED ISSUE #5132: Fix DataStorm correctness bugs: data race, move-assignment leak, double-negation, uninitialized member
### 1. Data race in `NodeI::forwardToPublishers` — missing mutex lock

**File:** `cpp/src/DataStorm/NodeI.cpp` lines 667–679
**Severity:** High — data race / undefined behavior

`forwardToPublishers` iterates `_publishers` without acquiring `_mutex`. Its counterpart `forwardToSubscribers` (line 653) correctly acquires the lock. Since `_publishers` is concurrently modified by `createPublisherSessionServant`, `removePublisherSession`, and `destroy`, iterating without the lock is a data race.

**Fix:** Add `lock_guard<mutex> lock(_mutex);` at the start of `forwardToPublishers`.

### 2. `Node::operator=(Node&&)` leaks the previous instance

**File:** `cpp/src/DataStorm/Node.cpp` lines 93–99
**Severity:** High — resource leak

The move-assignment operator overwrites `_instance` without first destroying the previous instance. The destructor (lines 66–72) correctly calls `_instance->destroy(_ownsCommunicator)`. If a live `Node` is move-assigned, its original communicator, object adapters, timer, callback executor, and connection manager are all leaked.

**Fix:** Destroy the old instance before overwriting, and handle self-assignment:

```cpp
Node& Node::operator=(Node&& node) noexcept
{
    if (this != &node)
    {
        if (_instance)
        {
            _instance->destroy(_ownsCommunicator);
        }
        _instance = std::move(node._instance);
        _factory = std::move(node._factory);
        _ownsCommunicator = node._ownsCommunicator;
    }
    return *this;
}
```

### 3. Double-negation of filter element ID in `DataElementI::disconnect()`

**File:** `cpp/src/DataStorm/DataElementI.cpp` lines 641–654
**Severity:** Medium — filter subscriptions not cleaned up on element destruction

When a data element with filter subscriptions is destroyed, `disconnect()` passes the already-negated `k.second` to `disconnectFromFilter`. This value is forwarded to `unsubscribeFromFilter` (SessionI.cpp line 1076), which negates it again: `subscriber.get(-elementId)`. The double-negation produces a positive key, but filter entries are stored under negative keys — the lookup fails silently and the filter subscription is orphaned.

Contrast with `detachFilter` (line 392), which correctly calls `p->second.get(topicId, -elementId)` with a positive `elementId` that gets negated once.

**Fix:** Negate `k.second` in `disconnect()`:

```cpp
listener.first.session->disconnectFromFilter(k.first, -k.second, shared_from_this(), ks.second->id);
```

### 4. `DataReaderI::_instanceCount` is never initialized or updated

**File:** `cpp/src/DataStorm/DataElementI.h` line 380, `DataElementI.cpp` lines 692–696
**Severity:** Medium — undefined behavior

`int _instanceCount` is not initialized in any constructor and never assigned anywhere. `getInstanceCount()` returns an indeterminate value. Reading an uninitialized variable is UB.

**Fix:** Initialize to zero: `int _instanceCount{0};`

If instance counting is intended to be functional, it should also be incremented/decremented in the appropriate connection callbacks.

### PR DESCRIPTION
**Pull request by pepone**
## Summary

DataStorm uses negative IDs to represent subscriptions to filters, and positive IDs to represent subscriptions to keys. This PR centralizes the sign conversion in `attachFilter` and updates methods that take a filter ID to accept the already-negated (internal) value, instead of performing sign conversions in multiple places.

This PR also includes the following correctness fixes (closes #5141):

- **Data race**: Add missing `lock_guard<mutex>` in `NodeI::forwardToPublishers` which iterates `_publishers` without synchronization, unlike its counterpart `forwardToSubscribers`.
- **Resource leak**: Fix `Node::operator=(Node&&)` to destroy the previous instance before overwriting, preventing leaks of the communicator, adapters, timer, and connection manager.
- **Double-negation**: Fix `DataElementI::disconnect()` passing an already-negated filter element ID to `disconnectFromFilter`, which negates it again — the positive key fails to match filter entries stored under negative keys, silently orphaning the subscription.
- **Uninitialized member**: Initialize `DataReaderI::_instanceCount` to zero to avoid undefined behavior from reading an indeterminate value.

Fixes #5132

## Test plan
- [ ] CI passes
- [ ] DataStorm test suite passes

### CODE REVIEW

File: cpp/src/DataStorm/DataElementI.cpp [hunk 1]
```diff
@@ -338,8 +338,12 @@ DataElementI::attachFilter(
         p = _listeners.emplace(std::move(listenerKey), Listener{std::move(prx), facet}).first;
     }
 
+    // Negate the element ID for internal storage — filter subscriptions use negative IDs to distinguish them from
+    // key subscriptions. All subsequent internal functions receive and use this negated ID directly.
+    int64_t filterId = -elementId;
```
Comment (externl) [inline cpp/src/DataStorm/DataElementI.cpp]: Can we also add a `> 0` assert.

Comment (bernardnormier) [reply cpp/src/DataStorm/DataElementI.cpp]: Can we make this filterId const?
