### PR TITLE
Ensure that request reply is not processed before the request is marked as sent

### LINKED ISSUE #3087: JavaScript Ice/ami assert
```
testing AsyncResult operations... Trace: Assertion failed: undefined
    at Debug.assert (file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/Debug.js:8:21)
    at OutgoingAsync.markSent (file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/AsyncResult.js:47:15)
    at OutgoingAsync.markSent (file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/OutgoingAsync.js:149:24)
    at OutgoingAsync.sent (file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/OutgoingAsync.js:377:14)
    at OutgoingMessage.sent (file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/ConnectionI.js:1504:27)
    at ConnectionI.sendNextMessage (file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/ConnectionI.js:1156:25)
    at ConnectionI.message (file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/ConnectionI.js:566:26)
    at TcpTransceiver._bytesWrittenCallback (file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/ConnectionI.js:160:28)
    at file:///C:/Users/jose/source/repos/3.8/ice/js/node_modules/ice/src/Ice/TcpTransceiver.js:155:30
    at afterWrite (node:internal/streams/writable:710:5)
```

Got this on a local machine while investigating #2979 , likely related to the same underlying issue.

### PR DESCRIPTION
**Pull request by pepone**
Fix #3087

Edit 1:

Reworked this with requested review comments, added more comments and included fixes for "at-most once" from #3099 as both issues are closely related.

### CODE REVIEW

File: js/src/Ice/ConnectionI.js [hunk 1]
```diff
@@ -1140,9 +1154,17 @@ export class ConnectionI {
         return true;
     }
 
+    /**
+     * Sends the next message in the send queue, if any, and returns an array of messages that have already been sent and
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:1158]: > returns an array of messages that have already been sent and for which a reply has been received.

Message is the terminology we use for Frame in Ice. In this particular case, the messages are necessarily outgoing requests. I would make this clearer in the doc-comment, like:

> returns an array of messages that hold outgoing requests for which we've received replies.

Also, to be clear, do we include / not include oneway requests in this list?

File: js/src/Ice/ConnectionI.js [hunk 2]
```diff
@@ -1154,6 +1176,10 @@ export class ConnectionI {
                 let message = this._sendStreams.shift();
                 this._writeStream.swap(message.stream);
                 message.sent();
+                if (message.receivedReply) {
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:1179]: It would be helpful to add a comment explaining how message.receivedReply can be true.
There is nothing obviously async in this code. Where do we "suspend" to give a chance to receive the reply?

File: js/src/Ice/ConnectionI.js [hunk 3]
```diff
@@ -563,22 +564,25 @@ export class ConnectionI {
                 }
 
                 if ((operation & SocketOperation.Write) !== 0) {
-                    this.sendNextMessage();
+                    messages = this.sendNextMessage();
+                    if (messages !== null) {
+                        ++this.upcallCount;
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:569]: Add a comment.

File: js/src/Ice/ConnectionI.js [hunk 4]
```diff
@@ -591,6 +595,16 @@ export class ConnectionI {
             ++count;
         }
 
+        if (messages != null) {
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:598]: Add a comment.

File: js/src/Ice/ConnectionI.js [hunk 5]
```diff
@@ -591,6 +595,16 @@ export class ConnectionI {
...
+            for (const message of messages) {
+                if (message.outAsync !== null) {
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:600]: messages is a list of outgoing requests for which we've received replies. How can outAsync be null?

File: js/src/Ice/ConnectionI.js [hunk 6]
```diff
@@ -1488,10 +1531,12 @@ export class ConnectionI {
 }
 
 class OutgoingMessage {
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:1533]: OutgoingMessage means outgoing request message? request or batch request?

The fields you added don't seem appropriate for an outgoing reply. You're sure OutgoingMessage is not used for replies?
What about outgoing ValidateConnection, outgoing ConnectionClose?

File: js/src/Ice/ConnectionI.js [hunk 7]
```diff
@@ -1140,9 +1154,17 @@ export class ConnectionI {
...
     }
 
+    /**
+     * Sends the next message in the send queue, if any, and returns an array of messages that have already been sent and
+     * for which a reply has been received. Messages that have been sent are removed from the send queue.
+     *
+     * @returns An array of messages that have been sent and for which a reply has been received, or null if there are no
+     * completed messages.
+     */
     sendNextMessage() {
```
Comment (externl) [inline js/src/Ice/ConnectionI.js:1164]: This the return in the catch block of the try { while {} } loop correct now? Won't this just return undefined. Additionally, does generally catching LocalException here make sense?

File: js/src/Ice/ConnectionI.js [hunk 8]
```diff
@@ -1154,6 +1176,10 @@ export class ConnectionI {
                 let message = this._sendStreams.shift();
                 this._writeStream.swap(message.stream);
                 message.sent();
+                if (message.receivedReply) {
+                    completed ??= [];
+                    completed.push(message);
+                }
```
Comment (externl) [inline js/src/Ice/ConnectionI.js:1182]: Should the break be return like there others, or make the others break so that thy hit the assert check.

File: js/src/Ice/ConnectionI.js (hunk 6 above)
Comment (pepone) [reply js/src/Ice/ConnectionI.js:1533]: > OutgoingMessage means outgoing request message? request or batch request?

It is used for any thing we send with the connection, it can be a request, a response, and validate connection message, a batch request.

> The fields you added don't seem appropriate for an outgoing reply.

we already have the `receivedReply` in the C# version of this.

https://github.com/zeroc-ice/ice/blob/34ce55cb67eee969459b618bfe7e9a5cab91e2c9/csharp/src/Ice/ConnectionI.cs#L2877

File: js/src/Ice/ConnectionI.js (hunk 7 above)
Comment (pepone) [reply js/src/Ice/ConnectionI.js:1164]: need to fix the return.

The catch is fine similar to the C# version

https://github.com/zeroc-ice/ice/blob/34ce55cb67eee969459b618bfe7e9a5cab91e2c9/csharp/src/Ice/ConnectionI.cs#L2095-L2098

Here is a bit more convoluted because in JavaScript there is not catch by type, maybe we should just add an assert to ensure we only catch LocalException, no other exception should appear here.

File: js/src/Ice/ConnectionI.js (hunk 5 above)
Comment (pepone) [reply js/src/Ice/ConnectionI.js:600]: Yes no need for this null check.

File: js/src/Ice/ConnectionI.js (hunk 2 above)
Comment (pepone) [reply js/src/Ice/ConnectionI.js:1179]: I will add a comment.

Here when we call sendNextMessage the first message is always already sent. If the message was sent asynchronously,  and the reply is received almost immediately the Red ready with the reply might be processed before than the Write ready that ends up calling sendNextMessage.

File: js/src/Ice/ConnectionI.js [hunk 9]
```diff
@@ -49,17 +49,6 @@ const StateClosingPending = 5;
 const StateClosed = 6;
 const StateFinished = 7;
 
-class MessageInfo {
```
Comment (pepone) [inline js/src/Ice/ConnectionI.js:52]: Renamed as IncomingMessage, and move below next to OutgoingMessage

File: js/src/Ice/ConnectionI.js [hunk 10]
```diff
@@ -1140,42 +1144,43 @@ export class ConnectionI {
...
+     * sent synchronously.
+     *
+     * If the first message in the queue is a protocol request and its response was received before this method was
+     * called, the response should be cached in the message's response field and will be returned as the result. The
+     * caller is then responsible for processing the response, now that the message has been marked as sent.
+     *
+     * @returns The response of the first message in the send queue if it has been received; null otherwise.
+     */
     sendNextMessage() {
-        if (this._sendStreams.length === 0) {
```
Comment (pepone) [inline js/src/Ice/ConnectionI.js:1144]: This cannot happen in JavaScript implementation, `sendNextMessage` it is only called when we are sending messages.

File: js/src/Ice/ConnectionI.js [hunk 11]
```diff
@@ -1140,42 +1144,43 @@ export class ConnectionI {
...
+     * protocol messages to be sent when the sending cannot complete synchronously or when another protocol message is
+     * in the process of being sent.
+     *
+     * When this method is called, the first message in the send queue (the message currently being sent) has already
+     * been sent and will be removed from the queue.
+     *
+     * This method will continue sending messages until the send queue is empty or until a protocol message cannot be
+     * sent synchronously.
+     *
+     * If the first message in the queue is a protocol request and its response was received before this method was
```
Comment (bernardnormier) [inline js/src/Ice/ConnectionI.js:1158]: I would replace "protocol request" by "outgoing request".

**Review by bernardnormier — APPROVED** [review]
Looks good, but I don't fully understand the logic.

**Review by externl — APPROVED** [review]
Looks good to me. Do other languages follow a similar pattern?

**Comment by pepone** [comment]
> Looks good, but I don't fully understand the logic.

Two issues addressed in the PR.

- Sent, and Complete request events dispatched out of order. This can happen because the asynchronous write-event, gets queued after the read.
- The requests was marked as sent only after if has been sent, but we want to mark it as sent as soon as the buffer is consumed to warranty "at most once" semantics.

The implementation for this fixes is based on the C# code we already have to deal with the same issues.
