### PR TITLE
Fix Ice/maxConnection test failures

### LINKED ISSUE #3131: Ice/maxConnections failure
This test failed in https://github.com/zeroc-ice/ice/actions/runs/11786119716/job/32828768710

Win32 release build.

```
*** [41/94] Running cpp/Ice/maxConnections tests ***
2024-11-11T21:50:28.5515013Z [ running client/server test - 11/11/24 21:44:05 ]
2024-11-11T21:50:28.5515151Z - Config: ssl,Win32
2024-11-11T21:50:28.5519091Z (D:\a\ice\ice\cpp\test\Ice\maxConnections\msbuild\server\Win32\Release\server.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.LogFile=D:\a\ice\ice\cpp\test\Ice\maxConnections\server-111124-2144.log env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\Win32\\Release;D:\\a\\ice\\ice\\cpp\\bin\\Win32\\Release'})
2024-11-11T21:50:28.5522278Z (D:\a\ice\ice\cpp\test\Ice\maxConnections\msbuild\client\Win32\Release\client.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.PrintStackTraces=1 --Ice.Trace.Network=2 --Ice.LogFile=D:\a\ice\ice\cpp\test\Ice\maxConnections\client-111124-2144.log env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\Win32\\Release;D:\\a\\ice\\ice\\cpp\\bin\\Win32\\Release'})
2024-11-11T21:50:28.5522482Z testing the creation of 100 connections... ok
2024-11-11T21:50:28.5522809Z testing the creation of 10 connections with connection lost at 11... ok
2024-11-11T21:50:28.5524118Z testing the creation of 10 connections with connection lost at 11 then recovery... Unexpected exception: D:\a\ice\ice\cpp\src\Ice\StreamSocket.cpp:442 ::Ice::ConnectionLostException connection lost: The specified network name is no longer available.
2024-11-11T21:50:28.5524319Z stack trace:
2024-11-11T21:50:28.5524702Z   0 Ice::LocalException::LocalException at D:\a\ice\ice\cpp\include\Ice\LocalException.h:25
2024-11-11T21:50:28.5525149Z   1 Ice::SyscallException::SyscallException at D:\a\ice\ice\cpp\src\Ice\LocalExceptions.cpp:218
2024-11-11T21:50:28.5525294Z   2 Ice::SocketException::SocketException
2024-11-11T21:50:28.5525753Z   3 Ice::ConnectionLostException::ConnectionLostException at D:\a\ice\ice\cpp\src\Ice\LocalExceptions.cpp:315
2024-11-11T21:50:28.5526101Z   4 IceInternal::StreamSocket::finishRead at D:\a\ice\ice\cpp\src\Ice\StreamSocket.cpp:460
2024-11-11T21:50:28.5526529Z   5 Ice::SSL::Schannel::TransceiverI::finishRead at D:\a\ice\ice\cpp\src\Ice\SSL\SchannelTransceiverI.cpp:869
2024-11-11T21:50:28.5526836Z   6 Ice::ConnectionI::finishAsync at D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:1126
2024-11-11T21:50:28.5527172Z   7 IceInternal::ThreadPool::startMessage at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:845
2024-11-11T21:50:28.5527469Z   8 Ice::ConnectionI::message at D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:1169
2024-11-11T21:50:28.5527766Z   9 IceInternal::ThreadPool::run at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:724
2024-11-11T21:50:28.5528176Z  10 IceInternal::ThreadPool::EventHandlerThread::run at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:1080
2024-11-11T21:50:28.5529401Z  11 std::thread::_Invoke<std::tuple<void (__thiscall `anonymous namespace'::ServiceStatusManager::*)(void),A0x142df39d::ServiceStatusManager *>,0,1> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\thread:61
2024-11-11T21:50:28.5529489Z  12 0000000076dc6403
2024-11-11T21:50:28.5529567Z  13 00000000769467f9
2024-11-11T21:50:28.5529643Z  14 0000000077a17f6d
2024-11-11T21:50:28.5529725Z  15 0000000077a17f3b
2024-11-11T21:50:28.5529737Z 
2024-11-11T21:50:28.5529815Z failed!
2024-11-11T21:50:28.5530397Z D:\a\ice\ice\cpp\test\Ice\maxConnections\AllTests.cpp:124: assertion `false' failed
2024-11-11T21:50:28.5530793Z saved D:\a\ice\ice\cpp\test\Ice\maxConnections\client-111124-2144.log
2024-11-11T21:50:28.5531184Z !! 11/11/24 21:44:42686 error: communicator not destroyed during global destruction.
2024-11-11T21:50:28.5531555Z saved D:\a\ice\ice\cpp\test\Ice\maxConnections\server-111124-2144.log
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #3131

### CODE REVIEW

File: java/test/src/main/java/test/Ice/maxConnections/AllTests.java [hunk 1]
```diff
@@ -134,6 +134,14 @@ private static void testCreateConnectionsWithMaxAndRecovery(
 
         if (postCloseDelay != null) {
             postCloseDelay.run();
+        } else {
+            // We need to wait a tiny bit to let the server remove the connection from its incoming
+            // connection factory.
+            try {
+                Thread.sleep(50);
```
Comment (bernardnormier) [inline java/test/src/main/java/test/Ice/maxConnections/AllTests.java:141]: I would wait for 10ms like in C++ and C#.

**Review by bernardnormier — APPROVED** [review]
