### PR TITLE
Fix ice_invoke and ice_invokeAsync to handle empty result buffer

### LINKED ISSUE #1728: Bogus handling on empty result in InvokeLambdaOutgoing
`{0, 0}` is some times substitute by `std::parit<const Byte*, const Byte*>` which is ok, representing an empty buffer.

But we also replace it by `using Outgoing = ::IceInternal::InvokeLambdaOutgoing<::Ice::Object::Ice_invokeResult>;` in with case it ends up converted into a `vector<Byte> {0, 0}` witch is incorrect.

https://github.com/zeroc-ice/ice/blob/56528a30119fae9c03bb3cb19a7d0decae5f4ebf/cpp/include/Ice/Proxy.h#L166C38-L166C46

There is a similar issue with InvokePromiseOutgoing

https://github.com/zeroc-ice/ice/blob/56528a30119fae9c03bb3cb19a7d0decae5f4ebf/cpp/include/Ice/Proxy.h#L190

I included a fix for the later on https://github.com/zeroc-ice/ice/pull/1727

### PR DESCRIPTION
**Pull request by pepone**
Fix #1728

### CODE REVIEW

File: cpp/test/Ice/invoke/AllTests.cpp [hunk 1]
```diff
@@ -434,14 +442,63 @@ allTests(Test::TestHelper* helper)
...
+        test(result.first);
+        test(result.second.size() == 6); // Empty encapsulation
+    }
+
     //
     // repeat with the future API.
     //
 
     {
+        // Oneway operation with a twoway proxy must return empty encapsulation.
```
Comment (pepone) [inline cpp/test/Ice/invoke/AllTests.cpp:471]: This test worked fine before the fix, oneway operation invoked from twoway proxy returns an empty encapsulation written in 6 bytes.

File: cpp/test/Ice/invoke/AllTests.cpp [hunk 2]
```diff
@@ -434,14 +442,63 @@ allTests(Test::TestHelper* helper)
...
+        auto completed = cl->ice_invokeAsync("opOneway", Ice::OperationMode::Normal, inEncaps);
+        auto result = completed.get();
+        test(result.returnValue);
+        test(result.outParams.size() == 6); // Empty encapsulation
+    }
+
+    {
+        // Oneway operation with a twoway proxy must return empty encapsulation buffer.
         Ice::ByteSeq inEncaps, outEncaps;
+        auto returnValue = cl->ice_invoke("opOneway", Ice::OperationMode::Normal, inEncaps, outEncaps);
```
Comment (pepone) [inline cpp/test/Ice/invoke/AllTests.cpp:482]: That is the original issue I found when upgrading Python in main branch, the returned buffer has two bytes with values 0x0 0x0

File: cpp/test/Ice/invoke/AllTests.cpp [hunk 3]
```diff
@@ -434,14 +442,63 @@ allTests(Test::TestHelper* helper)
...
+        test(returnValue);
+        test(outEncaps.size() == 6); // Empty encapsulation
+    }
+
+    {
+        // Oneway operation with a oneway proxy must return empty encapsulation.
+        Ice::ByteSeq inEncaps, outEncaps;
```
Comment (pepone) [inline cpp/test/Ice/invoke/AllTests.cpp:489]: That is the original issue I found when upgrading Python in main branch, the returned buffer has two bytes with values 0x0 0x0

**Comment by pepone** [comment]
For `ice_invokeAsync` that take a response `std::function` there is no issues, because for oneway we never call the response callback. And for twoway the empty encaps is always written in 6 bytes, so you never get an empty buffer when using a twoway proxy.

File: cpp/test/Ice/invoke/AllTests.cpp [hunk 4]
```diff
@@ -434,14 +442,63 @@ allTests(Test::TestHelper* helper)
...
+        test(returnValue);
+        test(outEncaps.size() == 0 || outEncaps.size() == 6); // Empty encapsulation
+    }
+
+    {
+        // Oneway operation with a oneway proxy must return empty encapsulation.
+        Ice::ByteSeq inEncaps;
         auto completed = oneway->ice_invokeAsync("opOneway", Ice::OperationMode::Normal, inEncaps);
-        test(completed.get().returnValue);
+        auto result = completed.get();
```
Comment (pepone) [inline cpp/test/Ice/invoke/AllTests.cpp:499]: This overload of ice_invokeAsync has the same problem.

File: cpp/include/Ice/Proxy.h [hunk 5]
```diff
@@ -138,7 +152,7 @@ class InvokeOutgoingAsyncT : public OutgoingAsync
             const ::Ice::Byte* encaps;
             ::Ice::Int sz;
             stream->readEncapsulation(encaps, sz);
-            return R { ok, { encaps, encaps + sz } };
+            return makeIceInvokeResult<R>(ok, encaps, sz);
```
Comment (pepone) [inline cpp/include/Ice/Proxy.h:155]: I didn't add a test for this but seems it will be also bogus when `R` is `Ice_invokeResult`.

**Comment by externl** [comment]
Once we merge this PR we should merge 3.7 into main

File: cpp/test/Ice/invoke/AllTests.cpp [hunk 6]
```diff
@@ -434,14 +442,63 @@ allTests(Test::TestHelper* helper)
...
+        test(result.returnValue);
+        test(result.outParams.size() == 0 || result.outParams.size() == 6); // Empty encapsulation
```
Comment (bernardnormier) [inline cpp/test/Ice/invoke/AllTests.cpp:501]: Always 0. 6 looks unexpected to me.

File: cpp/test/Ice/invoke/AllTests.cpp [hunk 7]
```diff
@@ -646,6 +703,8 @@ allTests(Test::TestHelper* helper)
         {
             test(false);
         }
+        test(result);
+        test(outEncaps.size() == 0 || outEncaps.size() == 6); // Empty encapsulation
```
Comment (bernardnormier) [inline cpp/test/Ice/invoke/AllTests.cpp:707]: Should be 0, not 6. We know how it's implemented locally - doesn't depend on the peer.

File: cpp/include/Ice/Proxy.h [hunk 8]
```diff
@@ -101,6 +101,20 @@ typedef IceUtil::Handle<ProxyGetConnection> ProxyGetConnectionPtr;
...
+    return std::make_pair(ok, std::make_pair(first, first + size));
+}
+
+template <> inline ::Ice::Object::Ice_invokeResult
+makeIceInvokeResult<::Ice::Object::Ice_invokeResult>(
+    bool ok,
+    const Ice::Byte* first,
+    ::Ice::Int size)
+{
+    return Ice::Object::Ice_invokeResult { ok, Ice::ByteSeq(first, first + size) };
```
[the remark this answers is not in the document]
Comment (pepone) [reply cpp/include/Ice/Proxy.h:115]:
```
template< class InputIt >vector( InputIt first, InputIt last, 
   const Allocator& alloc = Allocator() );
```
 Constructs the container with the contents of the range [first, last).

Constructor (5) in https://en.cppreference.com/w/cpp/container/vector/vector

File: cpp/include/Ice/Proxy.h (hunk 5 above)
Comment (pepone) [reply cpp/include/Ice/Proxy.h:155]:
```
using Outgoing = ::IceInternal::InvokeLambdaOutgoing<::Ice::Object::Ice_invokeResult>;
::std::function<void(::Ice::Object::Ice_invokeResult&&)> r;
```

And

```
template<typename R>
class InvokeLambdaOutgoing : public InvokeOutgoingAsyncT<R>, public LambdaInvoke
```

File: cpp/include/Ice/Proxy.h [hunk 9]
```diff
@@ -187,7 +201,7 @@ class InvokeLambdaOutgoing : public InvokeOutgoingAsyncT<R>, public LambdaInvoke
             {
                 if(this->_is.b.empty())
                 {
-                    response(R { ok, { 0, 0 }});
+                    response(makeIceInvokeResult<R>(true, 0, 0));
```
[the remark this answers is not in the document]
Comment (pepone) [reply cpp/include/Ice/Proxy.h:204]: Using `{}` seems to produce an empty pair {0, 0} and an empty vector size 0.

File: cpp/include/Ice/Proxy.h (hunk 8 above)
[the remark this answers is not in the document]
Comment (bernardnormier) [reply cpp/include/Ice/Proxy.h:115]: Ok. 

I would add a comment:
```
// Constructs a byte sequence with the bytes in the range [first,  first + size).
```

File: cpp/include/Ice/Proxy.h (hunk 5 above)
Comment (bernardnormier) [reply cpp/include/Ice/Proxy.h:155]: Ok.

File: cpp/include/Ice/Proxy.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (bernardnormier) [reply cpp/include/Ice/Proxy.h:204]: So we only need makeIceInvokeResult<T> for createProxy?

It would be good to add a test - I am wondering if `{ 0, 0 }` is only problematic with Ice_invokeResult because of the 0 literals. When using variables with proper types, we should always get constructor (5) - and never constructor (3) or (10).

File: cpp/include/Ice/Proxy.h [hunk 10]
```diff
@@ -224,7 +238,8 @@ class InvokePromiseOutgoing : public InvokeOutgoingAsyncT<R>, public PromiseInvo
     {
         if(done)
         {
-            this->_promise.set_value(R { true, { 0, 0 }});
+            Ice::ByteSeq empty;
```
[the remark this answers is not in the document]
Comment (bernardnormier) [reply cpp/include/Ice/Proxy.h:241]: Probably simpler / safer to use `{ }` and refactor more in 3.8.

File: cpp/include/Ice/Proxy.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (bernardnormier) [reply cpp/include/Ice/Proxy.h:204]: > Using {} seems to produce an empty pair {0, 0} and an empty vector size 0.

It's actually not clear to me that `{ }` is correct to create a `{ nullptr, nullptr }` pair<Byte*>. What about using `{nullptr, nullptr}`. This is the clearest; the compiler won't confuse nullptr with a byte value.

**Review by bernardnormier — APPROVED** [review]
Looks good.
