### PR TITLE
Simplify stack trace collection code in C++

### LINKED ISSUE #3048: cpp/Ice/timeout failure (Windows)
From https://github.com/zeroc-ice/ice/actions/runs/11666208467/job/32480630322

```
*** [60/93] Running cpp/Ice/timeout tests ***
[ running client/server test - 11/04/24 15:08:44 ]
- Config: ssl,Win32
(D:\a\ice\ice\cpp\test\Ice\timeout\msbuild\server\Win32\Release\server.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=D:\a\ice\ice\cpp\test\Ice\timeout\server-110424-1508.log env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\Win32\\Release;D:\\a\\ice\\ice\\cpp\\bin\\Win32\\Release'})
(D:\a\ice\ice\cpp\test\Ice\timeout\msbuild\client\Win32\Release\client.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.PrintStackTraces=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=D:\a\ice\ice\cpp\test\Ice\timeout\client-110424-1508.log env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\Win32\\Release;D:\\a\\ice\\ice\\cpp\\bin\\Win32\\Release'})
testing connect timeout... ok
testing invocation timeout... ok
testing close timeout... ok
testing invocation timeouts with collocated calls... ok
[ running client/server test - 11/04/24 15:08:51 ]
- Config: ws,ipv6,serialize,mx,Win32
(D:\a\ice\ice\cpp\test\Ice\timeout\msbuild\server\Win32\Release\server.exe --Ice.Default.Host=::1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=D:\a\ice\ice\cpp\test\Ice\timeout\server-110424-1508.log env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\Win32\\Release;D:\\a\\ice\\ice\\cpp\\bin\\Win32\\Release'})
(D:\a\ice\ice\cpp\test\Ice\timeout\msbuild\client\Win32\Release\client.exe --Ice.Default.Host=::1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.PrintStackTraces=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=D:\a\ice\ice\cpp\test\Ice\timeout\client-110424-1508.log env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\Win32\\Release;D:\\a\\ice\\ice\\cpp\\bin\\Win32\\Release'})
testing connect timeout... error: D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:2387 ::Ice::ConnectTimeoutException connection establishment timed out
stack trace:
  0 Ice::LocalException::LocalException at D:\a\ice\ice\cpp\include\Ice\LocalException.h:25
  1 Ice::TimeoutException::TimeoutException
  2 Ice::ConnectTimeoutException::ConnectTimeoutException at D:\a\ice\ice\cpp\include\Ice\LocalExceptions.h:313
  3 `anonymous namespace'::ConnectTimerTask::runTimerTask at D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:50
  4 IceInternal::ThreadObserverTimer::runTimerTask at D:\a\ice\ice\cpp\src\Ice\Instance.cpp:254
  5 IceInternal::Timer::run at D:\a\ice\ice\cpp\src\Ice\Timer.cpp:125
  6 std::thread::_Invoke<std::tuple<void (__thiscall `anonymous namespace'::ServiceStatusManager::*)(void),A0xf1684611::ServiceStatusManager *>,0,1> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\thread:61
  7 00000000762b6403
  8 0000000076b667f9
  9 0000000077e67f6d
 10 0000000077e67f3b
saved D:\a\ice\ice\cpp\test\Ice\timeout\client-110424-1508.log
!! 11/04/24 15:08:55353 error: communicator not destroyed during global destruction.
saved D:\a\ice\ice\cpp\test\Ice\timeout\server-110424-1508.log
```

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR simplifies the stack trace collection code in C++, and moves the initialization to a static function on Ice::Exception.

It also fixes #3048.

### CODE REVIEW

**Review by pepone — APPROVED** [review]
Looks good, not clear why this is faster.

File: cpp/include/Ice/Exception.h [hunk 1]
```diff
@@ -10,6 +10,7 @@
 
 #include <exception>
 #include <memory>
+#include <optional>
```
[the remark this answers is not in the document]
Comment (bernardnormier) [reply cpp/include/Ice/Exception.h]: Removed

File: cpp/src/Ice/Exception.cpp [hunk 2]
```diff
@@ -539,6 +466,59 @@ Ice::Exception::ice_stackTrace() const
     return getStackTrace(*_stackFrames);
 }
 
+bool
+Ice::Exception::ice_enableStackTraceCollection()
```
Comment (externl) [inline cpp/src/Ice/Exception.cpp:470]: Is the `ice_` prefix really necessary?

File: cpp/src/Ice/Exception.cpp [hunk 3]
```diff
@@ -116,40 +85,40 @@ namespace
...
+                process = nullptr;
             }
-#endif
         }
     };
 
     Init init;
+#endif
+
+    inline bool collectStackTraces() noexcept
```
Comment (externl) [inline cpp/src/Ice/Exception.cpp:110]: Should we be using a memory barrier to access these global variables. Isn't there a chance they'll be stale otherwise.

File: cpp/src/Ice/Exception.cpp [hunk 4]
```diff
@@ -539,6 +466,59 @@ Ice::Exception::ice_stackTrace() const
...
+            CloseHandle(process);
+            process = nullptr;
+            throw std::runtime_error{"SymInitialize failed with " + IceInternal::errorToString(GetLastError())};
+        }
+    }
+#elif defined(ICE_LIBBACKTRACE)
+    if (!bstate)
+    {
+        // Leaked, as libbacktrace does not provide an API to free this state.
+        bstate = backtrace_create_state(0, 1, ignoreErrorCallback, 0);
```
Comment (externl) [inline cpp/src/Ice/Exception.cpp:509]: It would be nice to get an error message out of the callback if possible.

File: cpp/src/Ice/Exception.cpp (hunk 2 above)
Comment (bernardnormier) [reply cpp/src/Ice/Exception.cpp:470]: We use this ice_ prefix for all other member functions. No ice_ prefix would be inconsistent.

File: cpp/src/Ice/Exception.cpp [hunk 5]
```diff
@@ -539,6 +466,59 @@ Ice::Exception::ice_stackTrace() const
...
+
+        // The first call to backtrace_pcinfo does not initialize bstate->fileline_fn
+        // in a thread-safe manner, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81098.
+        // So we make a "dummy" call to backtrace_pcinfo to initialize it here.
+        backtrace_pcinfo(bstate, 0, ignoreFrame, ignoreErrorCallback, 0);
+    }
+#elif defined(ICE_BACKTRACE)
+    backTraceEnabled = true;
+#endif
+    return collectStackTraces();
```
[the remark this answers is not in the document]
Comment (bernardnormier) [reply cpp/src/Ice/Exception.cpp:520]: Fixed. It now returns void and the test assumes stack trace collection is available for the current platform/build.

File: cpp/src/Ice/Exception.cpp (hunk 3 above)
Comment (bernardnormier) [reply cpp/src/Ice/Exception.cpp:110]: Added mutex lock.

**Review by externl — APPROVED** [review]

File: cpp/src/Ice/Exception.cpp [hunk 6]
```diff
@@ -539,6 +461,54 @@ Ice::Exception::ice_stackTrace() const
...
+        if (!DuplicateHandle(currentProcess, currentProcess, currentProcess, &process, 0, FALSE, DUPLICATE_SAME_ACCESS))
+        {
+            throw std::runtime_error{
+                "DuplicateHandle on current process failed with " + IceInternal::errorToString(GetLastError())};
+        }
+
+        SymSetOptions(SYMOPT_LOAD_LINES | SYMOPT_DEFERRED_LOADS | SYMOPT_EXACT_SYMBOLS | SYMOPT_UNDNAME);
+        if (!SymInitialize(process, nullptr, TRUE))
+        {
+            CloseHandle(process);
```
Comment (pepone) [inline cpp/src/Ice/Exception.cpp:496]: Maybe construct the error message before calling `CloseHandle` so we get the error from SymInitialize, and not from CloseHandle if it happens to fail too.

File: cpp/src/IceBox/ServiceManagerI.cpp [hunk 7]
```diff
@@ -63,6 +63,17 @@ namespace
...
     };
+
+    inline bool printStackTraces(const PropertiesPtr& properties)
+    {
+#ifdef NDEBUG
+        // Release build
+        return properties->getIcePropertyAsInt("Ice.PrintStackTraces") > 0;
+#else
+        // Debug build
+        return properties->getPropertyAsIntWithDefault("Ice.PrintStackTraces", 1);
```
Comment (pepone) [inline cpp/src/IceBox/ServiceManagerI.cpp:74]:
```suggestion
        return properties->getPropertyAsIntWithDefault("Ice.PrintStackTraces", 1) > 0;
```

**Review by pepone — APPROVED** [review]

File: cpp/src/Ice/Exception.cpp (hunk 6 above)
Comment (bernardnormier) [reply cpp/src/Ice/Exception.cpp:496]: You're right. It's likely CloseHandle resets the last error to 0. Fixed.

File: cpp/src/IceBox/ServiceManagerI.cpp (hunk 7 above)
Comment (bernardnormier) [reply cpp/src/IceBox/ServiceManagerI.cpp:74]: Fixed as suggested (also in Instance.cpp)
