### PR TITLE
Move android controller initialization to a background thread

### LINKED ISSUE #3299: Android computePublishedEndpoints fails with NetworkOnMainThread
```
Process: com.zeroc.testcontroller, PID: 3661
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1675)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1488)
	at com.zeroc.Ice.ObjectAdapter.computePublishedEndpoints(ObjectAdapter.java:1423)
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #3299

### CODE REVIEW

**Review by externl — APPROVED** [review]

File: java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerActivity.java [hunk 1]
```diff
@@ -126,7 +128,18 @@ public void onNothingSelected(AdapterView<?> arg0)
                 }
             });
         s.setSelection(0);
-        app.startController(this, bluetooth);
+
+        // Start the controller in a background thread. Starting the controller creates the ObjectAdapter which makes
+        // IO calls. Android doesn't allow  making IO calls from the main thread.
```
Comment (InsertCreativityHere) [inline java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerActivity.java:133]: An extra space snuck in here.
```suggestion
        // IO calls. Android doesn't allow making IO calls from the main thread.
```

File: java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerActivity.java [hunk 2]
```diff
@@ -126,7 +128,18 @@ public void onNothingSelected(AdapterView<?> arg0)
...
+        Executor executor = Executors.newSingleThreadExecutor();
+        executor.submit(() ->{
```
Comment (InsertCreativityHere) [inline java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerActivity.java:135]: I feel like there should be a space here. Does the formatter reject putting a space here.
```suggestion
        executor.submit(() -> {
```

**Review by InsertCreativityHere — APPROVED** [review]
Looks good to me!
