### PR TITLE
Fix C# connection to correctly mark messages as sent

### LINKED ISSUE #3079: Backport #3072 to 3.7
We need to back port the fix from #3072 to 3.7 branch

### PR DESCRIPTION
**Pull request by pepone**
Fix #3079, see also #3072

### CODE REVIEW

File: csharp/src/Ice/ConnectionI.cs [hunk 1]
```diff
@@ -1064,15 +1064,23 @@ public override bool startAsync(int operation, IceInternal.AsyncCallback complet
...
-                            bool completed;
-                            if (_transceiver.startWrite(_writeStream.getBuffer(), completedCallback, this, out completed))
+                            bool messageWritten = false;
+                            bool completedSynchronously = _transceiver.startWrite(
+                                _writeStream.getBuffer(),
+                                completedCallback,
+                                this,
+                                out messageWritten);
+
+                            // If the startWrite call consumed the complete buffer, we assume the message
```
Comment (bernardnormier) [inline csharp/src/Ice/ConnectionI.cs]: We should use the comments currently on main, not the comments from the old PR:

```cs
                        // If the startWrite call wrote the message, we assume the message is sent now for at-most-once
                        // semantics in the event the connection is closed while the message is still in _sendStreams.
                        if (messageWritten && _sendStreams.Count > 0)
                        {
                            // See finish() code.
                            _sendStreams.First.Value.isSent = true;
                        }


```

Comment (pepone) [reply csharp/src/Ice/ConnectionI.cs]: Fixed the comments to match what we have in main.
