### PR TITLE
Fix Swift race condition

### LINKED ISSUE #3031: Swift Ice/ami failure: Unexpectedly found nil while unwrapping an Optional value
client:
```
testing bi-dir... ok
testing connection abort... ok
testing async invocation...ok
testing local exceptions... ok
testing exceptions with async/await... ok
testing batch requests with proxy... ok
testing batch requests with connection... ok
testing batch requests with communicator... ok
testing connection close... 0   TestDriver                          0x000000010163251c async_MainTY2_ + 156
1   TestDriver                          0x00000001016328c9 $sIetH_yts5Error_pIegHrzo_TRTQ0_ + 1
2   TestDriver                          0x00000001016329f1 $sIetH_yts5Error_pIegHrzo_TRTATQ0_ + 1
3   libswift_Concurrency.dylib          0x0000000279689035 _ZL23completeTaskWithClosurePN5swift12AsyncContextEPNS_10SwiftErrorE + 1
Error src/Ice/Network.cpp:1877 ::Ice::ConnectionRefusedException connection refused
```

server:
```
Ice_ami/TestI.swift:159: Fatal error: Unexpectedly found nil while unwrapping an Optional value
fish: Job 1, 'swift run -c debug --skip-build…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

### PR DESCRIPTION
**Pull request by externl**
There was a race condition that could occur if one thread was trying to access the cached object while another thread was trying to deallocate said object.

Fixes #3031

### CODE REVIEW

File: swift/src/IceImpl/LocalObject.mm [hunk 1]
```diff
@@ -38,16 +41,24 @@ + (nullable instancetype)getHandle:(std::shared_ptr<void>)cppObject
...
+        auto p = cachedObjects->find(cppObject.get());
         if (p != cachedObjects->end())
         {
-            // assert(p->second);
-            return p->second;
-        }
-        else
-        {
-            return [[[self class] alloc] initWithCppObject:std::move(cppObject)];
+            // Get a strong reference to the object. If it's nil, preemptively remove it from the cache,
```
Comment (bernardnormier) [inline swift/src/IceImpl/LocalObject.mm:47]: I am not following the logic.

Say another thread is releasing the last-reference of the ObjC object, and is waiting to enter the synchronization in dealloc below to remove the entry in cachedObjects.
Meaning the entry is still in cacheObjects.

Now, p points to this "about to die" entry. So we remove the entry and create a new entry on line 61, and release the synchronization.

But now the other thread can run dealloc and remove the new entry we've just created... not good.

File: swift/src/IceImpl/DispatchAdapter.mm [hunk 2]
```diff
@@ -63,6 +61,9 @@
     ICEObjectAdapter* adapter = [ICEObjectAdapter getHandle:current.adapter];
     ICEConnection* con = [ICEConnection getHandle:current.con];
 
+    // Both are null or both are non-null
```
[the remark this answers is not in the document]
Comment (externl) [reply swift/src/IceImpl/DispatchAdapter.mm:64]: Yes

File: swift/src/IceImpl/LocalObject.mm (hunk 1 above)
Comment (externl) [reply swift/src/IceImpl/LocalObject.mm:47]: This was essentially the previous issue. We could end up in the situation where dealloc was waiting for the mutex while this function is looking in the map. The new update gets the weak ptr the creates a a strong ptr. 

That's the point of `ICELocalObject* obj = p->second;` If we're in the situation objc is deallocating the object pointed to be p, then this assignment will return nil. Otherwise it will increment the ref count and there's no deallocation sorry.

Comment (bernardnormier) [reply swift/src/IceImpl/LocalObject.mm:44]: https://github.com/bernardnormier/ice/blob/pr/externl/3042/swift/src/IceImpl/LocalObject.mm shows the issue introduced by this PR, and a solution.

**Review by bernardnormier — APPROVED** [review]
Looks good. We should backport this fix to 3.7.

**Review by pepone — APPROVED** [review]
