### PR TITLE
Remove `com.zeroc.Ice.Exception` in Java

### LINKED ISSUE #2765: Remove 'Ice.Exception' from Java
Now that we've simplified our exception hierarchy, there is only one class which inherits from `com.zeroc.Ice.Exception` and that is `LocalException`. So I think we could further simplify our structure by just merging these two together (and keeping the name `LocalException`).

https://github.com/zeroc-ice/ice/blob/main/java/src/Ice/src/main/java/com/zeroc/Ice/Exception.java

This also has the very nice effect of helping disambiguate `Exception`. In many places, we don't qualify this type, and it's not immediately clear whether we meant `java.lang.Exception` or `com.zeroc.Ice.Exception` (which one it actually resolves to depends on which package you're in).

Also, for what it's worth, the doc comment for `Exception` says "Base class for Ice local exceptions."
Sure sounds like it just belongs in the `LocalException` class to me.

----

Note that unlike other languages which have a single common-base for all our exceptions,
exceptions in Java are split in 2 due to the difference between checked and unchecked exceptions.

### PR DESCRIPTION
**Pull request by InsertCreativityHere**
This PR fixes #2765.

`com.zeroc.Ice.Exception` has been removed and merged into `LocalException`.

### CODE REVIEW

File: java/src/Ice/src/main/java/com/zeroc/Ice/BZip2.java [hunk 1]
```diff
@@ -24,7 +24,7 @@ public static Buffer compress(Buffer buf, int headerSize, int compressionLevel)
             //
             data = buf.b.array();
             offset = buf.b.arrayOffset();
-        } catch (java.lang.Exception ex) {
+        } catch (Exception ex) {
```
Comment (InsertCreativityHere) [inline java/src/Ice/src/main/java/com/zeroc/Ice/BZip2.java:27]: Now that there's no `Exception` class that we define, we no longer need to qualify the built in `Exception` type.

File: cpp/src/slice2java/JavaUtil.cpp [hunk 2]
```diff
@@ -483,7 +483,7 @@ namespace
                 //
                 if ((*i) == "java:getset" &&
                     (!dynamic_pointer_cast<ClassDef>(p) && !dynamic_pointer_cast<Struct>(p) &&
-                     !dynamic_pointer_cast<Slice::Exception>(p) && !dynamic_pointer_cast<DataMember>(p)))
+                     !dynamic_pointer_cast<Exception>(p) && !dynamic_pointer_cast<DataMember>(p)))
```
Comment (bernardnormier) [inline cpp/src/slice2java/JavaUtil.cpp:486]: I'd rather keep the qualification. We also have Ice::Exception and it's certainly possible to add a "using namespace Ice" in the future.

**Review by bernardnormier — APPROVED** [review]

File: cpp/src/slice2java/JavaUtil.cpp (hunk 2 above)
Comment (InsertCreativityHere) [reply cpp/src/slice2java/JavaUtil.cpp:486]: Alright I'll add it back, but just FYI we use `Exception` without qualification all over the Slice compilers.
This was the only place where we qualified it, hence why I removed the qualification (for consistency).
