### PR TITLE
CloseConnectionTimeout fix

### LINKED ISSUE #2681: Close connection timeout should report CloseTimeoutException
When close on a connection results in a connection abort because the close does not complete within CloseTimeout, the application should get a CloseTimeoutException (this exception already exists).

However, as shown in the Ice/timeout test, the application currently gets a ConnectionClosedException (= graceful connection closure).  See for example:
https://github.com/zeroc-ice/ice/blob/5797114b375ad7ac2a1829c47f1a70ad127172c4/cpp/test/Ice/timeout/AllTests.cpp#L175

 - [x] C++
 - [x] C#
 - [x] Java
 - [ ] JS

### PR DESCRIPTION
**Pull request by bernardnormier**
Revision 2:

I simplified the logic, and all the tests pass now. Implemented in C++, C# and Java. (Missing: JS).

Revision 1:
This is an attempt to fix #2681 in C#. However, it does not work with wss:

```
[ running client/server test - 08/26/24 21:06:50 ]
- Config: wss
testing async/await...ok
testing local exceptions with async tasks... ok
testing exception with async task... ok
testing progress callback... ok
testing batch requests with proxy and async tasks... ok
testing batch requests with connection... ok
testing batch requests with communicator... ok
testing async/await... ok
testing async Task cancellation... ok
testing connection close... Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
   at Ice.Internal.OutgoingAsyncBase.invokeException() in /Users/bernard/builds/ice/csharp/src/Ice/Internal/OutgoingAsync.cs:line 95
--- End of stack trace from previous location ---
   at Test.TestDriver.runTestAsync[T](String[] args) in /Users/bernard/builds/ice/csharp/test/TestCommon/TestHelper.cs:line 232
saved /Users/bernard/builds/ice/csharp/test/Ice/ami/client-082624-2106.log
saved /Users/bernard/builds/ice/csharp/test/Ice/ami/server-082624-2106.log
```

Graceful closure with the ice protocol relies on the peer closing (aborting) the transport connection. What's the correct way to map such an expected transport-level abort to a graceful closure?

See also step 5 at:
https://docs.icerpc.dev/icerpc/ice-protocol/connection-shutdown 

implemented here in IceRPC:
https://github.com/icerpc/icerpc-csharp/blob/c866c086c6e0b2064681351cf0c7c0a1b4f79d61/src/IceRpc/Internal/IceProtocolConnection.cs#L522

### CODE REVIEW

**Comment by pepone** [comment]
I cannot reproduce this wss failure in macOS

**Comment by bernardnormier** [comment]
It fails all the time for me on macos:
```
csharp % python3 allTests.py Ice/ami --protocol wss
*** [1/1] Running csharp/Ice/ami tests ***
[ running client/server test - 08/27/24 10:16:31 ]
- Config: wss
testing async/await...ok
testing local exceptions with async tasks... ok
testing exception with async task... ok
testing progress callback... ok
testing batch requests with proxy and async tasks... ok
testing batch requests with connection... ok
testing batch requests with communicator... ok
testing async/await... ok
testing async Task cancellation... ok
testing connection close... Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
   at Ice.Internal.OutgoingAsyncBase.invokeException() in /Users/bernard/builds/ice/csharp/src/Ice/Internal/OutgoingAsync.cs:line 95
--- End of stack trace from previous location ---
   at Test.TestDriver.runTestAsync[T](String[] args) in /Users/bernard/builds/ice/csharp/test/TestCommon/TestHelper.cs:line 232
saved /Users/bernard/builds/ice/csharp/test/Ice/ami/client-082724-1016.log
saved /Users/bernard/builds/ice/csharp/test/Ice/ami/server-082724-1016.log
unexpected exit status: expected: 0, got 1
```

The issue is (most likely) that the expected connection abort is not received by finishAsync, but somewhere else.

**Comment by bentoi** [comment]
> Graceful closure with the ice protocol relies on the peer closing (aborting) the transport connection.

Why abort? The protocol waits for the close connection message from the peer and the connection doesn't abort right away the transport connection. It allows the transport to perform its own graceful connection closure. That's the purpose of the transceiver "closing" method.

`Transceiver::closing` is called after the close connection message is received or after it's sent. It's only once the transceiver closing operation is done (it returns `SocketOperationNone`) that the Ice connection closes the connection.

**Comment by bernardnormier** [comment]
My understanding is the transport connection is always closed the same way, and the other side can't distinguish between a "graceful close" and an "abort" of the transport connection. It's all the same. 

In IceRPC, the IceProtocolConnection shutdown code awaits:
https://github.com/icerpc/icerpc-csharp/blob/802fd1f77ab360bf9a4261955a4bf883479afdee/src/IceRpc/Internal/IceProtocolConnection.cs#L526

and this task typically completes successfully because it gets an IceRpcError.ConnectionAborted:
https://github.com/icerpc/icerpc-csharp/blob/802fd1f77ab360bf9a4261955a4bf883479afdee/src/IceRpc/Internal/IceProtocolConnection.cs#L1254

>  It's only once the transceiver closing operation is done (it returns SocketOperationNone) that the Ice connection closes the connection.

Do you mean:
 - when transceiver.closing returns SocketOperationNone, it means the other side acknowledged the closure of the ice connection by aborting the transport connection?

**Review by pepone — COMMENTED** [review]
I find odd that getInfo would fail with `CloseTimeoutException` here. A timeout condition implies you are waiting for something, but here the getInfo caller is not waiting for the connection closure, and the connection was aborted because the close timeout.  Maybe a ConnectionAbortedException would make more sense.

**Comment by bernardnormier** [comment]
The logic is all the calls on Connection - not just getInfo - throw the exception held by Connection. And this test is really about verifying which exception is held by Connection. It's not a getInfo test.

**Review by pepone — APPROVED** [review]
Looks good

File: java/test/src/main/java/test/TestDriver.java [hunk 1]
```diff
@@ -4,13 +4,28 @@
...
       String testClass = System.getProperty("test.class");
       Class<?> c = Class.forName(testClass);
       test.TestHelper helper = (test.TestHelper) c.getDeclaredConstructor().newInstance();
+
+      // Make the test fail if a thread fails with an unhandled exception.
+      Thread.setDefaultUncaughtExceptionHandler(
+          (Thread t, Throwable e) -> {
+            PrintWriter out = helper.getWriter();
+            out.println(
+                "!!!!!!!!!!!!!!!!! unhandled exception in thread " + t.getName() + ": " + e);
```
Comment (InsertCreativityHere) [inline java/test/src/main/java/test/TestDriver.java:23]: If you want to leave these, getting rid of some will let this fit on one line
(which I think looks nicer than being broke up on 2 lines).
```suggestion
            out.println("!!!!!!!!!!! unhandled exception in thread " + t.getName() + ": " + e);
```

File: cpp/test/Ice/timeout/AllTests.cpp [hunk 2]
```diff
@@ -165,19 +165,25 @@ allTestsWithController(Test::TestHelper* helper, const ControllerPrx& controller
...
+        {
+            // Expected.
+        }
+
+        try
+        {
+            connection->getInfo();
+            test(false);
+        }
+        catch (const Ice::CloseTimeoutException& ex)
```
Comment (InsertCreativityHere) [inline cpp/test/Ice/timeout/AllTests.cpp:184]: Since we don't test `ex.closedByApplication()` anymore:
```suggestion
        catch (const Ice::CloseTimeoutException&)
```

**Review by InsertCreativityHere — APPROVED** [review]
Looks good.

File: java/src/Ice/src/main/java/com/zeroc/Ice/ConnectionI.java [hunk 3]
```diff
@@ -2282,17 +2282,13 @@ private boolean sendResponseImpl(OutputStream outputStream, boolean isTwoWay, by
             notifyAll();
           }
 
-          if (_state >= StateClosed) {
-            assert (_exception != null);
-            throw (LocalException) _exception.fillInStackTrace();
```
Comment (bernardnormier) [inline java/src/Ice/src/main/java/com/zeroc/Ice/ConnectionI.java:2287]: I find this old code very incorrect.
We were overwriting the stack trace in _exception with the current stack trace, which makes no sense.
