### PR TITLE
IceGrid/activation test fixes

### LINKED ISSUE #3447: IceGrid/activation failure on macOS
see https://github.com/zeroc-ice/ice/actions/runs/13034949544/job/36362954066?pr=3444

I recently fixed the test to not ignore this state errors in https://github.com/zeroc-ice/ice/issues/2117

### PR DESCRIPTION
**Pull request by pepone**
Fix #3447

### CODE REVIEW

File: cpp/test/IceGrid/activation/AllTests.cpp [hunk 1]
```diff
@@ -680,22 +680,24 @@ allTests(Test::TestHelper* helper)
...
+                break;
             }
             catch (const Ice::NoEndpointException&)
             {
+                this_thread::sleep_for(chrono::milliseconds(500));
+                continue;
             }
         }
         test(admin->isServerEnabled("server2"));
         waitForServerState(admin, "server2", IceGrid::ServerState::Active);
```
Comment (pepone) [inline cpp/test/IceGrid/activation/AllTests.cpp:700]: With the previous code, we can exit the loop after getting NoEndpointException if the server just get enabled before we send the next `ice_ping` request.

In this situation `waitForServerState` would hang as there is no request activating the server.

File: cpp/test/IceGrid/activation/AllTests.cpp [hunk 2]
```diff
@@ -680,22 +680,24 @@ allTests(Test::TestHelper* helper)
...
-        obj->ice_ping();
```
Comment (pepone) [inline cpp/test/IceGrid/activation/AllTests.cpp:698]: This `ice_ping` request after the server is already activate and before is stopped doesn't make sense. Maybe it was mean to be done before the `waitForServerState`.

File: cpp/test/IceGrid/activation/AllTests.cpp [hunk 3]
```diff
@@ -680,22 +680,24 @@ allTests(Test::TestHelper* helper)
...
-            ++nRetry;
             try
             {
                 obj->ice_ping();
+                break;
             }
             catch (const Ice::NoEndpointException&)
             {
+                this_thread::sleep_for(chrono::milliseconds(500));
+                continue;
```
Comment (externl) [inline cpp/test/IceGrid/activation/AllTests.cpp:696]: Is this continue necessary?

**Review by externl — APPROVED** [review]

File: cpp/test/IceGrid/activation/AllTests.cpp (hunk 3 above)
Comment (pepone) [reply cpp/test/IceGrid/activation/AllTests.cpp:696]: N. we can remove it.

**Review by bernardnormier — APPROVED** [review]
