### PR TITLE
Fix throwing of NotExist exceptions

### LINKED ISSUE #2971: Review ObjectNotExistException usage
The caller doesn't need to fill the id, facet, and operation. For example:

```
IceGrid/AdminSessionI.cpp
147:        throw Ice::ObjectNotExistException(__FILE__, __LINE__, current.id, "", "");
210:        throw Ice::ObjectNotExistException(__FILE__, __LINE__, current.id, "", "");
```

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR fixes the throwing of ObjectNotExistException, FacetNotExistException and OperationNotExistException.

Most of the time, you don't need to / should not specify id/facet/operation as they are filled-in automatically when the exception is encoded.

Fixes #2971.

### CODE REVIEW

File: cpp/src/Glacier2/ClientBlobject.cpp [hunk 1]
```diff
@@ -77,13 +77,9 @@ Glacier2::ClientBlobject::ice_invokeAsync(
...
     if (!proxy)
     {
-        //
-        // We use a special operation name indicate to the client that
-        // the proxy for the Ice object has not been found in our
-        // routing table. This can happen if the proxy was evicted
-        // from the routing table.
-        //
-        throw ObjectNotExistException(__FILE__, __LINE__, current.id, current.facet, "ice_add_proxy");
+        // We use a special operation name indicate to the client that the proxy for the Ice object has not been found
```
Comment (pepone) [inline cpp/src/Glacier2/ClientBlobject.cpp:80]:
```suggestion
        // We use a special operation name to indicate to the client that the proxy for the Ice object has not been found
```

**Review by pepone — APPROVED** [review]

**Review by externl — APPROVED** [review]
