### PR TITLE
Run ice2slice on CI

### LINKED ISSUE #3351: Run `ice2slice` in CI
It would be good to have at least some kind of testing for `ice2slice` run in CI.
Even just running it over the `./slice` directory would be good enough I think.

Because right now, where we have 0 testing of this tool, it's too east to accidentally break and not notice.
As shown from the fact that it was broken for months without anyone noticing until #3290.

### PR DESCRIPTION
**Pull request by pepone**
Fix #3351

### CODE REVIEW

File: cpp/src/ice2slice/Main.cpp [hunk 1]
```diff
@@ -113,6 +113,10 @@ compile(const vector<string>& argv)
     bool preprocess = opts.isSet("E");
 
     string outputDir = opts.optArg("output-dir");
+    if (outputDir.empty())
```
Comment (pepone) [inline cpp/src/ice2slice/Main.cpp:116]: This was broken, not emitting any files when you don't specify the output dir. But the compiler din't give any errors, which seems odd.

**Review by externl — APPROVED** [review]

File: cpp/src/ice2slice/Main.cpp (hunk 1 above)
Comment (InsertCreativityHere) [reply cpp/src/ice2slice/Main.cpp:116]: Huh, that's a little weird. It just passes this into `libSlice`, so there could be something weird going on downstream.
I'll take a peek at it later.

**Review by InsertCreativityHere — APPROVED** [review]
