### PR TITLE
Disable colloc optimization for datagram endpoints

### LINKED ISSUE #4142: java/test/IceDiscovery/simple failure on Ubuntu
From https://github.com/zeroc-ice/ice/actions/runs/15837533211/job/44644034846?pr=4141

```
(/opt/hostedtoolcache/Java_Oracle_jdk/17/x64/bin/java -ea -Djdk.net.URLClassPath.disableClassPathURLCheck=true -Dtest.class=test.IceDiscovery.simple.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=/home/runner/work/ice/ice/certs/common/ca --IceSSL.Keystore=client.p12 --IceSSL.KeystorePassword=password --IceSSL.KeystoreType=PKCS12 --IceSSL.Truststore=ca.p12 --IceSSL.TruststorePassword=password --IceSSL.TruststoreType=PKCS12 --IceDiscovery.Timeout=50 --IceDiscovery.RetryCount=20 --IceDiscovery.DomainId=abbf0610-e8fb-4c73-8ea0-6eb467fbef9c --IceDiscovery.Interface= --IceDiscovery.Port=14110 --Ice.Plugin.IceDiscovery=com.zeroc.IceDiscovery.PluginFactory --Ice.ProgramName=client --Ice.Trace.Locator=2 --Ice.Trace.Protocol=1 --Ice.Trace.Network=3 --Ice.LogFile=/home/runner/work/ice/ice/java/test/src/main/java/test/IceDiscovery/simple/client-062425-0019.log 3 env={'CLASSPATH': '/home/runner/work/ice/ice/java/lib/test.jar'})
testing indirect proxies... ok
testing well-known proxies... ok
testing object adapter registration... ok
testing object adapter migration...ok
testing object migration...ok
testing replica groups...ok
testing invalid lookup endpoints... com.zeroc.Ice.NoEndpointException: No suitable endpoint available for proxy 'controller0 @ control0'
	at com.zeroc.Ice.OutgoingAsync.waitForResponseOrUserEx(OutgoingAsync.java:104)
	at com.zeroc.Ice.OutgoingAsync.waitForResponse(OutgoingAsync.java:91)
	at com.zeroc.Ice._ObjectPrxI.ice_ping(_ObjectPrxI.java:63)
	at com.zeroc.Ice._ObjectPrxI.ice_ping(_ObjectPrxI.java:59)
	at test.IceDiscovery.simple.AllTests.allTests(AllTests.java:227)
	at test.IceDiscovery.simple.Client.run(Client.java:24)
	at test.TestDriver.main(TestDriver.java:26)
saved /home/runner/work/ice/ice/java/test/src/main/java/test/IceDiscovery/simple/client-062425-0019.log
saved /home/runner/work/ice/ice/java/test/src/main/java/test/IceDiscovery/simple/server2-062425-0019.log
saved /home/runner/work/ice/ice/java/test/src/main/java/test/IceDiscovery/simple/server1-062425-0019.log
saved /home/runner/work/ice/ice/java/test/src/main/java/test/IceDiscovery/simple/server0-062425-0019.log

```

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR disables colloc optimization for datagram (UDP) endpoints. It also removes the various spot where we called `ice_collocationOptimized(false)` on multicast proxies.

Fixes #4142, indirectly.

### CODE REVIEW

File: cpp/src/IceStorm/Subscriber.cpp [hunk 1]
```diff
@@ -296,7 +296,7 @@ namespace
     SubscriberLink::SubscriberLink(const shared_ptr<Instance>& instance, const SubscriberRecord& rec)
         : Subscriber(instance, rec, nullopt, -1, 1),
           _obj(Ice::uncheckedCast<TopicLinkPrx>(
-              rec.obj->ice_collocationOptimized(false)->ice_invocationTimeout(instance->sendTimeout())))
+              rec.obj->ice_invocationTimeout(instance->sendTimeout())))
```
Comment (pepone) [inline cpp/src/IceStorm/Subscriber.cpp]: Dos `rec.obj` only use datagram?

**Review by pepone — APPROVED** [review]

File: cpp/src/Ice/ObjectAdapterI.cpp [hunk 2]
```diff
@@ -676,13 +676,18 @@ Ice::ObjectAdapterI::isLocal(const ReferencePtr& ref) const
         checkForDestruction();
 
         // Proxies which have at least one endpoint in common with the published endpoints are considered local.
+        // This check doesn't take datagram endpoints into account; this effectively disables colloc optimization
```
Comment (externl) [inline cpp/src/Ice/ObjectAdapterI.cpp:679]: It would be good to say why we do this, not just that we're doing it.

**Review by externl — APPROVED** [review]
Looks good. We should say why though.

File: cpp/src/IceStorm/Subscriber.cpp (hunk 1 above)
Comment (bernardnormier) [reply cpp/src/IceStorm/Subscriber.cpp]: Probably not. 

Subscribers are never collocated with IceStorm (except possibly when loaded by IceGrid). So we used to turn-off colloc optimization to avoid incorrect colloc with UDP endpoints (primarily multicast UDP). This PR makes this turn-off unnecessary.

File: cpp/src/Ice/ObjectAdapterI.cpp (hunk 2 above)
Comment (bernardnormier) [reply cpp/src/Ice/ObjectAdapterI.cpp:679]: I updated the CHANGELOG.
