### PR TITLE
Fix for DataStorm session retries

### LINKED ISSUE #4231: DataStorm/reliability failure
https://github.com/zeroc-ice/ice/actions/runs/16464928429/job/46539916125

[test-logs-cpp-win32-release-windows-2022.zip](https://github.com/user-attachments/files/21685276/test-logs-cpp-win32-release-windows-2022.zip)

### PR DESCRIPTION
**Pull request by pepone**
Fix #4231

### CODE REVIEW

File: cpp/src/DataStorm/NodeI.cpp [hunk 1]
```diff
@@ -458,6 +458,24 @@ NodeI::retrySubscriberSessionCreation(
...
 {
+    try
+    {
+        rethrow_exception(ex);
+    }
+    catch (const SessionCreationException& sessionCreationException)
+    {
+        if (sessionCreationException.error == SessionCreationError::AlreadyConnected && session->checkSession())
+        {
+            // A concurrent session attempt from the peer succeeded, no need to retry.
```
Comment (pepone) [inline cpp/src/DataStorm/NodeI.cpp:471]: In this case both peers are seeing the session as connected.

- This node Session::checkSession returns true, meaning it is already connected.
- The peer node just throw `SessionCreationException` with `AlreadyConnected` error code.

There is no need to keep retrying, and if we keep the retries will keep failing with already connected and the session will be destroyed when the retry limit is hit.

**Review by bernardnormier — APPROVED** [review]
