### PR TITLE
Fix sendHeartbeat in C++, C# and Java

### LINKED ISSUE #2868: Send heartbeats when connection state is StateClosing
We currently send heartbeats only when the connection state is StateActive or StateHolding:

https://github.com/zeroc-ice/ice/blob/9ab4adbe63adacacc0ed523e7ba0e6c2108cbec4/csharp/src/Ice/ConnectionI.cs#L1499

We should also send them in StateClosing.

Scenario:
  - in server, communicator shutdown transitions the state of an incoming connection to StateClosing:
 https://github.com/zeroc-ice/ice/blob/9ab4adbe63adacacc0ed523e7ba0e6c2108cbec4/csharp/src/Ice/ConnectionI.cs#L150

  - connection does not transition to StateClosingPending because there are outstanding upcalls (e.g. dispatches):
 https://github.com/zeroc-ice/ice/blob/9ab4adbe63adacacc0ed523e7ba0e6c2108cbec4/csharp/src/Ice/ConnectionI.cs#L1786

  - new client requests get discarded, with no responses
 https://github.com/zeroc-ice/ice/blob/9ab4adbe63adacacc0ed523e7ba0e6c2108cbec4/csharp/src/Ice/ConnectionI.cs#L2322

The logic here is once upcalls in the server connection reach 0, we call initiateShutdown which sends a CloseConnection frame and transitions to StateClosingPending when done:
https://github.com/zeroc-ice/ice/blob/9ab4adbe63adacacc0ed523e7ba0e6c2108cbec4/csharp/src/Ice/ConnectionI.cs#L1826
or
https://github.com/zeroc-ice/ice/blob/9ab4adbe63adacacc0ed523e7ba0e6c2108cbec4/csharp/src/Ice/ConnectionI.cs#L2109

However, this can take a while, and during this time, the server connection should keep sending heartbeats to the client connection.

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR fixes #2868 in C++, C# and Java.

The JS code is different with no StateClosingPending state, so fixing JS is not as simple.

### CODE REVIEW

File: java/src/Ice/src/main/java/com/zeroc/Ice/ConnectionI.java [hunk 1]
```diff
@@ -1215,21 +1214,13 @@ public synchronized void sendHeartbeat() {
...
-            // send a heartbeat. It's possible the first message of _sendStreams was already
-            // sent
-            // but
-            // not yet removed from _sendStreams: it means the last write occurred very
-            // recently,
-            // which is good enough with respect to the idle check.
+            // write in turns creates a read on the peer, and resets the peer's idle check timer.
+            // When _sendStream is not empty, there is already an outstanding write, so we don't
+            // need to send a heartbeat. It's possible the first message of _sendStreams was
+            // already sent but  not yet removed from _sendStreams: it means the last write
```
Comment (InsertCreativityHere) [inline java/src/Ice/src/main/java/com/zeroc/Ice/ConnectionI.java:1220]: Extra space hiding here.
```suggestion
            // already sent but not yet removed from _sendStreams: it means the last write
```

**Review by InsertCreativityHere — APPROVED** [review]
Looks good to me.

**Comment by pepone** [comment]
>  The JS code is different with no StateClosingPending state, so fixing JS is not as simple.

The issue only mentions server connections, and there is no server connections (incoming connections) in JS.

**Review by pepone — APPROVED** [review]

**Review by externl — APPROVED** [review]
