### PR TITLE
Fix doc-comment for Communicator destroy, shutdown and related methods

### LINKED ISSUE #2561: Improve Communicator destroy doc comments
(Not from this PR). I find the description misleading. We should never use "shut down the communicator's client functionality". Shut down is only about server-side functionality.

_Originally posted by @bernardnormier in https://github.com/zeroc-ice/ice/pull/2554#discussion_r1689812343_

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixed #2561.

### CODE REVIEW

File: matlab/lib/+Ice/Communicator.m [hunk 1]
```diff
@@ -113,8 +113,8 @@ function destroy(obj)
         end
 
         function f = destroyAsync(obj)
-            %DESTROYASYNC Asynchronously destroys the communicator. Calling destroyAsync cleans up memory, and shuts
-            %   down this communicator's client functionality. Subsequent calls to destroyAsync are ignored.
+            %DESTROYASYNC Asynchronously destroys the communicator.
```
Comment (bernardnormier) [inline matlab/lib/+Ice/Communicator.m:116]: Not clear why we provide this destroyAsync in MATLAB. It should always complete synchronously. Maybe we should remove it?

**Review by externl — APPROVED** [review]

File: java/src/com.zeroc.ice/src/main/java/com/zeroc/Ice/Communicator.java [hunk 2]
```diff
@@ -5,6 +5,7 @@
 import com.zeroc.Ice.Instrumentation.CommunicatorObserver;
 import com.zeroc.Ice.SSL.SSLEngineFactory;
 
+import java.security.Identity;
```
Comment (pepone) [inline java/src/com.zeroc.ice/src/main/java/com/zeroc/Ice/Communicator.java]: This import looks bogus, probably added by Visual Studio Code.

File: js/src/Ice/Communicator.d.ts [hunk 3]
```diff
@@ -11,8 +11,10 @@ declare module "@zeroc/ice" {
          */
         interface Communicator {
             /**
-             * Destroy the communicator. This operation calls {@link Communicator#shutdown} implicitly. Calling {@link Communicator#destroy} cleans up
-             * memory, and shuts down this communicator's client functionality and destroys all object adapters.
+             * Destroys this communicator. This method calls {@link Communicator#shutdown} implicitly. Calling
+             * {@link Communicator#destroy} destroys all object adapters, and closes all outgoing connections. `destroy`
+             * waits for all outstanding dispatches to complete before returning. This includes "bidirectional
```
Comment (pepone) [inline js/src/Ice/Communicator.d.ts]: In JavaScript the method is async, doesn't wait before returning.

**Review by pepone — APPROVED** [review]

File: js/src/Ice/Communicator.d.ts (hunk 3 above)
Comment (bernardnormier) [reply js/src/Ice/Communicator.d.ts]: Fixed.

File: java/src/com.zeroc.ice/src/main/java/com/zeroc/Ice/Communicator.java (hunk 2 above)
Comment (bernardnormier) [reply java/src/com.zeroc.ice/src/main/java/com/zeroc/Ice/Communicator.java]: Fixed
