### PR TITLE
Fix IceGrid/activation test failure

### LINKED ISSUE #2117: Extra output in cpp/IceGrid/activation test. May indicate silent test failure.
When running the tests locally I noticed this odd output. At first I thought it was recently leftover debugging output. But it looks like it's been there for a while and may be indicating at a test is silently failing.

https://github.com/zeroc-ice/ice/blob/28a2e29cd08a76fefab83075da4532cb59fab74d/cpp/test/IceGrid/activation/AllTests.cpp#L25-L30

```
*** [68/85] Running cpp/IceGrid/activation tests ***
[ running IceGrid test - 05/06/24 11:31:17 ]
- Config: ssl,mx
starting IceGrid registry Master... ok
starting IceGrid registry Slave1... ok
starting IceGrid node localnode... ok
testing on-demand activation... ok
testing manual activation... ok
testing always activation... ok
testing session activation... ok
testing server disable... ok
testing server enable... ok
testing activation failure... ok
testing activation timeout... ok
testing deactivation timeout... ok
testing permanent disable on failure... server state change timed out:
server: server1
state: 3
ok
```

I didn't look closely it could also be related to the recent removal of ACM and the addition of the new idle and timeout settings. Maybe we just need to update the test.

### PR DESCRIPTION
**Pull request by pepone**
Fix #2117

### CODE REVIEW

File: cpp/test/IceGrid/activation/AllTests.cpp [hunk 1]
```diff
@@ -610,6 +615,7 @@ allTests(Test::TestHelper* helper)
     {
         test(admin->getServerState("server1") == IceGrid::ServerState::Inactive);
         TestIntfPrx obj(communicator, "server1");
```
Comment (pepone) [inline cpp/test/IceGrid/activation/AllTests.cpp:617]: The 3.7 version has a checkedCast, and ice_isA request triggers the activation.

**Review by externl — APPROVED** [review]
