### PR TITLE
Fix Swift LocalObject.mm assert

### LINKED ISSUE #3064: Swift local object cache assertion
```
2024-11-05T01:16:45.9302440Z Assertion failed: (p != cachedObjects->end()), function -[ICELocalObject dealloc], file LocalObject.mm, line 70.
```

see https://github.com/zeroc-ice/ice/actions/runs/11674569241/job/32507500860

### PR DESCRIPTION
**Pull request by externl**
Closes #3064

### CODE REVIEW

File: swift/src/IceImpl/LocalObject.mm [hunk 1]
```diff
@@ -64,23 +64,24 @@ - (void)dealloc
...
+            {
+                cachedObjects->erase(p);
+            }
 
-        // When the last reference on this object is released, p->second is nil and we remove the stale entry from the
-        // cache.
-        if (p->second == nil)
-        {
-            cachedObjects->erase(p);
+            _cppObject = nullptr;
```
Comment (bernardnormier) [inline swift/src/IceImpl/LocalObject.mm:83]: This "reset" should be outside the `if` block or not there at all.

File: swift/src/IceImpl/LocalObject.mm [hunk 2]
```diff
@@ -64,23 +64,24 @@ - (void)dealloc
...
         assert(_cppObject != nullptr);
-        auto p = cachedObjects->find(_cppObject.get());
 
-        // There is necessarily an entry in the cache for this address.
-        assert(p != cachedObjects->end());
+        // Find the object in the cache. If it's not there, it's likely that another thread already replaced
+        // the object with a new one and then that new one was quickly deallocated.
+        if (auto p = cachedObjects->find(_cppObject.get()); p != cachedObjects->end())
+        {
+            // The object in the cache is either nil or NOT current object. The later can happen if this thread was
```
Comment (bernardnormier) [inline swift/src/IceImpl/LocalObject.mm:72]: NOT the current object

**Review by bernardnormier — APPROVED** [review]

**Review by pepone — APPROVED** [review]
