### PR TITLE
Fix segfault accessing null pointer in IceGrid node updateRevision

### LINKED ISSUE #4547: IceGrid/update test failure (Windows)
From https://github.com/zeroc-ice/ice/actions/runs/18516434747/job/52767615729?pr=4545:

```
*** [81/96] Running cpp/IceGrid/update tests ***
[ running IceGrid test - 10/15/25 03:19:57 ]
- Config: ssl,mx,x64,Debug
starting IceGrid registry Master... (D:\a\ice\ice\cpp\bin\x64\Debug\icegridregistry.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=0 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs/common/ca --IceSSL.CAs=ca_cert.pem --IceSSL.CertFile=server.p12 --Ice.PrintStackTraces=1 --IceGrid.InstanceName=TestIceGrid --IceGrid.Registry.PermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.AdminPermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.SSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.AdminSSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.Server.Endpoints=default --IceGrid.Registry.Internal.Endpoints=default --IceGrid.Registry.Client.Endpoints="default -p 14220" --IceGrid.Registry.Discovery.Port=14299 --IceGrid.Registry.SessionManager.Endpoints=default --IceGrid.Registry.AdminSessionManager.Endpoints=default --IceGrid.Registry.ReplicaName=Master --Ice.ProgramName=Master --Ice.PrintAdapterReady=1 --Ice.ThreadPool.Client.SizeWarn=0 --IceGrid.Registry.LMDB.MapSize=1 --IceGrid.Registry.LMDB.Path=D:\a\ice\ice\cpp\test\IceGrid\update/registry-Master --IceGrid.Registry.Client.ThreadPool.SizeWarn=0 --IceGrid.Registry.DefaultTemplates="D:\a\ice\ice\cpp\config\templates.xml" --IceGrid.Registry.Discovery.Interface=127.0.0.1 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
ok
starting IceGrid registry Slave1... (D:\a\ice\ice\cpp\bin\x64\Debug\icegridregistry.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=0 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs/common/ca --IceSSL.CAs=ca_cert.pem --IceSSL.CertFile=server.p12 --Ice.PrintStackTraces=1 --IceGrid.InstanceName=TestIceGrid --IceGrid.Registry.PermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.AdminPermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.SSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.AdminSSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.Server.Endpoints=default --IceGrid.Registry.Internal.Endpoints=default --IceGrid.Registry.Client.Endpoints="default -p 14221" --IceGrid.Registry.Discovery.Port=14299 --IceGrid.Registry.SessionManager.Endpoints=default --IceGrid.Registry.AdminSessionManager.Endpoints=default --IceGrid.Registry.ReplicaName=Slave1 --Ice.ProgramName=Slave1 --Ice.PrintAdapterReady=1 --Ice.ThreadPool.Client.SizeWarn=0 --IceGrid.Registry.LMDB.MapSize=1 --IceGrid.Registry.LMDB.Path=D:\a\ice\ice\cpp\test\IceGrid\update/registry-Slave1 --IceGrid.Registry.Client.ThreadPool.SizeWarn=0 --IceGrid.Registry.DefaultTemplates="D:\a\ice\ice\cpp\config\templates.xml" --IceGrid.Registry.Discovery.Interface=127.0.0.1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14220" env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
ok
starting IceGrid node localnode... (D:\a\ice\ice\cpp\bin\x64\Debug\icegridnode.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs/common/ca --IceSSL.CAs=ca_cert.pem --IceSSL.CertFile=server.p12 --Ice.PrintStackTraces=1 --IceGrid.InstanceName=TestIceGrid --IceGrid.Node.Endpoints=default --IceGrid.Node.WaitTime=240 --Ice.ProgramName=icegridnode --IceGrid.Node.Trace.Replica=0 --IceGrid.Node.Trace.Activator=0 --IceGrid.Node.Trace.Adapter=0 --IceGrid.Node.Trace.Server=0 --IceGrid.Node.ThreadPool.SizeWarn=0 --IceGrid.Node.PrintServersReady=node --IceGrid.Node.Name=localnode --IceGrid.Node.Data=D:\a\ice\ice\cpp\test\IceGrid\update/node-localnode --IceGrid.Node.PropertiesOverride="Ice.Default.Host=127.0.0.1 Test.BasePort=14200 Ice.Warn.Connections=1 Ice.Default.Protocol=ssl Ice.IPv6=0 Ice.Admin.Endpoints=\"tcp -h 127.0.0.1\" Ice.Admin.InstanceName=Server IceMX.Metrics.Debug.GroupBy=id IceMX.Metrics.Parent.GroupBy=parent IceMX.Metrics.All.GroupBy=none IceSSL.*** IceSSL.DefaultDir=D:\\a\\ice\\ice\\certs/common/ca IceSSL.CAs=ca_cert.pem IceSSL.CertFile=server.p12 Ice.PrintStackTraces=1 Ice.PrintAdapterReady=1" --Ice.Default.Locator="TestIceGrid/Locator:default -p 14220:default -p 14221" env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
ok
(D:\a\ice\ice\cpp\test\IceGrid\update\msbuild\client\x64\Debug\client.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs/common/ca --IceSSL.CAs=ca_cert.pem --IceSSL.CertFile=client.p12 --Ice.PrintStackTraces=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14220" --NodePropertiesOverride="Ice.Default.Host=127.0.0.1 Test.BasePort=14200 Ice.Warn.Connections=1 Ice.Default.Protocol=ssl Ice.IPv6=0 Ice.Admin.Endpoints=\"tcp -h 127.0.0.1\" Ice.Admin.InstanceName=Server IceMX.Metrics.Debug.GroupBy=id IceMX.Metrics.Parent.GroupBy=parent IceMX.Metrics.All.GroupBy=none IceSSL.*** IceSSL.DefaultDir=D:\\a\\ice\\ice\\certs/common/ca IceSSL.CAs=ca_cert.pem IceSSL.CertFile=server.p12 Ice.PrintStackTraces=1 Ice.PrintAdapterReady=1" --IceBoxExe=D:\a\ice\ice\cpp\bin\x64\Debug\icebox.exe --IceGridNodeExe=D:\a\ice\ice\cpp\bin\x64\Debug\icegridnode.exe --ServerDir=msbuild\server\x64\Debug --TestDir=D:\a\ice\ice\cpp\test\IceGrid\update env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
testing server add... ok
testing server remove... ok
testing server update... ok
testing icebox server add... ok
testing service add... ok
testing service remove... ok
testing node add... ok
testing node update... ok
testing node remove... ok
testing variable update... ok
testing property set update... ok
testing description update... ok
testing server node move... error: class IceGrid::NodeUnreachableException ::IceGrid::NodeUnreachableException
(D:\a\ice\ice\cpp\bin\x64\Debug\icegridadmin.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs/common/ca --IceSSL.CAs=ca_cert.pem --IceSSL.CertFile=client.p12 --Ice.PrintStackTraces=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14220" --IceGridAdmin.Username=admin1 --IceGridAdmin.*** -r Master -e "node shutdown localnode" env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
error: node 'localnode' couldn't be reached:
the node is not active
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #4547

### CODE REVIEW

File: cpp/src/IceGrid/ServerI.cpp [hunk 1]
```diff
@@ -2440,24 +2440,31 @@ ServerI::checkAndUpdateUser(const shared_ptr<InternalServerDescriptor>& desc, bo
...
+        desc->revision = revision;
     }
 
     string idFilePath = _serverDir + "/revision";
     ofstream os(IceInternal::streamFilename(idFilePath).c_str()); // idFilePath is a UTF-8 string
     if (os.good())
     {
         os << "#" << endl;
-        os << "# This server belongs to the application '" << _desc->application << "'" << endl;
+        os << "# This server belongs to the application '" << desc->application << "'" << endl;
```
Comment (externl) [inline cpp/src/IceGrid/ServerI.cpp]: I'm not quite following. Can't desc be null here still?

Comment (pepone) [reply cpp/src/IceGrid/ServerI.cpp]: This is just inside `updateRevision` writing the revision file, if it was null before, it will still be null. This method doesn't update `_desc`.

Comment (externl) [reply cpp/src/IceGrid/ServerI.cpp]: But it `_load` is `false`, then `desc` will be `nullptr`. This deference will crash.

Comment (pepone) [reply cpp/src/IceGrid/ServerI.cpp]: _desc is set if already loaded.
_load is set if loading.

We don't call this method if neither is set, I will add an assert.

Comment (pepone) [reply cpp/src/IceGrid/ServerI.cpp]: see:

```
    auto d = _load ? _load->getInternalServerDescriptor() : _desc;
    if (d && (replicaName != "Master" || d->sessionId == desc->sessionId) && !descriptorUpdated(d, desc))
    {
        if (d->revision != desc->revision)
        {
            updateRevision(desc->uuid, desc->revision);
        }
```

The `if (d &&` ensures either `_load` or `_desc` is set.

Next call is: 

```
_load->addCallback(response, exception); // Must be called before startRuntimePropertiesUpdate!
updateRevision(desc->uuid, desc->revision);
```

Here `_load` is set.

The third call hasppens inside updateImpl and both are set in this case:

```
void
ServerI::updateImpl(const shared_ptr<InternalServerDescriptor>& descriptor)
{
    assert(_load && descriptor);

    _desc = descriptor;
    _waitForReplication = true;

    // Remember if the server was just released by a session, this will be used later to not update the configuration
    // on the disk (as an optimization and to allow users to review the configuration file after allocating a server --
    // that's useful if the server configuration is bogus and the session server can't start).
    bool serverSessionReleased = _desc && _desc->activation == "session" && _desc->revision == descriptor->revision &&
                                 !_desc->sessionId.empty() && descriptor->sessionId.empty();
```

File: cpp/src/IceGrid/ServerI.cpp [hunk 2]
```diff
@@ -2440,24 +2440,34 @@ ServerI::checkAndUpdateUser(const shared_ptr<InternalServerDescriptor>& desc, bo
 void
 ServerI::updateRevision(const string& uuid, int revision)
 {
-    _desc->uuid = uuid;
-    _desc->revision = revision;
+    // We must have either _desc or _load.
+    assert(_desc || _load);
+
+    // _desc can be nullptr if the server initial load didn't complete yet.
+    shared_ptr<InternalServerDescriptor> desc = _desc;
```
Comment (bernardnormier) [inline cpp/src/IceGrid/ServerI.cpp]: I find this helper desc (a shared_ptr) pretty confusing. You're still updating _desc when it's not null.
And when _load is set, you are updating load's internal server descriptor (not the greatest API).

What about avoiding this desc helper and writing instead something like:
```cpp
string application;

if (_desc)
{
    _desc->uuid = uuid;
    _desc->revision = revision;
    application = _desc->application;
}

if (_load)
{
    _load->getInternalServerDescriptor()->uuid = uuid;
    _load->getInternalServerDescriptor()->revision = revision;
  
    // When both _desc and _load are not null, this one prevails.
    application = _load->getInternalServerDescriptor()->application;
}
```

and then use application, uuid and revision in the code below?

**Review by bernardnormier — APPROVED** [review]

**Review by bernardnormier — APPROVED** [review]
