### PR TITLE
Enforce fixed names for Ice plug-ins

### LINKED ISSUE #3844: Plug-in name
In Ice, the name of a plug-in is traditionally the name after `Ice.Plugin.` in configuration. This name can be anything.

For example, all the following entries load the IceDiscovery plug-in:
```
Ice.Plugin.Discovery = ...discovery plug-in spec
Ice.Plugin.IceDiscovery = ...discovery plug-in spec
Ice.Plugin.FooDiscovery = ...discovery plug-in spec
```

This flexibility allows us to load multiple instances of the same plug-in a communicator.

However, no plug-in provided with Ice takes advantage of this feature. All the plug-ins are singletons, and it's not meaningful to install multiple copies in the same communicator (with different names).  Worse, the plug-in implementations typically don't handle well such accidental installation, made possible by the flexible Ice.Plugin.name feature.

Related issue: #2798.

Even though plug-in names are flexible and user-specified, each plug-in has a default/preferred name. That's the name registered by the Ice::registerXxx function in Ice 3.7. With #3842, that's the `pluginName` provided by each proxy factory.

## Issue

Because of the plug-in name flexibility, you can fairly easily get into the situation where you load multiple instances of the same plug-in. For example, you specify:
```cpp
initData.pluginFactories = {Ice::discoveryPluginFactory()};
```
which uses the plug-in name "IceDiscovery", and you also configure:

```
Ice.Plugin.Discovery = ...discovery plug-in spec
```

In some cases, it may be hard to detect as we currently "reject" duplicate transport registrations through asserts.

https://github.com/zeroc-ice/ice/blob/52b0dad35395079ac9f39664bdd32f1cb843680f/cpp/src/Ice/EndpointFactoryManager.cpp#L38

## Proposal

For all singleton plug-ins (all Ice-provided plug-ins so far), the plug-in name as provided by the plug-in factory is the only allowed name. 

If you give the proxy factory function another name, you get a `PluginInitializationException`.

This way, each singleton plug-in can easily ensure only one instance is ever created in a communicator.

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #3844

### CODE REVIEW

File: cpp/src/Ice/SSL/SSLEndpointI.cpp [hunk 1]
```diff
@@ -12,10 +12,32 @@ using namespace std;
 using namespace Ice;
 using namespace Ice::SSL;
 
+namespace
+{
+    const char* const sslPluginName = "IceSSL";
+}
+
 extern "C"
```
Comment (pepone) [inline cpp/src/Ice/SSL/SSLEndpointI.cpp:20]: I wonder if there is any point in keeping `extern "C"`for SSL, which is always loaded from Ice library. The only use case I see is if you were loading IceSSL with a different name (not clear this worked) you will now get this error. Otherwise the plug-in is already registered and no need for extern C.

File: cpp/src/Ice/UdpEndpointI.cpp [hunk 2]
```diff
@@ -15,10 +15,32 @@ using namespace std;
 using namespace Ice;
 using namespace IceInternal;
 
+namespace
+{
+    const char* const udpPluginName = "IceUDP";
+}
+
 extern "C"
```
Comment (pepone) [inline cpp/src/Ice/UdpEndpointI.cpp:23]: Here this is only for static libraries, extern C seems not relevant. You either use a dynamic Ice build and this is loaded, or you use a static library and you have to use the factory to register it. I assuming extern "C" here is only relevant for dlsym and similar mechanism, where we want to avoid name mangling. That applies to TPC/WS too.

File: cpp/src/IceDiscovery/PluginI.cpp [hunk 3]
```diff
@@ -9,19 +9,41 @@
...
-createIceDiscovery(const Ice::CommunicatorPtr& communicator, const string&, const Ice::StringSeq&)
+createIceDiscovery(const Ice::CommunicatorPtr& communicator, const string& name, const Ice::StringSeq&)
 {
+    string pluginName{discoveryPluginName};
+
+    if (name != pluginName)
+    {
+#ifdef _MSC_VER
+#    pragma warning(push)
+#    pragma warning(disable : 4297) // function assumed not to throw an exception but does
```
Comment (pepone) [inline cpp/src/IceDiscovery/PluginI.cpp:29]: Maybe mention `VC++ assumes extern "C" function ....`

**Review by pepone — APPROVED** [review]

File: CHANGELOG-3.8.md [hunk 4]
```diff
@@ -206,6 +206,9 @@ classDiagram
   New local exceptions:\
   ConnectionAbortedException, ConnectionClosedException, ParseException
 
+- The plug-ins provided by Ice have now fixed names: IceIAP, IceBT, IceUDP, IceWS, IceDiscovery, IceLocatorDiscovery.
```
Comment (externl) [inline CHANGELOG-3.8.md:209]:
```suggestion
- The plug-ins provided by Ice now have fixed names: IceIAP, IceBT, IceUDP, IceWS, IceDiscovery, IceLocatorDiscovery.
```

**Review by externl — APPROVED** [review]

File: cpp/src/Ice/SSL/SSLEndpointI.cpp (hunk 1 above)
Comment (bernardnormier) [reply cpp/src/Ice/SSL/SSLEndpointI.cpp]: Fixed as suggested: the built-in plug-in functions for tcp, ssl, udp, ws and iap are no longer extern "C".

File: cpp/src/Ice/TcpEndpointI.cpp [hunk 5]
```diff
@@ -21,16 +21,34 @@ using namespace std;
 using namespace Ice;
 using namespace IceInternal;
 
-extern "C"
+namespace
 {
-    Plugin* createIceTCP(const CommunicatorPtr& c, const string&, const StringSeq&)
+    const char* const tcpPluginName = "IceTCP";
+
+    Plugin* createIceTCP(const CommunicatorPtr& c, const string& name, const StringSeq&)
```
Comment (bernardnormier) [inline cpp/src/Ice/TcpEndpointI.cpp:28]: It's now a regular C++ function in the anonymous namespace.

**Review by externl — APPROVED** [review]
Looks good!

**Review by pepone — APPROVED** [review]
