### PR TITLE
Replace sprintf/vsprintf with snprintf/vsnprintf

### LINKED ISSUE #1368: C++ build failure on macOS Ventura: deprecated sprintf
```
src/IceUtil/OutputUtil.cpp:38:5: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
    sprintf(buf, "%ld", val); // Avoids a format warning from GCC.
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:214:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
make: *** [src/IceUtil/build/macosx/static/OutputUtil.o] Error 1
make: *** Waiting for unfinished jobs....
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #1368

### CODE REVIEW

File: cpp/src/IceUtil/OutputUtil.cpp [hunk 1]
```diff
@@ -34,10 +34,19 @@ IceUtilInternal::int64ToString(Int64 val)
 
 #if defined(_WIN32)
     sprintf_s(buf, sizeof(buf), "%I64d", val);
-#elif defined(ICE_64)
-    sprintf(buf, "%ld", val); // Avoids a format warning from GCC.
+#elif defined(__APPLE__)
+    // sprintf is deprecated with macOS Ventura
+#   if defined(ICE_64)
```
Comment (externl) [inline cpp/src/IceUtil/OutputUtil.cpp:39]: Do we need this check anymore? Pretty sure everything Apple is 64-bit now.

File: cpp/src/IceUtil/OutputUtil.cpp [hunk 2]
```diff
@@ -34,10 +34,15 @@ IceUtilInternal::int64ToString(Int64 val)
 
 #if defined(_WIN32)
     sprintf_s(buf, sizeof(buf), "%I64d", val);
-#elif defined(ICE_64)
-    sprintf(buf, "%ld", val); // Avoids a format warning from GCC.
+#elif defined(__APPLE__)
+    // sprintf is deprecated with macOS Ventura
+    snprintf(buf, sizeof(buf), "%ld", val); // Avoids a format warning from GCC.
```
Comment (externl) [inline cpp/src/IceUtil/OutputUtil.cpp:39]: We can remove the comment. No GCC on macOS.

**Review by externl — APPROVED** [review]
