### PR TITLE
Complete Dispatch exception implementation

### LINKED ISSUE #3548: Proposal: Add implicit DispatchException
The current version (1.1) of the Ice protocol has no exception extensibility beyond the 6 local exceptions which can be encoded and user exceptions. This makes implementing generic middleware (think rate-limiting, authorization, etc.) painful. 

Users need to define an exception and ensure it's specified in every operation.

**Proposal:**

Add a new implicit user exception: `Ice::DispatchException` (name tbd), probably not defined in Slice so that users can't inherit from it.

Borrowing from IceRPC it could look something like https://github.com/icerpc/icerpc-slice/blob/main/IceRpc/StatusCode.slice.

E.g. (specifics to be worked out)
```slice
enum DispatchStatusCode {
     ...
     Unavailable,
     Unauthorized
     ...
}

exception DispatchException {
    DispatchStatus status;
    optional(1) string message;
}
```

This user exception would always be available in 3.8 and above and would be excluded from the exception specification checks.

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR makes the dispatch exception implementation and test more consistent across languages and reenables cross-testing for Ice/exceptions.

Fixes #3548.

### CODE REVIEW

File: cpp/src/Ice/LocalExceptions.cpp [hunk 1]
```diff
@@ -17,33 +17,42 @@ using namespace IceInternal;
...
 {
-    string createDispatchExceptionMessage(ReplyStatus replyStatus)
+    string createDispatchExceptionMessage(ReplyStatus replyStatus, optional<string> message)
     {
-        ostringstream os;
-        os << "dispatch failed with reply status " << replyStatus;
-        return os.str();
+        if (message)
+        {
+            return *message;
```
Comment (pepone) [inline cpp/src/Ice/LocalExceptions.cpp:24]: Do we need to call std::move here to avoid a copy?

**Review by pepone — APPROVED** [review]

**Review by externl — APPROVED** [review]

File: cpp/src/Ice/LocalExceptions.cpp (hunk 1 above)
Comment (bernardnormier) [reply cpp/src/Ice/LocalExceptions.cpp:24]: You're right, fixed. It would not be necessary without the optional unwrapping.
