### PR TITLE
C++ catch exception cleanup

### LINKED ISSUE #48: Eliminate catch(const char*)
We should not throw or catch C-strings (or any type not derived from `std::exception`), yet we have quite a number of `catch(const char*)` in the code:
```
./python/modules/IcePy/Slice.cpp:    catch(const char* msg)
./cpp/src/IceGrid/Client.cpp:    catch(const char* msg)
./cpp/src/IceGrid/Topics.cpp:    catch(const char* msg)
./cpp/src/slice2py/Main.cpp:    catch(const char* msg)
./cpp/src/Glacier2Lib/Application.cpp:    catch(const char* ex)
./cpp/src/slice2cs/Main.cpp:    catch(const char* msg)
./cpp/src/slice2java/Main.cpp:    catch(const char* msg)
./cpp/src/slice2cpp/Main.cpp:    catch(const char* msg)
./cpp/src/slice2html/Main.cpp:        catch(const char* err)
./cpp/src/slice2html/Main.cpp:    catch(const char* msg)
./cpp/src/IcePatch2/Calc.cpp:    catch(const char* ex)
./cpp/src/slice2confluence/Main.cpp:        catch(const char* err)
./cpp/src/slice2confluence/Main.cpp:    catch(const char* msg)
./cpp/src/slice2js/Main.cpp:    catch(const char* msg)
./cpp/src/Ice/Service.cpp:    catch(const char* msg)
./cpp/src/Ice/PluginManagerI.cpp:                catch(const char* msg)
./cpp/src/Ice/Application.cpp:    catch(const char* msg)
./cpp/src/Ice/Application.cpp:    catch(const char* msg)
./cpp/src/slice2php/Main.cpp:    catch(const char* msg)
./cpp/src/slice2matlab/Main.cpp:    catch(const char* msg)
./cpp/src/slice2rb/Main.cpp:    catch(const char* msg)
./cpp/src/slice2objc/Main.cpp:    catch(const char* msg)
./ruby/src/IceRuby/Slice.cpp:        catch(const char* msg)
```

ICE-8639

### PR DESCRIPTION
**Pull request by pepone**
Fix #48

### CODE REVIEW

File: cpp/src/IceGrid/RegistryI.cpp [hunk 1]
```diff
@@ -510,9 +510,26 @@ RegistryI::startImpl()
     _wellKnownObjects->addEndpoint("Server", _serverAdapter->createDirectProxy(dummy));
     _wellKnownObjects->addEndpoint("Internal", _registryAdapter->createDirectProxy(dummy));
 
-    if (!setupUserAccountMapper())
+    //
```
Comment (pepone) [inline cpp/src/IceGrid/RegistryI.cpp:513]: Moved `setupUserAccountMapper` implementation here as that was the only place we called.

**Review by bernardnormier — APPROVED** [review]
