### PR TITLE
Fix iceserviceinstall properties to accept IceGrid and Glacier2 prefixes

### LINKED ISSUE #4807: iceserviceinstall.exe failure on 3.8: IceGrid is opt-in and must be explicitly enabled.
### Version

- Ice 3.8
- OS: Windows 11

### Describe the bug

Creating Services with command: 
iceserviceinstall.exe icegridregistry registry.cfg

Error: unable to set 'IceGrid.InstanceName': property prefix 'IceGrid' is opt-in and must be explicitly enabled.

### Expected behavior

The service is created.

### Additional context

#registry.cfg
IceGrid.InstanceName=MyService
...

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR fixes the `iceserviceinstall` code to accept IceGrid and Glacier2 property prefixes (required since the code calls `getIceProperty` with IceGrid and Glacier2 property depending on the service).

It also includes small additional bug fixes in that code.

Fixes #4807

### CODE REVIEW

File: cpp/src/iceserviceinstall/ServiceInstaller.cpp [hunk 1]
```diff
@@ -282,7 +288,7 @@ IceServiceInstaller::install(const PropertiesPtr& properties)
     {
         DWORD res = GetLastError();
         CloseServiceHandle(scm);
-        throw runtime_error("Cannot create service" + _serviceName + ": " + IceInternal::errorToString(res));
+        throw runtime_error("Cannot create service '" + _serviceName + "': " + IceInternal::errorToString(res));
```
Comment (bernardnormier) [inline cpp/src/iceserviceinstall/ServiceInstaller.cpp:291]: The space was missing in the error messages.

File: cpp/src/iceserviceinstall/ServiceInstaller.cpp [hunk 2]
```diff
@@ -49,6 +49,12 @@ IceServiceInstaller::IceServiceInstaller(int serviceType, const string& configFi
     if (_serviceType == icegridregistry)
     {
         _icegridInstanceName = _serviceProperties->getIceProperty("IceGrid.InstanceName");
+        if (_icegridInstanceName == "")
```
Comment (bernardnormier) [inline cpp/src/iceserviceinstall/ServiceInstaller.cpp:52]: In Ice 3.7, the corresponding code is `getPropertyWithDefault("IceGrid.InstanceName", "IceGrid")`.

Keep in mind that in Ice 3.8, we recommend to use the default. In particular, the sample config files we ship no longer set `IceGrid.InstanceName`.

File: cpp/src/iceserviceinstall/ServiceInstaller.cpp [hunk 3]
```diff
@@ -36,7 +36,7 @@ IceServiceInstaller::IceServiceInstaller(int serviceType, const string& configFi
     : _serviceType(serviceType),
       _configFile(fixDirSeparator(configFile)),
       _communicator(communicator),
-      _serviceProperties(createProperties()),
+      _serviceProperties(make_shared<Properties>("IceGrid", "Glacier2")),
```
Comment (bernardnormier) [inline cpp/src/iceserviceinstall/ServiceInstaller.cpp:39]: The actual fix for #4807, using the preferred make_shared syntax.

**Review by pepone — APPROVED** [review]
