### PR TITLE
Fix lints in C++ code

### LINKED ISSUE #2358: C++ exceptions should have a noexcept copy constructor and assignment operator
Related to: https://github.com/zeroc-ice/ice-demos/issues/146

All C++ local exceptions should follow this rule. 

For generated user exceptions with user-specified fields, it should be true when the fields are noexcept copy-constructible and assignable. Unfortunately we can't provide this guarantee for user exceptions with fields that aren't noexcept copy-constructible  (like std::string) without breaking source compatibility. We could try to disable this diagnostics for such generated user exceptions.

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR fixes a number of lints reported by clang-tidy.

Fixes #2358.

### CODE REVIEW

File: cpp/src/slice2cpp/Gen.cpp [hunk 1]
```diff
@@ -2025,6 +2025,12 @@ Slice::Gen::DataDefVisitor::visitExceptionStart(const ExceptionPtr& p)
             H.dec();
             H << sb;
             H << eb;
+
+            // We generate a noexcept copy constructor all the time. A C++ exception must have noexcept copy constructor
```
Comment (bernardnormier) [inline cpp/src/slice2cpp/Gen.cpp:2029]: That's the fix for #2358: always generate a noexcept copy constructor even when the fields (e.g. string) don't have one. This will result in a crash if the field copy construction throws.

File: cpp/include/Ice/FactoryTable.h [hunk 2]
```diff
@@ -88,27 +88,27 @@ namespace IceInternal
...
 
-        const std::string_view typeId;
+        const char* typeId;
     };
 
     template<class O> class DefaultValueFactoryInit
     {
     public:
-        DefaultValueFactoryInit(std::string_view tId) : typeId(tId)
+        DefaultValueFactoryInit(const char* tId) noexcept : typeId(tId)
```
Comment (bernardnormier) [inline cpp/include/Ice/FactoryTable.h:104]: The `std::string_view(const char*)` constructor is not noexcept - and we always construct these objects with string literals.

**Review by externl — APPROVED** [review]

**Review by pepone — APPROVED** [review]
