### PR TITLE
Fix dynamic property warning in PHP slicing/objects test

### LINKED ISSUE #3090: `Deprecated: Creation of dynamic property` when running php test suite
```
❯ php -v
PHP 8.3.13 (cli) (built: Oct 22 2024 18:39:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.13, Copyright (c), by Zend Technologies
```

```
*** [141/343] Running php/Ice/slicing/objects tests ***
[ running client/server test - 11/07/24 09:54:04 ]
- Config: tcp
base as Object... ok
base as base... ok
base with known derived as base... ok
base with known derived as known derived... ok
base with unknown derived as base... ok
unknown with Object as Object... ok
one-element cycle... ok
two-element cycle... ok
known derived pointer slicing as base... ok
known derived pointer slicing as derived... ok
unknown derived pointer slicing as base... ok
parameter pointer slicing with known first... ok
parameter pointer slicing with unknown first... ok
return value identity with known first... ok
return value identity with unknown first... ok
return value identity for input params known first... ok
return value identity for input params unknown first... 
Deprecated: Creation of dynamic property Test\D3::$pd1 is deprecated in /Users/joe/Developer/zeroc-ice/ice/php/test/Ice/slicing/objects/Client.php on line 411
ok
return value identity for input params unknown first... ok
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #3090

### CODE REVIEW

File: php/test/Ice/slicing/objects/Client.php [hunk 1]
```diff
@@ -408,7 +408,10 @@ function allTests($helper)
         $d1->pb = null;
         $d1->pd1 = null;
         $b1->pb = null;
-        $p1->pd1 = null;
+        if($p1 instanceof Test\D3)
+        {
+            $p1->pd3 = null;
```
Comment (pepone) [inline php/test/Ice/slicing/objects/Client.php:413]: no pd3 property when it is Slicing in 1.0 encoding.

**Review by externl — APPROVED** [review]
