### PR TITLE
Ensure JavaScript Ice/ami test awaits all requests

### LINKED ISSUE #3129: Unhandled promise rejection in JavaScript Ice/ami test
https://github.com/zeroc-ice/ice/actions/runs/11745547072/job/32723221310

```
2024-11-08T17:11:11.1454892Z Unhandled Rejection at: OutgoingAsync [Promise] {
2024-11-08T17:11:11.1455899Z   <rejected> Ice.CommunicatorDestroyedException: Communicator destroyed.
2024-11-08T17:11:11.1457349Z       at ConnectionI.destroy (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/ConnectionI.js:176:37)
2024-11-08T17:11:11.1458725Z       at file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:35:70
2024-11-08T17:11:11.1459685Z       at Array.forEach (<anonymous>)
2024-11-08T17:11:11.1460944Z       at ConnectionListMap.forEach (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:475:25)
2024-11-08T17:11:11.1462879Z       at OutgoingConnectionFactory.destroy (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:35:37)
2024-11-08T17:11:11.1464564Z       at Instance.destroy (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/InstanceExtensions.js:338:45)
2024-11-08T17:11:11.1466036Z       at Communicator.destroy (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/Communicator.js:23:31)
2024-11-08T17:11:11.1467270Z       at Client.run (file:///D:/a/ice/ice/js/test/Ice/ami/Client.js:263:36)
2024-11-08T17:11:11.1468406Z       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-08T17:11:11.1469463Z       at async file:///D:/a/ice/ice/js/test/Common/run.js:38:9,
2024-11-08T17:11:11.1470165Z   resolve: [Function (anonymous)],
2024-11-08T17:11:11.1470700Z   reject: [Function (anonymous)],
2024-11-08T17:11:11.1471219Z   _communicator: Communicator {
2024-11-08T17:11:11.1471686Z     _isShutdown: true,
2024-11-08T17:11:11.1472164Z     _shutdownPromise: P [Promise] {
2024-11-08T17:11:11.1472652Z       undefined,
2024-11-08T17:11:11.1473059Z       resolve: [Function (anonymous)],
2024-11-08T17:11:11.1473777Z       reject: [Function (anonymous)]
2024-11-08T17:11:11.1474344Z     },
2024-11-08T17:11:11.1474691Z     _instance: Instance {
2024-11-08T17:11:11.1475110Z       _state: 2,
2024-11-08T17:11:11.1475556Z       _initData: [InitializationData],
2024-11-08T17:11:11.1476174Z       _traceLevels: [class (anonymous)],
2024-11-08T17:11:11.1476842Z       _defaultsAndOverrides: [DefaultsAndOverrides],
2024-11-08T17:11:11.1477605Z       _clientConnectionOptions: [ConnectionOptions],
2024-11-08T17:11:11.1478253Z       _messageSizeMax: 1048576,
2024-11-08T17:11:11.1478769Z       _batchAutoFlushSize: 1048576,
2024-11-08T17:11:11.1479459Z       _classGraphDepthMax: 10,
2024-11-08T17:11:11.1479948Z       _toStringMode: [type],
2024-11-08T17:11:11.1480401Z       _implicitContext: null,
2024-11-08T17:11:11.1480867Z       _routerManager: null,
2024-11-08T17:11:11.1481313Z       _locatorManager: null,
2024-11-08T17:11:11.1481779Z       _referenceFactory: null,
2024-11-08T17:11:11.1482327Z       _outgoingConnectionFactory: null,
2024-11-08T17:11:11.1482955Z       _objectAdapterFactory: null,
2024-11-08T17:11:11.1483456Z       _retryQueue: null,
2024-11-08T17:11:11.1483931Z       _endpointHostResolver: null,
2024-11-08T17:11:11.1484494Z       _endpointFactoryManager: null,
2024-11-08T17:11:11.1485052Z       _retryIntervals: [Array],
2024-11-08T17:11:11.1485500Z       _timer: null,
2024-11-08T17:11:11.1485949Z       _destroyPromise: [P [Promise]]
2024-11-08T17:11:11.1486436Z     }
2024-11-08T17:11:11.1486720Z   },
2024-11-08T17:11:11.1487009Z   _instance: Instance {
2024-11-08T17:11:11.1487408Z     _state: 2,
2024-11-08T17:11:11.1487846Z     _initData: InitializationData {
2024-11-08T17:11:11.1488417Z       properties: [Properties],
2024-11-08T17:11:11.1488907Z       logger: [Logger],
2024-11-08T17:11:11.1489444Z       valueFactoryManager: [ValueFactoryManager]
2024-11-08T17:11:11.1490018Z     },
2024-11-08T17:11:11.1490417Z     _traceLevels: [class (anonymous)],
2024-11-08T17:11:11.1491075Z     _defaultsAndOverrides: DefaultsAndOverrides {
2024-11-08T17:11:11.1491850Z       defaultProtocol: 'tcp',
2024-11-08T17:11:11.1492434Z       defaultHost: '127.0.0.1',
2024-11-08T17:11:11.1492981Z       defaultSourceAddress: null,
2024-11-08T17:11:11.1493541Z       overrideSecure: false,
2024-11-08T17:11:11.1494097Z       defaultEndpointSelection: [type],
2024-11-08T17:11:11.1494802Z       defaultLocatorCacheTimeout: -1,
2024-11-08T17:11:11.1495643Z       defaultInvocationTimeout: -1,
2024-11-08T17:11:11.1496258Z       defaultPreferSecure: false,
2024-11-08T17:11:11.1496796Z       defaultEncoding: [Object],
2024-11-08T17:11:11.1497308Z       defaultFormat: [type]
2024-11-08T17:11:11.1497732Z     },
2024-11-08T17:11:11.1498205Z     _clientConnectionOptions: ConnectionOptions {
2024-11-08T17:11:11.1498814Z       _connectTimeout: 10,
2024-11-08T17:11:11.1499259Z       _closeTimeout: 10,
2024-11-08T17:11:11.1499683Z       _idleTimeout: 60,
2024-11-08T17:11:11.1500106Z       _enableIdleCheck: true,
2024-11-08T17:11:11.1500589Z       _inactivityTimeout: 300
2024-11-08T17:11:11.1501024Z     },
2024-11-08T17:11:11.1501367Z     _messageSizeMax: 1048576,
2024-11-08T17:11:11.1501911Z     _batchAutoFlushSize: 1048576,
2024-11-08T17:11:11.1502448Z     _classGraphDepthMax: 10,
2024-11-08T17:11:11.1503279Z     _toStringMode: type { _name: 'Unicode', _value: 0 },
2024-11-08T17:11:11.1503926Z     _implicitContext: null,
2024-11-08T17:11:11.1504403Z     _routerManager: null,
2024-11-08T17:11:11.1504885Z     _locatorManager: null,
2024-11-08T17:11:11.1505346Z     _referenceFactory: null,
2024-11-08T17:11:11.1505915Z     _outgoingConnectionFactory: null,
2024-11-08T17:11:11.1506536Z     _objectAdapterFactory: null,
2024-11-08T17:11:11.1507035Z     _retryQueue: null,
2024-11-08T17:11:11.1507525Z     _endpointHostResolver: null,
2024-11-08T17:11:11.1508099Z     _endpointFactoryManager: null,
2024-11-08T17:11:11.1508624Z     _retryIntervals: [ 0 ],
2024-11-08T17:11:11.1509113Z     _timer: null,
2024-11-08T17:11:11.1509735Z     _destroyPromise: P [Promise] {
2024-11-08T17:11:11.1510324Z       undefined,
2024-11-08T17:11:11.1510794Z       resolve: [Function (anonymous)],
2024-11-08T17:11:11.1511419Z       reject: [Function (anonymous)]
2024-11-08T17:11:11.1511926Z     }
2024-11-08T17:11:11.1512235Z   },
2024-11-08T17:11:11.1512784Z   _operation: 'opWithPayload',
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #3129

### CODE REVIEW

File: js/test/Ice/ami/Client.ts [hunk 1]
```diff
@@ -159,29 +159,29 @@ export class Client extends TestHelper {
...
                         r2 = p.opWithPayload(seq);
+                        requests.push(r2);
                         if (r2.sentSynchronously()) {
                             await Ice.Promise.delay(0);
                         } else {
                             break;
                         }
                     }
 
-                    if ((await p.ice_getConnection()) !== null) {
```
Comment (pepone) [inline js/test/Ice/ami/Client.ts:174]: This method cannot return null on JavaScript.

File: js/test/Ice/ami/Client.ts [hunk 2]
```diff
@@ -194,6 +194,8 @@ export class Client extends TestHelper {
                 test(r2.isSent());
                 test(r2.isCompleted());
 
+                await Promise.all(requests);
```
Comment (pepone) [inline js/test/Ice/ami/Client.ts:197]: The test previously assumed that once the last sent request completed, all prior requests had also completed. However, this assumption is incorrect, as responses may still be send in a different order due to server threading.
