### PR TITLE
Fix crash when validating dispatch out parameters in Ice for Python

### LINKED ISSUE #4705: Python dispatch segmentation fault
```
Thread 10 "python3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1bb06c0 (LWP 24122)]
PyObject_IsInstance (inst=0x0, cls=0x55555611d120) at Objects/abstract.c:2700
2700        return object_recursive_isinstance(tstate, inst, cls);
(gdb) bt
#0  PyObject_IsInstance (inst=0x0, cls=0x55555611d120) at Objects/abstract.c:2700
#1  0x00007ffff68cbe1d in IcePy::PyException::raise (this=this@entry=0x7ffff1bae440) at modules/IcePy/Util.cpp:259
#2  0x00007ffff68cc2e8 in IcePy::throwPythonException () at modules/IcePy/Util.cpp:717
#3  0x00007ffff689dd1d in IcePy::Operation::marshalResult (this=0x5555561e5c80, os=..., result=result@entry=0x7ffff69ce120) at modules/IcePy/Operation.cpp:729
#4  0x00007ffff689e2ca in IcePy::TypedUpcall::response (this=0x7fffc80012a0, result=0x7ffff69ce120) at /usr/include/c++/12/bits/shared_ptr_base.h:1665
#5  0x00007ffff6897fb7 in dispatchCallbackResponse (self=0x7ffff5bbcc30, args=<optimized out>) at modules/IcePy/Operation.cpp:463
#6  0x000055555565b036 in method_vectorcall_VARARGS (func=0x7ffff6971ad0, args=0x7ffff1bae9d8, nargsf=<optimized out>, kwnames=0x0) at Objects/descrobject.c:325
#7  0x000055555564c580 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x101, callable=0x7ffff6971ad0, tstate=0x7fffc8000eb0) at ./Include/internal/pycore_call.h:169
#8  PyObject_Vectorcall (callable=0x7ffff6971ad0, args=args@entry=0x7ffff1bae9d8, nargsf=<optimized out>, kwnames=kwnames@entry=0x0) at Objects/call.c:327
#9  0x00005555555e1e5c in _PyEval_EvalFrameDefault (tstate=0x7fffc8000eb0, frame=<optimized out>, throwflag=<optimized out>) at Python/generated_cases.c.h:4079
#10 0x00005555557aeada in _PyEval_EvalFrame (throwflag=0, frame=<optimized out>, tstate=0x7fffc8000eb0) at ./Include/internal/pycore_ceval.h:121
#11 _PyEval_Vector (tstate=0x7fffc8000eb0, func=0x7ffff5c67060, locals=0x0, args=0x7ffff5c55f00, argcount=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:2083
#12 0x00007ffff689cd56 in IcePy::Upcall::dispatchImpl (this=this@entry=0x7fffc80012a0, servant=servant@entry=0x7ffff69cde80, dispatchName=..., args=0x7ffff5bdf8c0, current=...) at modules/IcePy/Operation.cpp:1928
#13 0x00007ffff689d44b in IcePy::TypedUpcall::dispatch (this=0x7fffc80012a0, servant=0x7ffff69cde80, inBytes=..., current=...) at modules/IcePy/Operation.cpp:2040
#14 0x00007ffff68a0514 in IcePy::TypedServantWrapper::ice_invokeAsync(std::pair<std::byte const*, std::byte const*>, std::function<void (bool, std::pair<std::byte const*, std::byte const*>)>, std::function<void (std::__exception_ptr::exception_ptr)>, Ice::Current const&) (this=<optimized out>, inParams=..., 
    response=..., error=..., current=...) at modules/IcePy/Operation.cpp:2537
#15 0x00007ffff6488d8d in Ice::BlobjectArrayAsync::dispatch(Ice::IncomingRequest&, std::function<void (Ice::OutgoingResponse)>) (this=0x5555561b2bd0, request=..., sendResponse=...) at src/Ice/Object.cpp:238
#16 0x00007ffff64e9d5b in IceInternal::ServantManager::dispatch(Ice::IncomingRequest&, std::function<void (Ice::OutgoingResponse)>) (this=0x5555561bbd70, request=..., sendResponse=...) at src/Ice/ServantManager.cpp:480
#17 0x00007ffff64536ae in IceInternal::LoggerMiddleware::dispatch(Ice::IncomingRequest&, std::function<void (Ice::OutgoingResponse)>) (this=this@entry=0x7fffe0001b00, request=..., sendResponse=...) at src/Ice/LoggerMiddleware.cpp:35
#18 0x00007ffff63c3168 in Ice::ConnectionI::dispatchAll (this=0x7fffd4001280, stream=..., requestCount=1, requestId=2, compress=0 '\000', adapter=...) at src/Ice/ConnectionI.cpp:3428
#19 0x00007ffff63c3590 in operator() (messageStream=..., __closure=<optimized out>) at src/Ice/ConnectionI.cpp:3225
#20 std::__invoke_impl<bool, Ice::ConnectionI::parseMessage(int32_t&, std::function<bool(Ice::InputStream&)>&, Ice::InputStream&)::<lambda(Ice::InputStream&)>&, Ice::InputStream&> (__f=...) at /usr/include/c++/12/bits/invoke.h:61
#21 std::__invoke_r<bool, Ice::ConnectionI::parseMessage(int32_t&, std::function<bool(Ice::InputStream&)>&, Ice::InputStream&)::<lambda(Ice::InputStream&)>&, Ice::InputStream&> (__fn=...) at /usr/include/c++/12/bits/invoke.h:114
#22 std::_Function_handler<bool(Ice::InputStream&), Ice::ConnectionI::parseMessage(int32_t&, std::function<bool(Ice::InputStream&)>&, Ice::InputStream&)::<lambda(Ice::InputStream&)> >::_M_invoke(const std::_Any_data &, Ice::InputStream &) (__functor=..., __args#0=...) at /usr/include/c++/12/bits/std_function.h:290
#23 0x00007ffff63bfade in std::function<bool (Ice::InputStream&)>::operator()(Ice::InputStream&) const (__args#0=..., this=0x7ffff1baf870) at /usr/include/c++/12/bits/std_function.h:591
#24 Ice::ConnectionI::upcall(std::function<void (std::shared_ptr<Ice::ConnectionI>)> const&, std::vector<Ice::ConnectionI::OutgoingMessage, std::allocator<Ice::ConnectionI::OutgoingMessage> > const&, std::function<bool (Ice::InputStream&)> const&, Ice::InputStream&) (this=0x7fffd4001280, 
    connectionStartCompleted=..., sentCBs=..., messageUpcall=..., messageStream=...) at src/Ice/ConnectionI.cpp:1540
#25 0x00007ffff63c253c in Ice::ConnectionI::message (this=0x7fffd4001280, current=...) at src/Ice/ConnectionI.cpp:1476
#26 0x00007ffff6504dd6 in IceInternal::ThreadPool::run (this=0x555555bb32e0, thread=...) at src/Ice/ThreadPool.cpp:489
#27 0x00007ffff65054c9 in IceInternal::ThreadPool::EventHandlerThread::run (this=0x555556199f30) at src/Ice/ThreadPool.cpp:1061
#28 0x00007ffff5ed44a3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#29 0x00007ffff7d6f1f5 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#30 0x00007ffff7def8dc in ?? () from /lib/x86_64-linux-gnu/libc.so.6
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #4705

### CODE REVIEW

File: python/modules/IcePy/Operation.cpp [hunk 1]
```diff
@@ -703,19 +703,22 @@ Operation::marshalResult(Ice::OutputStream& os, PyObject* result)
         PyObject* arg = PyTuple_GET_ITEM(resultTuple.get(), info->pos);
         if ((!info->optional || arg != Py_None) && !info->type->validate(arg))
         {
-            try
-            {
-                throwPythonException();
-            }
-            catch (const Ice::UnknownException& ex)
+            // TODO: Provide the parameter name instead?
```
Comment (externl) [inline python/modules/IcePy/Operation.cpp:706]: We should open an issue to track this TODO.

EDIT: After reading further I realize you didn't add this. Would be good to either fix or delete this comment.

File: python/modules/IcePy/Operation.cpp [hunk 2]
```diff
@@ -703,19 +703,22 @@ Operation::marshalResult(Ice::OutputStream& os, PyObject* result)
...
+            ostringstream ostr;
+            ostr << "cannot marshal result: invalid value for out argument " << (info->pos + 1) << " in operation '"
```
Comment (externl) [inline python/modules/IcePy/Operation.cpp:708]: Can we improve the error message? Invalid is a bit ambiguous to me. Doe it mean wrong/unexpected type, a value that's out of range, something else?

File: python/modules/IcePy/Operation.cpp [hunk 3]
```diff
@@ -724,17 +727,20 @@ Operation::marshalResult(Ice::OutputStream& os, PyObject* result)
         PyObject* res = PyTuple_GET_ITEM(resultTuple.get(), 0);
         if ((!returnType->optional || res != Py_None) && !returnType->type->validate(res))
         {
-            try
-            {
-                throwPythonException();
-            }
-            catch (const Ice::UnknownException& ex)
+            ostringstream ostr;
+            ostr << "cannot marshal result: invalid return value for operation '" << mappedName << "'";
```
Comment (externl) [inline python/modules/IcePy/Operation.cpp:731]: Ditto.

File: python/modules/IcePy/Operation.cpp (hunk 2 above)
Comment (pepone) [reply python/modules/IcePy/Operation.cpp:708]: Here it means the "validate" method  for the param returned false, it doesn't specify the concrete error.

File: python/modules/IcePy/Operation.cpp [hunk 4]
```diff
@@ -703,19 +703,22 @@ Operation::marshalResult(Ice::OutputStream& os, PyObject* result)
...
-                ostringstream ostr;
-                ostr << "cannot marshal result: invalid value for out argument " << (info->pos + 1) << " in operation '"
-                     << mappedName;
-                ostr << "':\n" << ex.what();
-                throw Ice::MarshalException(__FILE__, __LINE__, ostr.str());
+                try
+                {
+                    throwPythonException();
+                }
+                catch (const Ice::UnknownException& ex)
```
Comment (bernardnormier) [inline python/modules/IcePy/Operation.cpp]: I'd rather catch `Ice::LocalException` here. Otherwise the reader wonders: why does throwPythonException always throw an UnknownException?

File: python/modules/IcePy/Operation.cpp [hunk 5]
```diff
@@ -724,17 +727,20 @@ Operation::marshalResult(Ice::OutputStream& os, PyObject* result)
...
             {
-                ostringstream ostr;
-                ostr << "cannot marshal result: invalid return value for operation '" << mappedName << "':\n"
-                     << ex.what();
-                throw Ice::MarshalException(__FILE__, __LINE__, ostr.str());
+                try
+                {
+                    throwPythonException();
+                }
+                catch (const Ice::UnknownException& ex)
```
Comment (bernardnormier) [inline python/modules/IcePy/Operation.cpp]: Same here.

**Review by bernardnormier — APPROVED** [review]
