### PR TITLE
Use Port-Forarding to Work Around Broken Android Test Controller

### LINKED ISSUE #4637: Android Test Suite Doesn't work On-Device
After fixing #4587 locally, I ran the Android tests in the emulator, and tried to run them on my Samsung Galaxy A25, but the test-controller for android returns unusable proxies, and the tests fail.

The problem is the published host for proxies returned by `ControllerApp`.
If we aren't running the emulator, we don't set `PublishedHost` via properties, meaning we compute one with this call:
```
publishedHost = InetAddress.getLocalHost().getHostName();
```
On MacOS and Windows, this returns a proper DNS hostname, but on android this always returns `localhost`.
This happens both on device and with the emulator, but this doesn't affect the emulator, since we set an explicit `PublishedHost` in `initData`.

----

Dumping my phone's network interfaces suggests that `getLocalHost` on Android always uses the `lo` interface, unlike other platforms:
```
INTERFACE 0: [dummy0] isLoopback=NO isVirtual=NO isUp=YES
    ADDR 0: fe80::e09b:bfff:fe80:44ed%dummy0
        isLoopback:  NO
        isSiteLocal: NO
        isLinkLocal: YES

INTERFACE 1: [wlan0] isLoopback=NO isVirtual=NO isUp=YES
    ADDR 0: [fe80::d0ef:ccff:fe8a:9db0%wlan0]
        isLoopback:  NO
        isSiteLocal: NO
        isLinkLocal: YES
    ADDR 1: [fd9d:1fff:250b:c846:d0ef:ccff:fe8a:9db0]
        isLoopback:  NO
        isSiteLocal: NO
        isLinkLocal: NO
    ADDR 2: [fd9d:1fff:250b:c846:2481:a77:c863:e8a3]
        isLoopback:  NO
        isSiteLocal: NO
        isLinkLocal: NO
    ADDR 3: [Austins-Galaxy-A25.jupiter.zeroc.com]    << What we want
        isLoopback:  NO
        isSiteLocal: YES
        isLinkLocal: NO

INTERFACE 2: [lo] isLoopback=YES isVirtual=NO isUp=YES
    ADDR 0: [ip6-localhost]
        isLoopback:  YES
        isSiteLocal: NO
        isLinkLocal: NO
    ADDR 1: [localhost]                 << What is actually published
        isLoopback:  YES
        isSiteLocal: NO
        isLinkLocal: NO
```
Sanity check: adding `initData.properties.setProperty("ControllerAdapter.PublishedHost", "Austins-Galaxy-A25")` to the on-device test-controller does fix this problem, and the tests all work (except Ice/udp, but whatever).

This isn't a quirk of Java, checking the device's hostname via `abd shell hostname` also returns `localhost`.
Looking online, some people said this is expected, but other people got reasonable DNS names running the same command. So maybe this is manufacturer dependent?

----

It's possible to fix this in general by looking through all the available INetAddresses and choosing the sane one.
But it'd be nice to have a larger sample size than `1` before making this change:
```java
// ControllerApp.java

                // Find the first non-loopback site-local INetAddress available for this device.
                //
                // We can't use `.networkInterfaces` or `.inetAddresses` because they are not available on Android.
                InetAddress hostAddress = null;
                try {
interfaceLoop:      for (var interfaces = NetworkInterface.getNetworkInterfaces(); interfaces.hasMoreElements();) {
                        var intf = interfaces.nextElement();
                        if (intf.isUp() && !intf.isLoopback()) {
                            for (var addresses = intf.getInetAddresses(); addresses.hasMoreElements();) {
                                var addr = addresses.nextElement();
                                if (addr.isSiteLocalAddress()) {
                                    hostAddress = addr;
                                    break interfaceLoop;
                                }
                            }
                        }
                    }
                } catch (SocketException ignored) {}
                if (hostAddress != null) {
                    initData.properties.setProperty("ControllerAdapter.PublishedHost", hostAddress.getHostName());
                }
```

### PR DESCRIPTION
**Pull request by InsertCreativityHere**
This PR fixes #4637 for our test suite, but not in general.
For our purposes we can just use port-forwarding for on-device testing (same as we do for the emulator),

For users in the real-world, running servers on Android devices, they will need to set `PublishedHost` in order for their server to return functioning proxies.

----

I tested this PR on-device and with the emulator and everything worked fine (except for IPv6 with the `Ice/udp` test, see #4654).

### CODE REVIEW

File: java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java [hunk 1]
```diff
@@ -173,16 +173,13 @@ public ControllerI(boolean bluetooth) {
...
-                // We use a hardcoded port that's forwarded to the host machine by the emulator.
-                initData.properties.setProperty("ControllerAdapter.Endpoints", "tcp -p 15001");
-                initData.properties.setProperty("ControllerAdapter.PublishedHost", "127.0.0.1");
-            }
-            else
+            // We use a hardcoded port that is forwarded to the device / emulator with `adb forward`.
+            initData.properties.setProperty("ControllerAdapter.Endpoints", "tcp -p 15001");
+            initData.properties.setProperty("ControllerAdapter.PublishedHost", "127.0.0.1");
+
+            if (!isEmulator())
```
Comment (externl) [inline java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java]: I don't think there's any reason to have discovery or AdapterID  configured now.

File: java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java [hunk 2]
```diff
@@ -173,21 +173,13 @@ public ControllerI(boolean bluetooth) {
...
-                initData.properties.setProperty("ControllerAdapter.Endpoints", "tcp -p 15001");
-                initData.properties.setProperty("ControllerAdapter.PublishedHost", "127.0.0.1");
-            }
-            else
+            // We use a hardcoded port that is forwarded to the device / emulator with `adb forward`.
+            initData.properties.setProperty("ControllerAdapter.Endpoints", "tcp -p 15001");
+            initData.properties.setProperty("ControllerAdapter.PublishedHost", "127.0.0.1");
+
+            if (bluetooth)
             {
```
[the remark this answers is not in the document]
Comment (externl) [reply java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java]: We should probably be running rewrite on the android controller too!

[the remark this answers is not in the document]
Comment (InsertCreativityHere) [reply java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java]: Yep, looking into it now!

File: java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java [hunk 3]
```diff
@@ -173,21 +173,12 @@ public ControllerI(boolean bluetooth) {
...
-                    initData.properties.setProperty("Ice.Plugin.IceBT", "com.zeroc.IceBT.PluginFactory");
-                }
-                initData.properties.setProperty("Ice.Plugin.IceDiscovery", "com.zeroc.IceDiscovery.PluginFactory");
-                initData.properties.setProperty("IceDiscovery.DomainId", "TestController");
+            // We use a hardcoded port that is forwarded to the device / emulator with `adb forward`.
+            initData.properties.setProperty("ControllerAdapter.Endpoints", "tcp -p 15001");
+            initData.properties.setProperty("ControllerAdapter.PublishedHost", "127.0.0.1");
+
+            if (bluetooth) {
+                initData.properties.setProperty("Ice.Plugin.IceBT", "com.zeroc.IceBT.PluginFactory");
```
Comment (pepone) [inline java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java]: We should use the new plugin factory on initData.

**Review by pepone — APPROVED** [review]

File: java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java (hunk 3 above)
Comment (InsertCreativityHere) [reply java/test/android/controller/src/main/java/com/zeroc/testcontroller/ControllerApp.java]: Fixed!
