### PR TITLE
Fix back pressure test in C#

### LINKED ISSUE #4646: Ice  back pressure test failure
This failed here for Windows 2022 C#

https://github.com/zeroc-ice/ice/actions/runs/19293615331/job/55170011562

```
2025-11-12T10:27:48.1028052Z testing back pressure... System.Exception: Exception of type 'System.Exception' was thrown.
2025-11-12T10:27:48.1028919Z    at Test.AllTests.test(Boolean b) in D:\a\ice\ice\csharp\test\TestCommon\TestHelper.cs:line 158
2025-11-12T10:27:48.1029652Z    at Ice.ami.AllTests.allTestsAsync(TestHelper helper, Boolean collocated) in D:\a\ice\ice\csharp\test\Ice\ami\AllTests.cs:line 935
2025-11-12T10:27:48.1030357Z    at Ice.ami.Client.runAsync(String[] args) in D:\a\ice\ice\csharp\test\Ice\ami\Client.cs:line 27
2025-11-12T10:27:48.1030928Z    at Ice.ami.Client.runAsync(String[] args) in D:\a\ice\ice\csharp\test\Ice\ami\Client.cs:line 27
2025-11-12T10:27:48.1031780Z    at Test.TestDriver.runTestAsync[T](String[] args) in D:\a\ice\ice\csharp\test\TestCommon\TestHelper.cs:line 172
2025-11-12T10:27:48.1032439Z saved D:\a\ice\ice\csharp\test\Ice\ami\client-111225-1027.log
2025-11-12T10:27:48.1033214Z saved D:\a\ice\ice\csharp\test\Ice\ami\server-111225-1027.log
```

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #4646. The CTS code was bogus. Also fix formatting of corresponding test in Java.

### CODE REVIEW

File: csharp/test/Ice/ami/AllTests.cs [hunk 1]
```diff
@@ -925,6 +924,7 @@ public static async Task allTestsAsync(global::Test.TestHelper helper, bool coll
                     // twice before blocking.
                     for (int i = 0; i < 3; ++i)
                     {
+                        using var cts = new CancellationTokenSource(200);
                         await onewayProxy.opWithPayloadAsync(new byte[768 * 1024]).WaitAsync(cts.Token);
```
Comment (pepone) [inline csharp/test/Ice/ami/AllTests.cs:928]: This is fine, but I don't think this is the cause of #4646.

The failure seems to indicate the 3 request were queued, how this change the fact that 3 oneway request get queued?

Comment (bernardnormier) [reply csharp/test/Ice/ami/AllTests.cs:928]: You're right, this update only synchronizes this test with the C++ test. We should also fix the assert to know what actually fails.

**Review by pepone — APPROVED** [review]
