### PR TITLE
Fix mapping for optional proxies in MATLAB

### LINKED ISSUE #1634: Ice for MATLAB does not handle optional proxies correctly
#1633 shows 2 bugs:
 - an unset optional proxy is not == Ice.Unset
 - the generated code code an operation with optional proxies fails when these parameters are not set

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #1634.

Both null proxies and unset proxies are now mapped to empty arrays in MATLAB.

### CODE REVIEW

File: cpp/src/slice2matlab/Main.cpp [hunk 1]
```diff
@@ -1948,14 +1948,8 @@ CodeVisitor::visitClassDefStart(const ClassDefPtr& p)
     }
     for (const auto& dm : optionalMembers)
     {
-        if (dm->type()->isClassType())
```
Comment (bernardnormier) [inline cpp/src/slice2matlab/Main.cpp:1951]: optional class leftover

File: matlab/test/Ice/optional/AllTests.m [hunk 2]
```diff
@@ -504,14 +504,14 @@
             [p2, p3] = f.fetchOutputs();
             assert(p2.a == p1.a && p3.a == p1.a);
 
-            % [p2, p3] = initial.opMyInterfaceProxy(Ice.Unset);
-            % assert(p2 == Ice.Unset && p3 == Ice.Unset);
-            % p1 = communicator.stringToProxy('test');
```
Comment (bernardnormier) [inline matlab/test/Ice/optional/AllTests.m:509]: stringToProxy also works. We don't validate proxy typing when marshaling.

**Review by externl — APPROVED** [review]

**Review by pepone — APPROVED** [review]
