### PR TITLE
Make getIcePropertiesXxx no throw in Swift

### LINKED ISSUE #2946: Replace getIceProperty exception by fatal error in Swift
getIceProperty in Swift should not throw an exception but terminate immediately with a fatal error.

It's odd and unexpected to have a 'try' in simple code like:
```swift
let host = try communicator.getProperties().getIcePropertyAsInt("Ice.IPv6") != 0 ? "::1" : "127.0.0.1"
```

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #2946.

### CODE REVIEW

**Review by externl — APPROVED** [review]

File: swift/src/IceImpl/include/Properties.h [hunk 1]
```diff
@@ -4,29 +4,28 @@
 NS_ASSUME_NONNULL_BEGIN
 
 ICEIMPL_API @interface ICEProperties : ICELocalObject
-- (nonnull NSString*)getProperty:(NSString*)key;
-- (nullable NSString*)getIceProperty:(NSString*)key error:(NSError**)error NS_SWIFT_NAME(getIceProperty(_:));
-- (nonnull NSString*)getPropertyWithDefault:(NSString*)key value:(NSString*)value;
+- (NSString*)getProperty:(NSString*)key;
```
Comment (pepone) [inline swift/src/IceImpl/include/Properties.h:7]: is this change because we have NS_ASSUME_NONNULL_BEGIN, and all the operations return nonnull results?

**Review by pepone — APPROVED** [review]

File: swift/src/IceImpl/include/Properties.h (hunk 1 above)
Comment (bernardnormier) [reply swift/src/IceImpl/include/Properties.h:7]: Yes
