### PR TITLE
Fixed concurrent directory creation issue in the Slice compilers

### LINKED ISSUE #1846: slice2matlab parallel build failures creating module directories
This code is prone to fail when building Slice files for the same module in parallel:

https://github.com/zeroc-ice/ice/blob/bf991f4f7604869517f9211f18a6048239521551/cpp/src/slice2matlab/Main.cpp#L234-L243

We just hit this with CI builds:

```
../cpp/bin/slice2matlab  -I../slice -Itest/Ice/optional --output-dir test/Ice/optional  --depend test/Ice/optional/Test.ice | sed 's/\(.*: \\\)/\/\/\1/' > test/Ice/optional/.depend/Test.ice.d
../cpp/bin/slice2matlab  -I../slice -Itest/Ice/optional --output-dir test/Ice/optional/generated  test/Ice/optional/ClientPrivate.ice
../cpp/bin/slice2matlab  -I../slice -Itest/Ice/optional --output-dir test/Ice/optional/generated  test/Ice/optional/Test.ice
../cpp/bin/slice2matlab: error: cannot create directory `test/Ice/optional/generated/+Test': File exists
make: *** [Makefile:146: test/Ice/optional/generated/Test.m] Error 1
```

### PR DESCRIPTION
**Pull request by pepone**
Fix #1846

### CODE REVIEW

**Comment by pepone** [comment]
We should chery-pick to 3.7

File: cpp/src/slice2java/JavaUtil.cpp [hunk 1]
```diff
@@ -700,10 +700,17 @@ Slice::JavaOutput::openClass(const string& cls, const string& prefix, const stri
                 continue;
             }
 
-            if(IceUtilInternal::mkdir(path, 0777) != 0)
+            int err = IceUtilInternal::mkdir(path, 0777);
+            // If slice2java is run concurrently, it's possible that another instance of slice2matlab has already
```
Comment (externl) [inline cpp/src/slice2java/JavaUtil.cpp:704]:
```suggestion
            // If slice2java is run concurrently, it's possible that another instance of slice2java has already
```

**Review by externl — APPROVED** [review]

**Review by bernardnormier — APPROVED** [review]
