### PR TITLE
Remove Incorrect 'virtual' Modifiers

### LINKED ISSUE #4846: Incorrect `virtual` Modifiers Applied to Logically `final` Functions
There are at least 2 classes which are final, but declare `virtual` functions.
This is at best useless, since nothing can ever override these functions.

We should remove/replace these incorrect modifiers where present.

### PR DESCRIPTION
**Pull request by InsertCreativityHere**
This PR fixes #4846.

### CODE REVIEW

File: cpp/src/Ice/ConnectionFactory.h [hunk 1]
```diff
@@ -88,11 +88,11 @@ namespace IceInternal
                 std::function<void(Ice::ConnectionIPtr, bool)>,
                 std::function<void(std::exception_ptr)>);
```
Comment (InsertCreativityHere) [inline cpp/src/Ice/ConnectionFactory.h:90]: This class is `final` and doesn't meaningfully inherit from anything:
```
class ConnectCallback final : public std::enable_shared_from_this<ConnectCallback>
```

File: cpp/test/Ice/operations/BatchOneways.cpp [hunk 2]
```diff
@@ -18,7 +18,7 @@ namespace
     public:
         BatchRequestInterceptorI() = default;
```
Comment (InsertCreativityHere) [inline cpp/test/Ice/operations/BatchOneways.cpp:20]: This class is `final` and has no superclasses:
```
class BatchRequestInterceptorI final
```

File: cpp/src/Ice/ConnectionFactory.h [hunk 3]
```diff
@@ -193,8 +193,8 @@ namespace IceInternal
         //
 
 #if defined(ICE_USE_IOCP)
```
Comment (InsertCreativityHere) [inline cpp/src/Ice/ConnectionFactory.h:195]: This class is `final`, but inherits from `EventHandler`:
```
class IncomingConnectionFactory final : public EventHandler
```

File: cpp/src/IceBT/AcceptorI.cpp [hunk 4]
```diff
@@ -19,7 +19,7 @@ using namespace IceBT;
 
 namespace
 {
-    class ProfileCallbackI : public ProfileCallback
+    class ProfileCallbackI final : public ProfileCallback
```
Comment (InsertCreativityHere) [inline cpp/src/IceBT/AcceptorI.cpp:22]: This is somewhat unrelated to the other changes, but should fix this warning:
```
/usr/lib/llvm-21/bin/../include/c++/v1/__memory/construct_at.h:61:3: error:
      destructor called on non-final '(anonymous namespace)::ProfileCallbackI' that has virtual functions
      but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
   61 |   __loc->~_Tp();
      |   ^
```

File: cpp/src/Ice/ConnectionFactory.h (hunk 3 above)
Comment (bernardnormier) [reply cpp/src/Ice/ConnectionFactory.h:195]: There is a high likelihood that these virtual functions should be marked final (and not virtual). Not nothing.

File: cpp/test/Ice/operations/BatchOneways.cpp (hunk 2 above)
Comment (bernardnormier) [reply cpp/test/Ice/operations/BatchOneways.cpp:20]: should be final or override
