### PR TITLE
Fix for #1543

### LINKED ISSUE #1543: Adopt new Slice class format and preservation approach
In "new Slice" (https://docs.icerpc.dev/slice1):
 - exceptions are always encoded in the sliced format
 - classes encoded in Sliced format are always "fully preserved" (there is no attribute to preserve slices)
 - exceptions are not preserved - unknown slices are lost during decoding

I propose we do the same in Ice for Ice 3.8 and cleanup Slice files like:
https://github.com/zeroc-ice/ice/blob/ce1649d310904937a3e70a0ac79dc0bcb3a7433a/slice/Glacier2/Session.ice#L37

In this file, we mark operations `format:slice` ostensibly to encode the one exception (CannotCreateSessionException) in the sliced format even though we don't define anywhere a derived exception.

### PR DESCRIPTION
**Pull request by bentoi**
This PR fixes #1543 for all language mappins except Matlab. I can try to write a patch for Matlab to make it easier to fix it but I won't be able to test.

### CODE REVIEW

File: cpp/test/IceGrid/session/Server.cpp [hunk 1]
```diff
@@ -19,7 +18,7 @@ class ClientPermissionsVerifierI final : public Glacier2::PermissionsVerifier
     {
         if(current.ctx.find("throw") != current.ctx.end())
         {
-            throw Test::ExtendedPermissionDeniedException("reason");
+            throw Glacier2::PermissionDeniedException("reason");
```
Comment (bernardnormier) [inline cpp/test/IceGrid/session/Server.cpp:21]: For my understanding:
using a derived exception no longer works for this use-case because the intermediary (IceGrid) unmarshals and then remarshals the exception?

**Review by bernardnormier — APPROVED** [review]
Looks good, much simpler.

I believe you also need to remove the validation for the preserve-slice metadata (unless there is none?), but this can wait until a follow-up PR.

**Review by pepone — APPROVED** [review]

File: cpp/test/IceGrid/session/Server.cpp (hunk 1 above)
Comment (bentoi) [reply cpp/test/IceGrid/session/Server.cpp:21]: Right.

**Comment by bentoi** [comment]
> I believe you also need to remove the validation for the preserve-slice metadata (unless there is none?), but this can wait until a follow-up PR.

I couldn't find metadata validation for preserve-slice.
