### PR TITLE
Fix bug in C# Ice/metrics test

### LINKED ISSUE #2680: CI failure: testing endpoint lookup metrics... no map `EndpointLookup` for group by = `endpointCompress`
The CI for C# on macos often fails with:

```
[ running client/server test - 08/26/24 17:49:05 ]
- Config: ssl,serialize,mx
(dotnet /Users/runner/work/ice/ice/csharp/test/Ice/metrics/msbuild/server/net8.0/server.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=2 --IceSSL.CertFile=server.p12 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=/Users/runner/work/ice/ice/csharp/test/Ice/metrics/server-082624-1749.log)
(dotnet /Users/runner/work/ice/ice/csharp/test/Ice/metrics/msbuild/client/net8.0/client.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=2 --IceSSL.CertFile=client.p12 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=/Users/runner/work/ice/ice/csharp/test/Ice/metrics/client-082624-1749.log)
testing metrics admin facet checkedCast... ok
testing group by none...ok
testing group by id...ok
testing connection metrics... ok
testing connection establishment metrics... ok
testing endpoint lookup metrics... no map `EndpointLookup' for group by = `endpointCompress'
System.Exception: Exception of type 'System.Exception' was thrown.
   at Test.AllTests.test(Boolean b) in /Users/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 218
   at AllTests.testAttribute(MetricsAdminPrx metrics, PropertiesAdminPrx props, UpdateCallbackI update, String map, String attr, String value, Action func, TextWriter output) in /Users/runner/work/ice/ice/csharp/test/Ice/metrics/AllTests.cs:line 337
   at AllTests.allTests(TestHelper helper, CommunicatorObserverI obsv) in /Users/runner/work/ice/ice/csharp/test/Ice/metrics/AllTests.cs:line 851
   at Client.runAsync(String[] args) in /Users/runner/work/ice/ice/csharp/test/Ice/metrics/Client.cs:line 29
   at Test.TestDriver.runTestAsync[T](String[] args) in /Users/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 232
saved /Users/runner/work/ice/ice/csharp/test/Ice/metrics/client-082624-1749.log
saved /Users/runner/work/ice/ice/csharp/test/Ice/metrics/server-082624-1749.log

test in Ice/metrics failed:
Traceback (most recent call last):
```

It does not always fail though.

for example:
https://github.com/zeroc-ice/ice/actions/runs/10563261351/job/29263099768

### PR DESCRIPTION
**Pull request by bernardnormier**
Fixes #2680.

### CODE REVIEW

File: csharp/test/Ice/metrics/AllTests.cs [hunk 1]
```diff
@@ -356,7 +357,7 @@ private static void
         }
     }
 
-    private static async void connect(Ice.ObjectPrx proxy)
```
Comment (bernardnormier) [inline csharp/test/Ice/metrics/AllTests.cs:359]: This was the root issue: connect is now async but we no longer waited for connect to complete.
