### PR TITLE
Fix Metadata Warning Locations

### LINKED ISSUE #2021: Warnings for Invalid Metadata are Reported on Incorrect Lines
I was fixing some of our `errorDetection` tests and noticed that the line number are off.
For example, take `WarningInvalidMetaData.ice`

In the source we have: https://github.com/zeroc-ice/ice/blob/60c41eab191ebdc522ac402ff4e0ec96f3c9351a/cpp/test/Slice/errorDetection/WarningInvalidMetaData.ice#L55-L59 But in the expected errors: https://github.com/zeroc-ice/ice/blob/60c41eab191ebdc522ac402ff4e0ec96f3c9351a/cpp/test/Slice/errorDetection/WarningInvalidMetaData.err#L18-L20

You will notice that `56 != 58`.

### PR DESCRIPTION
**Pull request by InsertCreativityHere**
This PR fixes #2021.

Before my refactoring of metadata, we didn't store the metadata's location. So when reporting warnings, we either had to omit location information (by passing `-1`) of guess that it was the same line as some other Slice definition.

Now, we use the metadata's location properly.
You can see this in the test that had to be fixed at the bottom of this PR.

### CODE REVIEW

**Comment by InsertCreativityHere** [comment]
I fixed the clang-format error locally, I'm just waiting to let the other tests finish before I push it (or they'd restart).

File: cpp/src/slice2cpp/Gen.h [hunk 1]
```diff
@@ -218,7 +218,7 @@ namespace Slice
             void visitConst(const ConstPtr&) final;
 
         private:
-            MetadataList validate(const SyntaxTreeBasePtr&, MetadataList, const std::string&, int, bool = false);
+            MetadataList validate(const SyntaxTreeBasePtr&, MetadataList, const std::string&, bool = false);
```
Comment (bernardnormier) [inline cpp/src/slice2cpp/Gen.h:221]: It's nice to add param names when updating functions. Especially when the param names are non-obvious.

Comment (bernardnormier) [reply cpp/src/slice2cpp/Gen.h:221]: You should also add a comment describing what this visitor does; presumably, validate `cpp:...` metadata.

File: cpp/src/slice2cpp/Gen.cpp [hunk 2]
```diff
@@ -1118,7 +1117,7 @@ Slice::Gen::MetadataVisitor::validate(
         {
             ostringstream ostr;
             ostr << "ignoring invalid metadata '" << *meta << "'";
-            dc->warning(InvalidMetadata, file, line, ostr.str());
+            dc->warning(InvalidMetadata, meta->file(), meta->line(), ostr.str());
```
Comment (bernardnormier) [inline cpp/src/slice2cpp/Gen.cpp:1120]: I don't quite follow the `file` vs `meta->file()` in this function. Are they always the same?
Apparently, `file` and `cont` are only used to get `dc` and `dc` is only used to issue warnings.

**Review by bernardnormier — APPROVED** [review]

File: cpp/src/slice2cpp/Gen.cpp (hunk 2 above)
Comment (InsertCreativityHere) [reply cpp/src/slice2cpp/Gen.cpp:1120]: Long story short, it's always safest to get the metadata's file with `meta->file()`.
Most of the time, you're right that it will be the same as `file`, but there's some edge cases where they can differ:
```
// File1
[good-metadata] sequence<int> IntSequence;

// File2
struct S
{
    [bad-metadata] IntSequence is;
}
```
Here, `file` is the file of the actual sequence definition (`File1`), but we want to issue the warning for `File2`.

----

I think we can eliminate the need to get the `dc` with a `file` in the first place, and let `warning` do the lookup using the `file` you pass into it. But obviously, we'd need to move `warning` somewhere else first.
One step at a time though. If you stare at any of our code long enough, you'll find an endless pit of refactoring.

**Review by externl — APPROVED** [review]
Looks good.
