### PR TITLE
Switch 'findMetadata' to Return an 'optional'

### LINKED ISSUE #2021: Warnings for Invalid Metadata are Reported on Incorrect Lines
I was fixing some of our `errorDetection` tests and noticed that the line number are off.
For example, take `WarningInvalidMetaData.ice`

In the source we have: https://github.com/zeroc-ice/ice/blob/60c41eab191ebdc522ac402ff4e0ec96f3c9351a/cpp/test/Slice/errorDetection/WarningInvalidMetaData.ice#L55-L59 But in the expected errors: https://github.com/zeroc-ice/ice/blob/60c41eab191ebdc522ac402ff4e0ec96f3c9351a/cpp/test/Slice/errorDetection/WarningInvalidMetaData.err#L18-L20

You will notice that `56 != 58`.

### PR DESCRIPTION
**Pull request by InsertCreativityHere**
This PR is a preliminary step in improving metadata validation by first improving the metadata APIs.
The biggest change is that instead of `findMetadata` using an out-parameter, it now returns an `optional`.

Also, we have 2 sets of metadata functions (one on `Contained` and one on `DefinitionContext`).
This PR also brings their implementations into alignment, whereas right now, they're actually pretty different.

----

The next step is to add a dedicated `Metadata` grammar element.
This can store a pre-parsed form of the metadata (to skip all the `meta.substr(prefix.length())` you'll see in this PR),
and to let us store it's location (to fix #2021).

### CODE REVIEW

File: cpp/src/Slice/Parser.cpp [hunk 1]
```diff
@@ -136,7 +136,7 @@ Slice::DefinitionContext::setSeenDefinition()
 bool
 Slice::DefinitionContext::hasMetadata(const string& directive) const
```
Comment (InsertCreativityHere) [inline cpp/src/Slice/Parser.cpp:137]: This PR slightly changes the semantics of `hasMetadata`.

Before, we needed an _exact_ match, but now `hasMetadata` will return true even for partial matches.
For example, if you marked a class with `format:compact` and called `hasMetadata("format")` it would return false before,
but now it will return true.

This actually lets us simplify a handful of places where we had this exact kind of case (metadata with arguments).

File: cpp/src/Slice/Parser.cpp [hunk 2]
```diff
@@ -881,38 +884,36 @@ Slice::Contained::includeLevel() const
...
-            return true;
+            return p;
         }
     }
-
-    return false;
+    return nullopt;
 }
 
-list<string>
```
Comment (InsertCreativityHere) [inline cpp/src/Slice/Parser.cpp:902]: We have the alias, might as well use it.
And this makes it consistent with the other metadata functions (where we use the alias).

File: cpp/src/slice2cpp/CPlusPlusUtil.cpp [hunk 3]
```diff
@@ -784,15 +784,15 @@ Slice::writeAllocateCode(
     const string& clScope,
     TypeContext typeCtx)
 {
-    for (ParamDeclList::const_iterator p = params.begin(); p != params.end(); ++p)
```
Comment (InsertCreativityHere) [inline cpp/src/slice2cpp/CPlusPlusUtil.cpp:787]: I also updated some for loops, while searching for the metadata functions.

File: cpp/src/slice2cpp/CPlusPlusUtil.cpp [hunk 4]
```diff
@@ -975,32 +975,6 @@ Slice::writeIceTuple(::IceInternal::Output& out, DataMemberList dataMembers, Typ
     out << ");" << eb;
 }
 
-bool
```
Comment (InsertCreativityHere) [inline cpp/src/slice2cpp/CPlusPlusUtil.cpp:978]: These 2 `findMetadata` functions were unused.

There's another `findMetadata` you can see underneath these 2 that I'd like to remove in the future,
but it's used in lots of places. So I'll deal with it in a future PR.

File: cpp/src/slice2js/JsUtil.cpp [hunk 5]
```diff
@@ -196,21 +196,6 @@ Slice::JsGenerator::fixDataMemberName(const std::string& name, bool isStruct, bo
     return Slice::JsGenerator::fixId(name);
 }
 
-bool
-Slice::JsGenerator::findMetadata(const string& prefix, const StringList& metadata, string& value)
```
Comment (InsertCreativityHere) [inline cpp/src/slice2js/JsUtil.cpp:200]: Dead function.

File: cpp/src/slice2swift/SwiftUtil.cpp [hunk 6]
```diff
@@ -1668,26 +1668,8 @@ SwiftGenerator::MetadataVisitor::visitModuleStart(const ModulePtr& p)
         // top-level module
         const UnitPtr unit = p->unit();
```
Comment (InsertCreativityHere) [inline cpp/src/slice2swift/SwiftUtil.cpp:1670]: This logic was just a duplicate of the `getSwiftModule` function that you can see above here.

File: cpp/src/Slice/Parser.cpp (hunk 1 above)
Comment (pepone) [reply cpp/src/Slice/Parser.cpp:137]: Looking at how this is implemented, shouldn't we check it is `== directive` or  starts with `directive:`

In other words `hasMetadata("format")` should return `false` for `[formating]` or other cases where the common prefix refers to a different metadata.

File: cpp/src/Slice/Parser.cpp [hunk 7]
```diff
@@ -952,31 +953,40 @@ Slice::Contained::isDeprecated(bool checkParent) const
 {
     const string prefix1 = "deprecate";
     const string prefix2 = "deprecated";
-    string metadata;
     ContainedPtr parent = checkParent ? dynamic_pointer_cast<Contained>(_container) : nullptr;
 
-    return (findMetadata(prefix1, metadata) || (parent && parent->findMetadata(prefix1, metadata))) ||
-           (findMetadata(prefix2, metadata) || (parent && parent->findMetadata(prefix2, metadata)));
+    return (hasMetadata(prefix1) || (parent && parent->hasMetadata(prefix1))) ||
```
Comment (pepone) [inline cpp/src/Slice/Parser.cpp:958]: With the updated `hasMetadata` using "deprecate" matches both, but I guess is not intentional.

File: cpp/src/slice2rb/RubyUtil.cpp [hunk 8]
```diff
@@ -583,7 +582,7 @@ Slice::Ruby::CodeVisitor::visitInterfaceDefStart(const InterfaceDefPtr& p)
                 _out << "::Ice::OperationMode::Idempotent";
                 break;
         }
-        _out << ", " << ((p->hasMetadata("amd") || (*s)->hasMetadata("amd")) ? "true" : "false") << ", " << format
+        _out << ", " << ((p->hasMetadata("amd") || op->hasMetadata("amd")) ? "true" : "false") << ", " << format
```
Comment (pepone) [inline cpp/src/slice2rb/RubyUtil.cpp:585]: I wonder why Ruby has this "amd" checks, when there isn't a server side mapping, looks suspicious.

**Review by pepone — APPROVED** [review]

File: cpp/src/Slice/Parser.cpp (hunk 7 above)
Comment (externl) [reply cpp/src/Slice/Parser.cpp:958]: It would be nice to just support one flavor for this metadata.

File: cpp/src/slice2rb/RubyUtil.cpp (hunk 8 above)
Comment (externl) [reply cpp/src/slice2rb/RubyUtil.cpp:585]: Would be good to open an issue to review this and probably remove it.

**Review by externl — APPROVED** [review]

File: cpp/src/Slice/Parser.cpp (hunk 7 above)
Comment (InsertCreativityHere) [reply cpp/src/Slice/Parser.cpp:958]: Yes, the loosening of `findsMetadata` was only going to be temporary, so I didn't want to cause more trouble for future me!

I think that "only supporting one" is the future goal. As of 3.7 we only supported `deprecate`, but with `3.8` we wanted to switch it to `deprecated`. That's a pretty negligible change though, so we didn't want to annoy users. In 3.9 I image we'll finalize the switch, or at least deprecate `deprecate`.
