### PR TITLE
Simplify mapping for user exceptions in MATLAB, PHP and Ruby

### LINKED ISSUE #2403: Simplify user exceptions in MATLAB, PHP and Ruby
In the client-only language mappings, the application code does not ever need to construct or throw a user exceptions, since user exceptions are only transmitted from the server back to the client.

As a result, the mapped user exceptions are only created from the C++ code. The code and documentation for mapped user exceptions can be greatly simplified. Most of the documentation here is not useful:

https://doc.zeroc.com/ice/3.7/language-mappings/matlab-mapping/client-side-slice-to-matlab-mapping/matlab-mapping-for-exceptions#id-.MATLABMappingforExceptionsv3.7-MATLABMappingforUserExceptions

https://doc.zeroc.com/ice/3.7/language-mappings/php-mapping/client-side-slice-to-php-mapping/php-mapping-for-exceptions#id-.PHPMappingforExceptionsv3.7-PHPMappingforUserExceptions

https://doc.zeroc.com/ice/3.7/language-mappings/ruby-mapping/client-side-slice-to-ruby-mapping/ruby-mapping-for-exceptions#id-.RubyMappingforExceptionsv3.7-RubyMappingforUserExceptions

### PR DESCRIPTION
**Pull request by bernardnormier**
This PR removes the generated constructor or simplifies it. In this client-side only mapping, the user exceptions are only constructed by the Ice runtime.

Fixes #2403.

### CODE REVIEW

File: cpp/src/slice2matlab/Main.cpp [hunk 1]
```diff
@@ -2658,71 +2658,39 @@ CodeVisitor::visitExceptionStart(const ExceptionPtr& p)
     //
     // Constructor
     //
-    out << nl << "function " << self << " = " << name << spar << "ice_exid"
-        << "ice_exmsg" << allNames << epar;
+    out << nl << "function " << self << " = " << name << spar << "errID" << "msg" << epar;
```
Comment (bernardnormier) [inline cpp/src/slice2matlab/Main.cpp:2661]: We still need to generate a constructor in MATLAB to fill-out errID + msg because the "activator" constructs the exception class with no argument.

File: matlab/test/Ice/defaultValue/Test.ice [hunk 2]
```diff
@@ -119,36 +119,6 @@ class Derived extends Base
     Nested::Color nc3 = blue;
 }
 
-exception BaseEx
```
Comment (bernardnormier) [inline matlab/test/Ice/defaultValue/Test.ice:122]: We had a fairly comprehensive testing for the user exception constructors even through it makes no sense to construct a user exception from a client-side only mapping.

File: matlab/lib/+Ice/UserException.m [hunk 3]
```diff
@@ -12,20 +12,6 @@
     methods(Abstract)
         ice_id(obj)
     end
-    methods
-        function obj = UserException(id, msg)
-            obj = obj@Ice.Exception(id, msg);
-        end
-        % ice_getSlicedData - Obtain the SlicedData object that contains the
```
Comment (pepone) [inline matlab/lib/+Ice/UserException.m:19]: Why are we removing this method?

Note it is still mentioned above in `% UserException Methods:`

**Review by pepone — APPROVED** [review]

File: matlab/lib/+Ice/UserException.m (hunk 3 above)
Comment (bernardnormier) [reply matlab/lib/+Ice/UserException.m:19]: Sorry, forgot to comment on it.

This is part of the left-over preserve-slice simplification that Benoit is working on.

With the simplified 3.8 version (mostly but not fully implemented - in particular, not in MATLAB):
 - user exceptions are always encoded in the Sliced format but are never preserved
 - class encoded in the Slice format are always preserved

That's already implemented in https://github.com/icerpc/icerpc-csharp.

Comment (bernardnormier) [reply matlab/lib/+Ice/UserException.m:19]: Fixed doc-comment.

**Review by externl — APPROVED** [review]
