### PR TITLE
Fix C++ buffer memory leak

### LINKED ISSUE #3726: swift/Ice/location failing on iOS
This test keeps failing on CI on iOS

```
2025-03-17T22:20:55.4866070Z *** [51/63] Running swift/Ice/location tests ***
2025-03-17T22:20:55.4965800Z [ running client/server test - 03/17/25 22:16:30 ]
2025-03-17T22:20:55.5074930Z - Config: ssl,mx,iphonesimulator
2025-03-17T22:20:55.5230900Z (executing `Ice/location/Server' on `iOS Simulator (iOS-18-4)' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.Default.Protocol=ssl', '--Ice.IPv6=0', '--Ice.Admin.Endpoints=tcp -h 127.0.0.1', '--Ice.Admin.InstanceName=Server', '--IceMX.Metrics.Debug.GroupBy=id', '--IceMX.Metrics.Parent.GroupBy=parent', '--IceMX.Metrics.All.GroupBy=none', '--IceSSL.***', '--IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs', '--IceSSL.CAs=cacert.pem', '--IceSSL.CertFile=server.p12', '--IceSSL.KeychainPassword=password', '--IceSSL.Keychain=server.keychain', '--Ice.ThreadPool.Server.Size=1', '--Ice.ThreadPool.Server.SizeMax=3', '--Ice.ThreadPool.Server.SizeWarn=0'])
2025-03-17T22:20:55.5282970Z (executing `Ice/location/Client' on `iOS Simulator (iOS-18-4)' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.Default.Protocol=ssl', '--Ice.IPv6=0', '--Ice.Admin.Endpoints=tcp -h 127.0.0.1', '--Ice.Admin.InstanceName=Client', '--IceMX.Metrics.Debug.GroupBy=id', '--IceMX.Metrics.Parent.GroupBy=parent', '--IceMX.Metrics.All.GroupBy=none', '--IceSSL.***', '--IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs', '--IceSSL.CAs=cacert.pem', '--IceSSL.CertFile=client.p12', '--IceSSL.KeychainPassword=password', '--IceSSL.Keychain=client.keychain'])
2025-03-17T22:20:55.5416780Z Traceback (most recent call last):
2025-03-17T22:20:55.5533380Z   File "/Users/runner/work/ice/ice/scripts/LocalDriver.py", line 678, in runClientServerTestCase
2025-03-17T22:20:55.5632740Z     self.runner.runClientSide(client, current, host)
```

### PR DESCRIPTION
**Pull request by externl**
This PR fixes a memory leak in the Ice::Buffer move assignment operator.

Fixes #3726 and  #3634 (hopefully 😄)

### CODE REVIEW

File: cpp/src/Ice/Buffer.cpp [hunk 1]
```diff
@@ -90,6 +90,11 @@ IceInternal::Buffer::Container::operator=(Container&& other) noexcept
 {
     if (this != &other)
     {
+        // If we own the buffer, free it first.
+        if (_buf && _owned)
```
Comment (pepone) [inline cpp/src/Ice/Buffer.cpp:94]: Looks good!

Side note: It’s fine to call `::free(nullptr)`. I think we should refactor the `::free` calls in this class to remove the `_buf` check.

**Review by pepone — APPROVED** [review]

**Review by bernardnormier — APPROVED** [review]
