### PR TITLE
Fix JavaScript deprecated doc comments

### LINKED ISSUE #3093: JavaScript deprecated metadata ignored for elements without a doc comment
There is a small issue here, definition marked as deprecated with metadata without a doc comment would be not marked as deprecated in JavaScript because of this early return.

Fixing in a follow up PR.

_Originally posted by @pepone in https://github.com/zeroc-ice/ice/pull/3086#discussion_r1832907634_

### PR DESCRIPTION
**Pull request by pepone**
Fix #3093

### CODE REVIEW

File: cpp/src/slice2js/Gen.cpp [hunk 1]
```diff
@@ -2563,16 +2571,8 @@ Slice::Gen::TypeScriptVisitor::visitInterfaceDefStart(const InterfaceDefPtr& p)
             }
         }
 
-        const string contextParam = escapeParam(paramList, "context");
-        CommentPtr comment = op->parseComment(jsLinkFormatter);
-        const string contextDoc = "@param " + contextParam + " The Context map to send with the invocation.";
-        const string asyncDoc = "The asynchronous result object for the invocation.";
```
Comment (pepone) [inline cpp/src/slice2js/Gen.cpp:2569]: Unused, this was move to writeOpDocSummary a while ago.

File: cpp/src/slice2js/Gen.cpp [hunk 2]
```diff
@@ -163,6 +163,27 @@ namespace
...
+    void writeDeprecated(Output& out, const CommentPtr& comment, const ContainedPtr& contained)
+    {
+        // JavaScript doesn't provide a way to deprecate elements other than by using a comment, so we map both the
+        // Slice @deprecated tag and the deprecated metadata argument to a `@deprecated` JSDoc tag.
+        if ((comment && comment->isDeprecated()) || contained->isDeprecated())
+        {
+            out << nl << " * @deprecated";
+            // If a reason was supplied, append it after the `@deprecated` tag. If no reason was supplied, fallback to
+            // the deprecated metadata argument.
+            if (!comment->deprecated().empty())
```
Comment (bernardnormier) [inline cpp/src/slice2js/Gen.cpp:175]: We should fix the Comment API. isDeprecated + deprecated is not a good API.

File: cpp/src/slice2js/Gen.cpp [hunk 3]
```diff
@@ -163,6 +163,27 @@ namespace
...
+            {
+                out << " ";
+                writeDocLines(out, comment->deprecated(), false);
+            }
+            else if (auto deprecated = contained->getDeprecationReason())
```
Comment (bernardnormier) [inline cpp/src/slice2js/Gen.cpp:180]: We should think about and settle on a good terminology for deprecated. I am not a fan of deprecationReason when the metadata and doc-comment are 'deprecated'.

**Review by bernardnormier — APPROVED** [review]
