### PR TITLE
slice2java: fix constructor parameter count check

### LINKED ISSUE #1539: slice2java: fix max parameter count for constructors
Java constructors must have a "length" that is less than 255. This length is not the number of parameters, but a special UNIT where all types are size 1 except long and double, which are 2.

The `slice2java` constructor does not count this number correctly and only looks at the number of parameters. 

https://github.com/zeroc-ice/ice/blob/3.7/cpp/src/slice2java/Gen.cpp#L2554-L2557

This means that we can generate code that does not compile. For instance if you have a class with 127 doubles. 

**Proposed fix:**
Fix the check to account for the correct size of long and double.

### PR DESCRIPTION
**Pull request by externl**
Closes #1539

### CODE REVIEW

**Review by pepone — APPROVED** [review]

File: cpp/src/slice2java/GenCompat.cpp [hunk 1]
```diff
@@ -210,6 +210,28 @@ writeParamList(Output& out, vector<string> params, bool end = true, bool newLine
     }
 }
 
+// Returns the "length" of the constructor parameter list from the given data member list.
+// All types are counted as 1, except for long and double which are counted as 2.
```
Comment (InsertCreativityHere) [inline cpp/src/slice2java/GenCompat.cpp:214]: Just to tie into the terminology used by the JVM.
```suggestion
// All types are counted as 1 unit, except for long and double which are counted as 2 units.
```

File: cpp/src/slice2java/Gen.cpp [hunk 2]
```diff
@@ -136,6 +136,28 @@ string ofFactory(const TypePtr& type)
     return "java.util.Optional.ofNullable";
 }
 
+// Returns the "length" of the constructor parameter list from the given data member list.
+// All types are counted as 1, except for long and double which are counted as 2.
```
Comment (InsertCreativityHere) [inline cpp/src/slice2java/Gen.cpp:140]:
```suggestion
// All types are counted as 1 unit, except for long and double which are counted as 2 units.
```

**Review by InsertCreativityHere — APPROVED** [review]
Looks good!

File: cpp/src/slice2java/Gen.cpp [hunk 3]
```diff
@@ -136,6 +136,28 @@ string ofFactory(const TypePtr& type)
...
+// See https://docs.oracle.com/javase/specs/jvms/se20/html/jvms-4.html#jvms-4.3.3
+int
+constructorParameterLength(const DataMemberList& members)
+{
+    int length = 0;
+    for(DataMemberList::const_iterator i = members.begin(); i != members.end(); ++i)
```
Comment (bernardnormier) [inline cpp/src/slice2java/Gen.cpp:146]: I think `p` is a more common iterator name.

File: cpp/src/slice2java/Gen.cpp [hunk 4]
```diff
@@ -136,6 +136,28 @@ string ofFactory(const TypePtr& type)
     return "java.util.Optional.ofNullable";
 }
 
+// Returns the "length" of the constructor parameter list from the given data member list.
+// All types are counted as 1, except for long and double which are counted as 2.
+// See https://docs.oracle.com/javase/specs/jvms/se20/html/jvms-4.html#jvms-4.3.3
+int
+constructorParameterLength(const DataMemberList& members)
+{
+    int length = 0;
```
Comment (bernardnormier) [inline cpp/src/slice2java/Gen.cpp:145]: I think it would be much more logical to include "this" in this computation, i.e. start length at 1 AND add a clear comment.

File: cpp/src/slice2java/Gen.cpp [hunk 5]
```diff
@@ -2554,7 +2576,7 @@ Slice::Gen::TypesVisitor::visitClassDefStart(const ClassDefPtr& p)
         //
         // A method cannot have more than 255 parameters (including the implicit "this" argument).
         //
-        if(allDataMembers.size() < 255)
+        if(constructorParameterLength(allDataMembers) < 255)
```
Comment (bernardnormier) [inline cpp/src/slice2java/Gen.cpp:2579]: Should be `<= 255` - see earlier comment about this.

File: cpp/src/slice2java/GenCompat.cpp [hunk 6]
```diff
@@ -210,6 +210,28 @@ writeParamList(Output& out, vector<string> params, bool end = true, bool newLine
...
+// See https://docs.oracle.com/javase/specs/jvms/se20/html/jvms-4.html#jvms-4.3.3
+int
+constructorParameterLength(const DataMemberList& members)
```
Comment (bernardnormier) [inline cpp/src/slice2java/GenCompat.cpp:217]: We really don't have any shared code between slice2java and slice2java --compat??

File: cpp/src/slice2java/Gen.cpp (hunk 3 above)
Comment (externl) [reply cpp/src/slice2java/Gen.cpp:146]: I think both are pretty common, I can change to `p` though.

File: cpp/src/slice2java/GenCompat.cpp (hunk 6 above)
Comment (externl) [reply cpp/src/slice2java/GenCompat.cpp:217]: No

Comment (bernardnormier) [reply cpp/src/slice2java/GenCompat.cpp:217]: You should move it to Slice/JavaUtil.h

Comment (externl) [reply cpp/src/slice2java/GenCompat.cpp:217]: Right, I forgot about those. Will fix.

**Comment by externl** [comment]
I reworked the logic a bit. The new method now returns a bool indicating if the length is ok. I also found a few other places that needed fixing. I think this is cleaner than having lots of magic numbers (254, 255) scattered throughout the code.

**Review by pepone — APPROVED** [review]

File: cpp/src/Slice/JavaUtil.h [hunk 7]
```diff
@@ -29,6 +29,15 @@ computeSerialVersionUUID(const ExceptionPtr&);
...
 computeSerialVersionUUID(const StructPtr&);
 
+//
+// Returns true if we can generate a method from the given data member list. A Java method
+// can have a maximum of 255 parameters (including the implicit 'this') where each parameter
+// is counted as 1 unit, except for long and double which are counted as 2 units.
+// See https://docs.oracle.com/javase/specs/jvms/se20/html/jvms-4.html#jvms-4.3.3
+//
+bool
+isValidMethodParameterList(const DataMemberList &, int additionalUnits = 0);
```
Comment (InsertCreativityHere) [inline cpp/src/Slice/JavaUtil.h:39]:
```suggestion
isValidMethodParameterList(const DataMemberList&, int additionalUnits = 0);
```

**Review by bernardnormier — APPROVED** [review]

**Review by InsertCreativityHere — APPROVED** [review]
